scim: scim::Signal1< R, P1, Marshal > Class Template Reference
scim::Signal1< R, P1, Marshal > Class Template Reference
SignalSlot
A template for a signal passing one argument of type P1 and returning a value of type R.
#include <scim_signals.h>
Public Types
typedef Slot1< R, P1 > SlotType
Function signature for handlers connecting to the signal.
Public Member Functions
Connection connect (SlotType *slot)
SlotType * slot ()
R emit (P1 p1)
R operator() (P1 p1)
Function operator; calls emit().
Public Member Functions inherited from scim::Signal
Signal ()
Constructor.
virtual ~Signal ()
Destructor.
SlotNode * connect (Slot *slot)
Creates a new SlotNode for slot and adds it to the connection_list.
Additional Inherited Members
Protected Types inherited from scim::Signal
typedef std::vector< Pointer
< SlotNode > > ConnectionList
ConnectionList type.
Protected Attributes inherited from scim::Signal
ConnectionList connection_list
A list of all the slots connected to the signal.
Detailed Description
template<typename R, typename P1, typename Marshal = class DefaultMarshal<R>>
class scim::Signal1< R, P1, Marshal >
A template for a signal passing one argument of type P1 and returning a value of type R.
Member Typedef Documentation
template<typename R, typename P1, typename Marshal = class DefaultMarshal<R>> typedef Slot1<R, P1> scim::Signal1< R, P1, Marshal >::SlotType
Function signature for handlers connecting to the signal.
Member Function Documentation
template<typename R, typename P1, typename Marshal = class DefaultMarshal<R>> Connection scim::Signal1< R, P1, Marshal >::connect (SlotType * slot) inline
Connect a slot to the signal.
Parameters
slot - a slot of type Slot1<R, P1>.
Returns
a connection object.
The returned connection object can be used alter or change the connection.
template<typename R, typename P1, typename Marshal = class DefaultMarshal<R>> SlotType* scim::Signal1< R, P1, Marshal >::slot () inline
Returns a slot for this signal.
Returns
a new slot of type Slot1<R, P1>.
The returned slot can be passed to another signal allowing the other signal to call this signal when it gets emitted.
Referenced by scim::Signal1< void, const ConfigPointer & >::emit(), and scim::Signal1< void, P1, IgnoreMarshal >::emit().
template<typename R, typename P1, typename Marshal = class DefaultMarshal<R>> R scim::Signal1< R, P1, Marshal >::emit (P1 p1) inline
Emit the signal.
Parameters
p1 - passes p1 to the signal handler.
Returns
the value returned by the signal handler.
Calls every slot connected to this signal, in order of connection.
Referenced by scim::Signal1< void, const ConfigPointer & >::operator()(), and scim::Signal1< void, P1, IgnoreMarshal >::operator()().
template<typename R, typename P1, typename Marshal = class DefaultMarshal<R>> R scim::Signal1< R, P1, Marshal >::operator() (P1 p1) inline
Function operator; calls emit().
The documentation for this class was generated from the following file:
scim_signals.h