scim: scim::Slot6< R, P1, P2, P3, P4, P5, P6 > Class Template Reference
scim::Slot6< R, P1, P2, P3, P4, P5, P6 > Class Template Reference abstract
SignalSlot
Base class template for slots passing six arguments of type P1, P2, P3, P4, P5 and P6, and returning a value of type R.
#include <scim_slot.h>
Public Member Functions
virtual R call (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5, P6 p6) const =0
Calls the signal handler connected to this slot.
R operator() (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5, P6 p6) const
Function operator; Calls call().
Public Member Functions inherited from scim::ReferencedObject
bool is_referenced () const
void ref ()
Increase an object's reference count by one.
void unref ()
Protected Member Functions
Slot6 ()
Constructor.
Protected Member Functions inherited from scim::Slot
Slot ()
Constructor.
virtual ~Slot ()=0
Destructor.
Protected Member Functions inherited from scim::ReferencedObject
ReferencedObject ()
Constructor.
virtual ~ReferencedObject ()=0
Destructor.
void set_referenced (bool reference)
Detailed Description
template<typename R, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6>
class scim::Slot6< R, P1, P2, P3, P4, P5, P6 >
Base class template for slots passing six arguments of type P1, P2, P3, P4, P5 and P6, and returning a value of type R.
Constructor & Destructor Documentation
template<typename R, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6> scim::Slot6< R, P1, P2, P3, P4, P5, P6 >::Slot6 () inline protected
Constructor.
Member Function Documentation
template<typename R, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6> virtual R scim::Slot6< R, P1, P2, P3, P4, P5, P6 >::call (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5, P6 p6) const pure virtual
Calls the signal handler connected to this slot.
Implemented in scim::SignalSlot6< T, R, P1, P2, P3, P4, P5, P6 >, scim::MethodSlot6< T, R, P1, P2, P3, P4, P5, P6 >, and scim::FunctionSlot6< R, P1, P2, P3, P4, P5, P6 >.
Referenced by scim::Signal6< R, P1, P2, P3, P4, P5, P6, Marshal >::emit(), scim::Signal6< void, P1, P2, P3, P4, P5, P6, IgnoreMarshal >::emit(), and scim::Slot6< R, P1, P2, P3, P4, P5, P6 >::operator()().
template<typename R, typename P1, typename P2, typename P3, typename P4, typename P5, typename P6> R scim::Slot6< R, P1, P2, P3, P4, P5, P6 >::operator() (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5, P6 p6) const inline
Function operator; Calls call().
References scim::Slot6< R, P1, P2, P3, P4, P5, P6 >::call().
The documentation for this class was generated from the following file:
scim_slot.h