scim: Accessories
Accessories
Classes
class scim::Attribute
Class to store the string attributes.
struct scim::KeyEvent
The class to store a keyboard event.
class scim::Exception
A base class of all other exception classes.
class scim::HotkeyMatcher
This class is used to match a KeyEvent among a set of hotkeys.
class scim::IMEngineHotkeyMatcher
This class hold all Hotkeys for each IMEngines.
class scim::FrontEndHotkeyMatcher
This class hold all FrontEnd specific Hotkeys, such as trigger keys, on/off keys, etc.
class scim::IConvert
A class to convert strings between UCS-4 and local encodings.
class scim::LookupTable
The base class of lookup table.
class scim::CommonLookupTable
A common lookup table class.
class scim::ModuleError
class scim::Module
class scim::ReferencedObject
Reference counted base class.
class scim::Pointer< T >
Smart pointer template class.
class scim::Property
Class to hold a property of a IMEngineInstance object or a Panel GUI client.
Macros
#define SCIM_RGB_COLOR(RED, GREEN, BLUE) ((unsigned int)(((RED)<<16) + ((GREEN)<<8) + (BLUE)))
#define SCIM_RGB_COLOR_RED(COLOR) ((unsigned int)((COLOR>>16) & 0x00ff))
#define SCIM_RGB_COLOR_GREEN(COLOR) ((unsigned int)((COLOR>>8) & 0x00ff))
#define SCIM_RGB_COLOR_BLUE(COLOR) ((unsigned int)((COLOR) & 0x00ff))
#define SCIM_MAX_BUFSIZE 4096
#define SCIM_LOOKUP_TABLE_MAX_PAGESIZE 16
#define SCIM_PATH_DELIM_STRING "/"
#define SCIM_PATH_DELIM '/'
#define RET_ILSEQ 0
#define RET_TOOFEW(n) (-1-(n))
#define RET_TOOSMALL -1
#define BAD_WCHAR ((ucs4_t) 0xfffd)
#define BAD_CHAR '?'
Typedefs
typedef std::vector< Attribute > scim::AttributeList
The container to store a set of Attribute objects.
typedef std::vector< KeyEvent > scim::KeyEventList
The container to store a set of KeyEvent objects.
typedef std::vector< Property > scim::PropertyList
The container to store a set of Properties.
Enumerations
enum scim::AttributeType { scim::SCIM_ATTR_NONE, scim::SCIM_ATTR_DECORATE, scim::SCIM_ATTR_FOREGROUND, scim::SCIM_ATTR_BACKGROUND }
Enum values of the valid attribute type.
enum scim::KeyMask {
scim::SCIM_KEY_NullMask = 0, scim::SCIM_KEY_ShiftMask = (1<<0), scim::SCIM_KEY_CapsLockMask = (1<<1), scim::SCIM_KEY_ControlMask = (1<<2),
scim::SCIM_KEY_AltMask = (1<<3), scim::SCIM_KEY_MetaMask = (1<<4), scim::SCIM_KEY_SuperMask = (1<<5), scim::SCIM_KEY_HyperMask = (1<<6),
scim::SCIM_KEY_NumLockMask = (1<<7), scim::SCIM_KEY_LockMask = SCIM_KEY_CapsLockMask, scim::SCIM_KEY_Mod1Mask = SCIM_KEY_AltMask, scim::SCIM_KEY_Mod2Mask = SCIM_KEY_MetaMask,
scim::SCIM_KEY_Mod3Mask = SCIM_KEY_SuperMask, scim::SCIM_KEY_Mod4Mask = SCIM_KEY_HyperMask, scim::SCIM_KEY_Mod5Mask = SCIM_KEY_NumLockMask, scim::SCIM_KEY_ScrollLockMask = 0,
scim::SCIM_KEY_QuirkKanaRoMask = (1<<14), scim::SCIM_KEY_ReleaseMask = (1<<15), scim::SCIM_KEY_AllMasks = 0xC0FF
}
Enum values of all valid key masks.
enum scim::KeyCode {
scim::SCIM_KEY_NullKey = 0, scim::SCIM_KEY_VoidSymbol = 0xFFFFFF, scim::SCIM_KEY_BackSpace = 0xFF08, scim::SCIM_KEY_Tab = 0xFF09,
scim::SCIM_KEY_Linefeed = 0xFF0A, scim::SCIM_KEY_Clear = 0xFF0B, scim::SCIM_KEY_Return = 0xFF0D, scim::SCIM_KEY_Pause = 0xFF13,
scim::SCIM_KEY_Scroll_Lock = 0xFF14, scim::SCIM_KEY_Sys_Req = 0xFF15, scim::SCIM_KEY_Escape = 0xFF1B, scim::SCIM_KEY_Delete = 0xFFFF,
scim::SCIM_KEY_Multi_key = 0xFF20, scim::SCIM_KEY_Codeinput = 0xFF37, scim::SCIM_KEY_SingleCandidate = 0xFF3C, scim::SCIM_KEY_MultipleCandidate = 0xFF3D,
scim::SCIM_KEY_PreviousCandidate = 0xFF3E, scim::SCIM_KEY_Kanji = 0xFF21, scim::SCIM_KEY_Muhenkan = 0xFF22, scim::SCIM_KEY_Henkan_Mode = 0xFF23,
scim::SCIM_KEY_Henkan = 0xFF23, scim::SCIM_KEY_Romaji = 0xFF24, scim::SCIM_KEY_Hiragana = 0xFF25, scim::SCIM_KEY_Katakana = 0xFF26,
scim::SCIM_KEY_Hiragana_Katakana = 0xFF27, scim::SCIM_KEY_Zenkaku = 0xFF28, scim::SCIM_KEY_Hankaku = 0xFF29, scim::SCIM_KEY_Zenkaku_Hankaku = 0xFF2A,
scim::SCIM_KEY_Touroku = 0xFF2B, scim::SCIM_KEY_Massyo = 0xFF2C, scim::SCIM_KEY_Kana_Lock = 0xFF2D, scim::SCIM_KEY_Kana_Shift = 0xFF2E,
scim::SCIM_KEY_Eisu_Shift = 0xFF2F, scim::SCIM_KEY_Eisu_toggle = 0xFF30, scim::SCIM_KEY_Kanji_Bangou = 0xFF37, scim::SCIM_KEY_Zen_Koho = 0xFF3D,
scim::SCIM_KEY_Mae_Koho = 0xFF3E, scim::SCIM_KEY_Home = 0xFF50, scim::SCIM_KEY_Left = 0xFF51, scim::SCIM_KEY_Up = 0xFF52,
scim::SCIM_KEY_Right = 0xFF53, scim::SCIM_KEY_Down = 0xFF54, scim::SCIM_KEY_Prior = 0xFF55, scim::SCIM_KEY_Page_Up = 0xFF55,
scim::SCIM_KEY_Next = 0xFF56, scim::SCIM_KEY_Page_Down = 0xFF56, scim::SCIM_KEY_End = 0xFF57, scim::SCIM_KEY_Begin = 0xFF58,
scim::SCIM_KEY_Select = 0xFF60, scim::SCIM_KEY_Print = 0xFF61, scim::SCIM_KEY_Execute = 0xFF62, scim::SCIM_KEY_Insert = 0xFF63,
scim::SCIM_KEY_Undo = 0xFF65, scim::SCIM_KEY_Redo = 0xFF66, scim::SCIM_KEY_Menu = 0xFF67, scim::SCIM_KEY_Find = 0xFF68,
scim::SCIM_KEY_Cancel = 0xFF69, scim::SCIM_KEY_Help = 0xFF6A, scim::SCIM_KEY_Break = 0xFF6B, scim::SCIM_KEY_Mode_switch = 0xFF7E,
scim::SCIM_KEY_Num_Lock = 0xFF7F, scim::SCIM_KEY_KP_Space = 0xFF80, scim::SCIM_KEY_KP_Tab = 0xFF89, scim::SCIM_KEY_KP_Enter = 0xFF8D,
scim::SCIM_KEY_KP_F1 = 0xFF91, scim::SCIM_KEY_KP_F2 = 0xFF92, scim::SCIM_KEY_KP_F3 = 0xFF93, scim::SCIM_KEY_KP_F4 = 0xFF94,
scim::SCIM_KEY_KP_Home = 0xFF95, scim::SCIM_KEY_KP_Left = 0xFF96, scim::SCIM_KEY_KP_Up = 0xFF97, scim::SCIM_KEY_KP_Right = 0xFF98,
scim::SCIM_KEY_KP_Down = 0xFF99, scim::SCIM_KEY_KP_Prior = 0xFF9A, scim::SCIM_KEY_KP_Page_Up = 0xFF9A, scim::SCIM_KEY_KP_Next = 0xFF9B,
scim::SCIM_KEY_KP_Page_Down = 0xFF9B, scim::SCIM_KEY_KP_End = 0xFF9C, scim::SCIM_KEY_KP_Begin = 0xFF9D, scim::SCIM_KEY_KP_Insert = 0xFF9E,
scim::SCIM_KEY_KP_Delete = 0xFF9F, scim::SCIM_KEY_KP_Equal = 0xFFBD, scim::SCIM_KEY_KP_Multiply = 0xFFAA, scim::SCIM_KEY_KP_Add = 0xFFAB,
scim::SCIM_KEY_KP_Separator = 0xFFAC, scim::SCIM_KEY_KP_Subtract = 0xFFAD, scim::SCIM_KEY_KP_Decimal = 0xFFAE, scim::SCIM_KEY_KP_Divide = 0xFFAF,
scim::SCIM_KEY_KP_0 = 0xFFB0, scim::SCIM_KEY_KP_1 = 0xFFB1, scim::SCIM_KEY_KP_2 = 0xFFB2, scim::SCIM_KEY_KP_3 = 0xFFB3,
scim::SCIM_KEY_KP_4 = 0xFFB4, scim::SCIM_KEY_KP_5 = 0xFFB5, scim::SCIM_KEY_KP_6 = 0xFFB6, scim::SCIM_KEY_KP_7 = 0xFFB7,
scim::SCIM_KEY_KP_8 = 0xFFB8, scim::SCIM_KEY_KP_9 = 0xFFB9, scim::SCIM_KEY_F1 = 0xFFBE, scim::SCIM_KEY_F2 = 0xFFBF,
scim::SCIM_KEY_F3 = 0xFFC0, scim::SCIM_KEY_F4 = 0xFFC1, scim::SCIM_KEY_F5 = 0xFFC2, scim::SCIM_KEY_F6 = 0xFFC3,
scim::SCIM_KEY_F7 = 0xFFC4, scim::SCIM_KEY_F8 = 0xFFC5, scim::SCIM_KEY_F9 = 0xFFC6, scim::SCIM_KEY_F10 = 0xFFC7,
scim::SCIM_KEY_F11 = 0xFFC8, scim::SCIM_KEY_F12 = 0xFFC9, scim::SCIM_KEY_F13 = 0xFFCA, scim::SCIM_KEY_F14 = 0xFFCB,
scim::SCIM_KEY_F15 = 0xFFCC, scim::SCIM_KEY_F16 = 0xFFCD, scim::SCIM_KEY_F17 = 0xFFCE, scim::SCIM_KEY_F18 = 0xFFCF,
scim::SCIM_KEY_F19 = 0xFFD0, scim::SCIM_KEY_F20 = 0xFFD1, scim::SCIM_KEY_F21 = 0xFFD2, scim::SCIM_KEY_F22 = 0xFFD3,
scim::SCIM_KEY_F23 = 0xFFD4, scim::SCIM_KEY_F24 = 0xFFD5, scim::SCIM_KEY_F25 = 0xFFD6, scim::SCIM_KEY_F26 = 0xFFD7,
scim::SCIM_KEY_F27 = 0xFFD8, scim::SCIM_KEY_F28 = 0xFFD9, scim::SCIM_KEY_F29 = 0xFFDA, scim::SCIM_KEY_F30 = 0xFFDB,
scim::SCIM_KEY_F31 = 0xFFDC, scim::SCIM_KEY_F32 = 0xFFDD, scim::SCIM_KEY_F33 = 0xFFDE, scim::SCIM_KEY_F34 = 0xFFDF,
scim::SCIM_KEY_F35 = 0xFFE0, scim::SCIM_KEY_Shift_L = 0xFFE1, scim::SCIM_KEY_Shift_R = 0xFFE2, scim::SCIM_KEY_Control_L = 0xFFE3,
scim::SCIM_KEY_Control_R = 0xFFE4, scim::SCIM_KEY_Caps_Lock = 0xFFE5, scim::SCIM_KEY_Shift_Lock = 0xFFE6, scim::SCIM_KEY_Meta_L = 0xFFE7,
scim::SCIM_KEY_Meta_R = 0xFFE8, scim::SCIM_KEY_Alt_L = 0xFFE9, scim::SCIM_KEY_Alt_R = 0xFFEA, scim::SCIM_KEY_Super_L = 0xFFEB,
scim::SCIM_KEY_Super_R = 0xFFEC, scim::SCIM_KEY_Hyper_L = 0xFFED, scim::SCIM_KEY_Hyper_R = 0xFFEE, scim::SCIM_KEY_ISO_Lock = 0xFE01,
scim::SCIM_KEY_ISO_Level2_Latch = 0xFE02, scim::SCIM_KEY_ISO_Level3_Shift = 0xFE03, scim::SCIM_KEY_ISO_Level3_Latch = 0xFE04, scim::SCIM_KEY_ISO_Level3_Lock = 0xFE05,
scim::SCIM_KEY_ISO_Group_Shift = 0xFF7E, scim::SCIM_KEY_ISO_Group_Latch = 0xFE06, scim::SCIM_KEY_ISO_Group_Lock = 0xFE07, scim::SCIM_KEY_ISO_Next_Group = 0xFE08,
scim::SCIM_KEY_ISO_Next_Group_Lock = 0xFE09, scim::SCIM_KEY_ISO_Prev_Group = 0xFE0A, scim::SCIM_KEY_ISO_Prev_Group_Lock = 0xFE0B, scim::SCIM_KEY_ISO_First_Group = 0xFE0C,
scim::SCIM_KEY_ISO_First_Group_Lock = 0xFE0D, scim::SCIM_KEY_ISO_Last_Group = 0xFE0E, scim::SCIM_KEY_ISO_Last_Group_Lock = 0xFE0F, scim::SCIM_KEY_ISO_Left_Tab = 0xFE20,
scim::SCIM_KEY_ISO_Move_Line_Up = 0xFE21, scim::SCIM_KEY_ISO_Move_Line_Down = 0xFE22, scim::SCIM_KEY_ISO_Partial_Line_Up = 0xFE23, scim::SCIM_KEY_ISO_Partial_Line_Down = 0xFE24,
scim::SCIM_KEY_ISO_Partial_Space_Left = 0xFE25, scim::SCIM_KEY_ISO_Partial_Space_Right = 0xFE26, scim::SCIM_KEY_ISO_Set_Margin_Left = 0xFE27, scim::SCIM_KEY_ISO_Set_Margin_Right = 0xFE28,
scim::SCIM_KEY_ISO_Release_Margin_Left = 0xFE29, scim::SCIM_KEY_ISO_Release_Margin_Right = 0xFE2A, scim::SCIM_KEY_ISO_Release_Both_Margins = 0xFE2B, scim::SCIM_KEY_ISO_Fast_Cursor_Left = 0xFE2C,
scim::SCIM_KEY_ISO_Fast_Cursor_Right = 0xFE2D, scim::SCIM_KEY_ISO_Fast_Cursor_Up = 0xFE2E, scim::SCIM_KEY_ISO_Fast_Cursor_Down = 0xFE2F, scim::SCIM_KEY_ISO_Continuous_Underline = 0xFE30,
scim::SCIM_KEY_ISO_Discontinuous_Underline = 0xFE31, scim::SCIM_KEY_ISO_Emphasize = 0xFE32, scim::SCIM_KEY_ISO_Center_Object = 0xFE33, scim::SCIM_KEY_ISO_Enter = 0xFE34,
scim::SCIM_KEY_dead_grave = 0xFE50, scim::SCIM_KEY_dead_acute = 0xFE51, scim::SCIM_KEY_dead_circumflex = 0xFE52, scim::SCIM_KEY_dead_tilde = 0xFE53,
scim::SCIM_KEY_dead_macron = 0xFE54, scim::SCIM_KEY_dead_breve = 0xFE55, scim::SCIM_KEY_dead_abovedot = 0xFE56, scim::SCIM_KEY_dead_diaeresis = 0xFE57,
scim::SCIM_KEY_dead_abovering = 0xFE58, scim::SCIM_KEY_dead_doubleacute = 0xFE59, scim::SCIM_KEY_dead_caron = 0xFE5A, scim::SCIM_KEY_dead_cedilla = 0xFE5B,
scim::SCIM_KEY_dead_ogonek = 0xFE5C, scim::SCIM_KEY_dead_iota = 0xFE5D, scim::SCIM_KEY_dead_voiced_sound = 0xFE5E, scim::SCIM_KEY_dead_semivoiced_sound = 0xFE5F,
scim::SCIM_KEY_dead_belowdot = 0xFE60, scim::SCIM_KEY_dead_hook = 0xFE61, scim::SCIM_KEY_dead_horn = 0xFE62, scim::SCIM_KEY_First_Virtual_Screen = 0xFED0,
scim::SCIM_KEY_Prev_Virtual_Screen = 0xFED1, scim::SCIM_KEY_Next_Virtual_Screen = 0xFED2, scim::SCIM_KEY_Last_Virtual_Screen = 0xFED4, scim::SCIM_KEY_Terminate_Server = 0xFED5,
scim::SCIM_KEY_AccessX_Enable = 0xFE70, scim::SCIM_KEY_AccessX_Feedback_Enable = 0xFE71, scim::SCIM_KEY_RepeatKeys_Enable = 0xFE72, scim::SCIM_KEY_SlowKeys_Enable = 0xFE73,
scim::SCIM_KEY_BounceKeys_Enable = 0xFE74, scim::SCIM_KEY_StickyKeys_Enable = 0xFE75, scim::SCIM_KEY_MouseKeys_Enable = 0xFE76, scim::SCIM_KEY_MouseKeys_Accel_Enable = 0xFE77,
scim::SCIM_KEY_Overlay1_Enable = 0xFE78, scim::SCIM_KEY_Overlay2_Enable = 0xFE79, scim::SCIM_KEY_AudibleBell_Enable = 0xFE7A, scim::SCIM_KEY_Pointer_Left = 0xFEE0,
scim::SCIM_KEY_Pointer_Right = 0xFEE1, scim::SCIM_KEY_Pointer_Up = 0xFEE2, scim::SCIM_KEY_Pointer_Down = 0xFEE3, scim::SCIM_KEY_Pointer_UpLeft = 0xFEE4,
scim::SCIM_KEY_Pointer_UpRight = 0xFEE5, scim::SCIM_KEY_Pointer_DownLeft = 0xFEE6, scim::SCIM_KEY_Pointer_DownRight = 0xFEE7, scim::SCIM_KEY_Pointer_Button_Dflt = 0xFEE8,
scim::SCIM_KEY_Pointer_Button1 = 0xFEE9, scim::SCIM_KEY_Pointer_Button2 = 0xFEEA, scim::SCIM_KEY_Pointer_Button3 = 0xFEEB, scim::SCIM_KEY_Pointer_Button4 = 0xFEEC,
scim::SCIM_KEY_Pointer_Button5 = 0xFEED, scim::SCIM_KEY_Pointer_DblClick_Dflt = 0xFEEE, scim::SCIM_KEY_Pointer_DblClick1 = 0xFEEF, scim::SCIM_KEY_Pointer_DblClick2 = 0xFEF0,
scim::SCIM_KEY_Pointer_DblClick3 = 0xFEF1, scim::SCIM_KEY_Pointer_DblClick4 = 0xFEF2, scim::SCIM_KEY_Pointer_DblClick5 = 0xFEF3, scim::SCIM_KEY_Pointer_Drag_Dflt = 0xFEF4,
scim::SCIM_KEY_Pointer_Drag1 = 0xFEF5, scim::SCIM_KEY_Pointer_Drag2 = 0xFEF6, scim::SCIM_KEY_Pointer_Drag3 = 0xFEF7, scim::SCIM_KEY_Pointer_Drag4 = 0xFEF8,
scim::SCIM_KEY_Pointer_Drag5 = 0xFEFD, scim::SCIM_KEY_Pointer_EnableKeys = 0xFEF9, scim::SCIM_KEY_Pointer_Accelerate = 0xFEFA, scim::SCIM_KEY_Pointer_DfltBtnNext = 0xFEFB,
scim::SCIM_KEY_Pointer_DfltBtnPrev = 0xFEFC, scim::SCIM_KEY_3270_Duplicate = 0xFD01, scim::SCIM_KEY_3270_FieldMark = 0xFD02, scim::SCIM_KEY_3270_Right2 = 0xFD03,
scim::SCIM_KEY_3270_Left2 = 0xFD04, scim::SCIM_KEY_3270_BackTab = 0xFD05, scim::SCIM_KEY_3270_EraseEOF = 0xFD06, scim::SCIM_KEY_3270_EraseInput = 0xFD07,
scim::SCIM_KEY_3270_Reset = 0xFD08, scim::SCIM_KEY_3270_Quit = 0xFD09, scim::SCIM_KEY_3270_PA1 = 0xFD0A, scim::SCIM_KEY_3270_PA2 = 0xFD0B,
scim::SCIM_KEY_3270_PA3 = 0xFD0C, scim::SCIM_KEY_3270_Test = 0xFD0D, scim::SCIM_KEY_3270_Attn = 0xFD0E, scim::SCIM_KEY_3270_CursorBlink = 0xFD0F,
scim::SCIM_KEY_3270_AltCursor = 0xFD10, scim::SCIM_KEY_3270_KeyClick = 0xFD11, scim::SCIM_KEY_3270_Jump = 0xFD12, scim::SCIM_KEY_3270_Ident = 0xFD13,
scim::SCIM_KEY_3270_Rule = 0xFD14, scim::SCIM_KEY_3270_Copy = 0xFD15, scim::SCIM_KEY_3270_Play = 0xFD16, scim::SCIM_KEY_3270_Setup = 0xFD17,
scim::SCIM_KEY_3270_Record = 0xFD18, scim::SCIM_KEY_3270_ChangeScreen = 0xFD19, scim::SCIM_KEY_3270_DeleteWord = 0xFD1A, scim::SCIM_KEY_3270_ExSelect = 0xFD1B,
scim::SCIM_KEY_3270_CursorSelect = 0xFD1C, scim::SCIM_KEY_3270_PrintScreen = 0xFD1D, scim::SCIM_KEY_3270_Enter = 0xFD1E, scim::SCIM_KEY_space = 0x020,
scim::SCIM_KEY_exclam = 0x021, scim::SCIM_KEY_quotedbl = 0x022, scim::SCIM_KEY_numbersign = 0x023, scim::SCIM_KEY_dollar = 0x024,
scim::SCIM_KEY_percent = 0x025, scim::SCIM_KEY_ampersand = 0x026, scim::SCIM_KEY_apostrophe = 0x027, scim::SCIM_KEY_quoteright = 0x027,
scim::SCIM_KEY_parenleft = 0x028, scim::SCIM_KEY_parenright = 0x029, scim::SCIM_KEY_asterisk = 0x02a, scim::SCIM_KEY_plus = 0x02b,
scim::SCIM_KEY_comma = 0x02c, scim::SCIM_KEY_minus = 0x02d, scim::SCIM_KEY_period = 0x02e, scim::SCIM_KEY_slash = 0x02f,
scim::SCIM_KEY_0 = 0x030, scim::SCIM_KEY_1 = 0x031, scim::SCIM_KEY_2 = 0x032, scim::SCIM_KEY_3 = 0x033,
scim::SCIM_KEY_4 = 0x034, scim::SCIM_KEY_5 = 0x035, scim::SCIM_KEY_6 = 0x036, scim::SCIM_KEY_7 = 0x037,
scim::SCIM_KEY_8 = 0x038, scim::SCIM_KEY_9 = 0x039, scim::SCIM_KEY_colon = 0x03a, scim::SCIM_KEY_semicolon = 0x03b,
scim::SCIM_KEY_less = 0x03c, scim::SCIM_KEY_equal = 0x03d, scim::SCIM_KEY_greater = 0x03e, scim::SCIM_KEY_question = 0x03f,
scim::SCIM_KEY_at = 0x040, scim::SCIM_KEY_A = 0x041, scim::SCIM_KEY_B = 0x042, scim::SCIM_KEY_C = 0x043,
scim::SCIM_KEY_D = 0x044, scim::SCIM_KEY_E = 0x045, scim::SCIM_KEY_F = 0x046, scim::SCIM_KEY_G = 0x047,
scim::SCIM_KEY_H = 0x048, scim::SCIM_KEY_I = 0x049, scim::SCIM_KEY_J = 0x04a, scim::SCIM_KEY_K = 0x04b,
scim::SCIM_KEY_L = 0x04c, scim::SCIM_KEY_M = 0x04d, scim::SCIM_KEY_N = 0x04e, scim::SCIM_KEY_O = 0x04f,
scim::SCIM_KEY_P = 0x050, scim::SCIM_KEY_Q = 0x051, scim::SCIM_KEY_R = 0x052, scim::SCIM_KEY_S = 0x053,
scim::SCIM_KEY_T = 0x054, scim::SCIM_KEY_U = 0x055, scim::SCIM_KEY_V = 0x056, scim::SCIM_KEY_W = 0x057,
scim::SCIM_KEY_X = 0x058, scim::SCIM_KEY_Y = 0x059, scim::SCIM_KEY_Z = 0x05a, scim::SCIM_KEY_bracketleft = 0x05b,
scim::SCIM_KEY_backslash = 0x05c, scim::SCIM_KEY_bracketright = 0x05d, scim::SCIM_KEY_asciicircum = 0x05e, scim::SCIM_KEY_underscore = 0x05f,
scim::SCIM_KEY_grave = 0x060, scim::SCIM_KEY_a = 0x061, scim::SCIM_KEY_b = 0x062, scim::SCIM_KEY_c = 0x063,
scim::SCIM_KEY_d = 0x064, scim::SCIM_KEY_e = 0x065, scim::SCIM_KEY_f = 0x066, scim::SCIM_KEY_g = 0x067,
scim::SCIM_KEY_h = 0x068, scim::SCIM_KEY_i = 0x069, scim::SCIM_KEY_j = 0x06a, scim::SCIM_KEY_k = 0x06b,
scim::SCIM_KEY_l = 0x06c, scim::SCIM_KEY_m = 0x06d, scim::SCIM_KEY_n = 0x06e, scim::SCIM_KEY_o = 0x06f,
scim::SCIM_KEY_p = 0x070, scim::SCIM_KEY_q = 0x071, scim::SCIM_KEY_r = 0x072, scim::SCIM_KEY_s = 0x073,
scim::SCIM_KEY_t = 0x074, scim::SCIM_KEY_u = 0x075, scim::SCIM_KEY_v = 0x076, scim::SCIM_KEY_w = 0x077,
scim::SCIM_KEY_x = 0x078, scim::SCIM_KEY_y = 0x079, scim::SCIM_KEY_z = 0x07a, scim::SCIM_KEY_braceleft = 0x07b,
scim::SCIM_KEY_bar = 0x07c, scim::SCIM_KEY_braceright = 0x07d, scim::SCIM_KEY_asciitilde = 0x07e, scim::SCIM_KEY_nobreakspace = 0x0a0,
scim::SCIM_KEY_exclamdown = 0x0a1, scim::SCIM_KEY_cent = 0x0a2, scim::SCIM_KEY_sterling = 0x0a3, scim::SCIM_KEY_currency = 0x0a4,
scim::SCIM_KEY_yen = 0x0a5, scim::SCIM_KEY_brokenbar = 0x0a6, scim::SCIM_KEY_section = 0x0a7, scim::SCIM_KEY_diaeresis = 0x0a8,
scim::SCIM_KEY_copyright = 0x0a9, scim::SCIM_KEY_ordfeminine = 0x0aa, scim::SCIM_KEY_guillemotleft = 0x0ab, scim::SCIM_KEY_notsign = 0x0ac,
scim::SCIM_KEY_hyphen = 0x0ad, scim::SCIM_KEY_registered = 0x0ae, scim::SCIM_KEY_macron = 0x0af, scim::SCIM_KEY_degree = 0x0b0,
scim::SCIM_KEY_plusminus = 0x0b1, scim::SCIM_KEY_twosuperior = 0x0b2, scim::SCIM_KEY_threesuperior = 0x0b3, scim::SCIM_KEY_acute = 0x0b4,
scim::SCIM_KEY_mu = 0x0b5, scim::SCIM_KEY_paragraph = 0x0b6, scim::SCIM_KEY_periodcentered = 0x0b7, scim::SCIM_KEY_cedilla = 0x0b8,
scim::SCIM_KEY_onesuperior = 0x0b9, scim::SCIM_KEY_masculine = 0x0ba, scim::SCIM_KEY_guillemotright = 0x0bb, scim::SCIM_KEY_onequarter = 0x0bc,
scim::SCIM_KEY_onehalf = 0x0bd, scim::SCIM_KEY_threequarters = 0x0be, scim::SCIM_KEY_questiondown = 0x0bf, scim::SCIM_KEY_Agrave = 0x0c0,
scim::SCIM_KEY_Aacute = 0x0c1, scim::SCIM_KEY_Acircumflex = 0x0c2, scim::SCIM_KEY_Atilde = 0x0c3, scim::SCIM_KEY_Adiaeresis = 0x0c4,
scim::SCIM_KEY_Aring = 0x0c5, scim::SCIM_KEY_AE = 0x0c6, scim::SCIM_KEY_Ccedilla = 0x0c7, scim::SCIM_KEY_Egrave = 0x0c8,
scim::SCIM_KEY_Eacute = 0x0c9, scim::SCIM_KEY_Ecircumflex = 0x0ca, scim::SCIM_KEY_Ediaeresis = 0x0cb, scim::SCIM_KEY_Igrave = 0x0cc,
scim::SCIM_KEY_Iacute = 0x0cd, scim::SCIM_KEY_Icircumflex = 0x0ce, scim::SCIM_KEY_Idiaeresis = 0x0cf, scim::SCIM_KEY_ETH = 0x0d0,
scim::SCIM_KEY_Eth = 0x0d0, scim::SCIM_KEY_Ntilde = 0x0d1, scim::SCIM_KEY_Ograve = 0x0d2, scim::SCIM_KEY_Oacute = 0x0d3,
scim::SCIM_KEY_Ocircumflex = 0x0d4, scim::SCIM_KEY_Otilde = 0x0d5, scim::SCIM_KEY_Odiaeresis = 0x0d6, scim::SCIM_KEY_multiply = 0x0d7,
scim::SCIM_KEY_Ooblique = 0x0d8, scim::SCIM_KEY_Oslash = SCIM_KEY_Ooblique, scim::SCIM_KEY_Ugrave = 0x0d9, scim::SCIM_KEY_Uacute = 0x0da,
scim::SCIM_KEY_Ucircumflex = 0x0db, scim::SCIM_KEY_Udiaeresis = 0x0dc, scim::SCIM_KEY_Yacute = 0x0dd, scim::SCIM_KEY_THORN = 0x0de,
scim::SCIM_KEY_Thorn = 0x0de, scim::SCIM_KEY_ssharp = 0x0df, scim::SCIM_KEY_agrave = 0x0e0, scim::SCIM_KEY_aacute = 0x0e1,
scim::SCIM_KEY_acircumflex = 0x0e2, scim::SCIM_KEY_atilde = 0x0e3, scim::SCIM_KEY_adiaeresis = 0x0e4, scim::SCIM_KEY_aring = 0x0e5,
scim::SCIM_KEY_ae = 0x0e6, scim::SCIM_KEY_ccedilla = 0x0e7, scim::SCIM_KEY_egrave = 0x0e8, scim::SCIM_KEY_eacute = 0x0e9,
scim::SCIM_KEY_ecircumflex = 0x0ea, scim::SCIM_KEY_ediaeresis = 0x0eb, scim::SCIM_KEY_igrave = 0x0ec, scim::SCIM_KEY_iacute = 0x0ed,
scim::SCIM_KEY_icircumflex = 0x0ee, scim::SCIM_KEY_idiaeresis = 0x0ef, scim::SCIM_KEY_eth = 0x0f0, scim::SCIM_KEY_ntilde = 0x0f1,
scim::SCIM_KEY_ograve = 0x0f2, scim::SCIM_KEY_oacute = 0x0f3, scim::SCIM_KEY_ocircumflex = 0x0f4, scim::SCIM_KEY_otilde = 0x0f5,
scim::SCIM_KEY_odiaeresis = 0x0f6, scim::SCIM_KEY_division = 0x0f7, scim::SCIM_KEY_oslash = 0x0f8, scim::SCIM_KEY_ooblique = SCIM_KEY_oslash,
scim::SCIM_KEY_ugrave = 0x0f9, scim::SCIM_KEY_uacute = 0x0fa, scim::SCIM_KEY_ucircumflex = 0x0fb, scim::SCIM_KEY_udiaeresis = 0x0fc,
scim::SCIM_KEY_yacute = 0x0fd, scim::SCIM_KEY_thorn = 0x0fe, scim::SCIM_KEY_ydiaeresis = 0x0ff, scim::SCIM_KEY_Aogonek = 0x1a1,
scim::SCIM_KEY_breve = 0x1a2, scim::SCIM_KEY_Lstroke = 0x1a3, scim::SCIM_KEY_Lcaron = 0x1a5, scim::SCIM_KEY_Sacute = 0x1a6,
scim::SCIM_KEY_Scaron = 0x1a9, scim::SCIM_KEY_Scedilla = 0x1aa, scim::SCIM_KEY_Tcaron = 0x1ab, scim::SCIM_KEY_Zacute = 0x1ac,
scim::SCIM_KEY_Zcaron = 0x1ae, scim::SCIM_KEY_Zabovedot = 0x1af, scim::SCIM_KEY_aogonek = 0x1b1, scim::SCIM_KEY_ogonek = 0x1b2,
scim::SCIM_KEY_lstroke = 0x1b3, scim::SCIM_KEY_lcaron = 0x1b5, scim::SCIM_KEY_sacute = 0x1b6, scim::SCIM_KEY_caron = 0x1b7,
scim::SCIM_KEY_scaron = 0x1b9, scim::SCIM_KEY_scedilla = 0x1ba, scim::SCIM_KEY_tcaron = 0x1bb, scim::SCIM_KEY_zacute = 0x1bc,
scim::SCIM_KEY_doubleacute = 0x1bd, scim::SCIM_KEY_zcaron = 0x1be, scim::SCIM_KEY_zabovedot = 0x1bf, scim::SCIM_KEY_Racute = 0x1c0,
scim::SCIM_KEY_Abreve = 0x1c3, scim::SCIM_KEY_Lacute = 0x1c5, scim::SCIM_KEY_Cacute = 0x1c6, scim::SCIM_KEY_Ccaron = 0x1c8,
scim::SCIM_KEY_Eogonek = 0x1ca, scim::SCIM_KEY_Ecaron = 0x1cc, scim::SCIM_KEY_Dcaron = 0x1cf, scim::SCIM_KEY_Dstroke = 0x1d0,
scim::SCIM_KEY_Nacute = 0x1d1, scim::SCIM_KEY_Ncaron = 0x1d2, scim::SCIM_KEY_Odoubleacute = 0x1d5, scim::SCIM_KEY_Rcaron = 0x1d8,
scim::SCIM_KEY_Uring = 0x1d9, scim::SCIM_KEY_Udoubleacute = 0x1db, scim::SCIM_KEY_Tcedilla = 0x1de, scim::SCIM_KEY_racute = 0x1e0,
scim::SCIM_KEY_abreve = 0x1e3, scim::SCIM_KEY_lacute = 0x1e5, scim::SCIM_KEY_cacute = 0x1e6, scim::SCIM_KEY_ccaron = 0x1e8,
scim::SCIM_KEY_eogonek = 0x1ea, scim::SCIM_KEY_ecaron = 0x1ec, scim::SCIM_KEY_dcaron = 0x1ef, scim::SCIM_KEY_dstroke = 0x1f0,
scim::SCIM_KEY_nacute = 0x1f1, scim::SCIM_KEY_ncaron = 0x1f2, scim::SCIM_KEY_odoubleacute = 0x1f5, scim::SCIM_KEY_udoubleacute = 0x1fb,
scim::SCIM_KEY_rcaron = 0x1f8, scim::SCIM_KEY_uring = 0x1f9, scim::SCIM_KEY_tcedilla = 0x1fe, scim::SCIM_KEY_abovedot = 0x1ff,
scim::SCIM_KEY_Hstroke = 0x2a1, scim::SCIM_KEY_Hcircumflex = 0x2a6, scim::SCIM_KEY_Iabovedot = 0x2a9, scim::SCIM_KEY_Gbreve = 0x2ab,
scim::SCIM_KEY_Jcircumflex = 0x2ac, scim::SCIM_KEY_hstroke = 0x2b1, scim::SCIM_KEY_hcircumflex = 0x2b6, scim::SCIM_KEY_idotless = 0x2b9,
scim::SCIM_KEY_gbreve = 0x2bb, scim::SCIM_KEY_jcircumflex = 0x2bc, scim::SCIM_KEY_Cabovedot = 0x2c5, scim::SCIM_KEY_Ccircumflex = 0x2c6,
scim::SCIM_KEY_Gabovedot = 0x2d5, scim::SCIM_KEY_Gcircumflex = 0x2d8, scim::SCIM_KEY_Ubreve = 0x2dd, scim::SCIM_KEY_Scircumflex = 0x2de,
scim::SCIM_KEY_cabovedot = 0x2e5, scim::SCIM_KEY_ccircumflex = 0x2e6, scim::SCIM_KEY_gabovedot = 0x2f5, scim::SCIM_KEY_gcircumflex = 0x2f8,
scim::SCIM_KEY_ubreve = 0x2fd, scim::SCIM_KEY_scircumflex = 0x2fe, scim::SCIM_KEY_kra = 0x3a2, scim::SCIM_KEY_kappa = 0x3a2,
scim::SCIM_KEY_Rcedilla = 0x3a3, scim::SCIM_KEY_Itilde = 0x3a5, scim::SCIM_KEY_Lcedilla = 0x3a6, scim::SCIM_KEY_Emacron = 0x3aa,
scim::SCIM_KEY_Gcedilla = 0x3ab, scim::SCIM_KEY_Tslash = 0x3ac, scim::SCIM_KEY_rcedilla = 0x3b3, scim::SCIM_KEY_itilde = 0x3b5,
scim::SCIM_KEY_lcedilla = 0x3b6, scim::SCIM_KEY_emacron = 0x3ba, scim::SCIM_KEY_gcedilla = 0x3bb, scim::SCIM_KEY_tslash = 0x3bc,
scim::SCIM_KEY_ENG = 0x3bd, scim::SCIM_KEY_eng = 0x3bf, scim::SCIM_KEY_Amacron = 0x3c0, scim::SCIM_KEY_Iogonek = 0x3c7,
scim::SCIM_KEY_Eabovedot = 0x3cc, scim::SCIM_KEY_Imacron = 0x3cf, scim::SCIM_KEY_Ncedilla = 0x3d1, scim::SCIM_KEY_Omacron = 0x3d2,
scim::SCIM_KEY_Kcedilla = 0x3d3, scim::SCIM_KEY_Uogonek = 0x3d9, scim::SCIM_KEY_Utilde = 0x3dd, scim::SCIM_KEY_Umacron = 0x3de,
scim::SCIM_KEY_amacron = 0x3e0, scim::SCIM_KEY_iogonek = 0x3e7, scim::SCIM_KEY_eabovedot = 0x3ec, scim::SCIM_KEY_imacron = 0x3ef,
scim::SCIM_KEY_ncedilla = 0x3f1, scim::SCIM_KEY_omacron = 0x3f2, scim::SCIM_KEY_kcedilla = 0x3f3, scim::SCIM_KEY_uogonek = 0x3f9,
scim::SCIM_KEY_utilde = 0x3fd, scim::SCIM_KEY_umacron = 0x3fe, scim::SCIM_KEY_Babovedot = 0x12a1, scim::SCIM_KEY_babovedot = 0x12a2,
scim::SCIM_KEY_Dabovedot = 0x12a6, scim::SCIM_KEY_Wgrave = 0x12a8, scim::SCIM_KEY_Wacute = 0x12aa, scim::SCIM_KEY_dabovedot = 0x12ab,
scim::SCIM_KEY_Ygrave = 0x12ac, scim::SCIM_KEY_Fabovedot = 0x12b0, scim::SCIM_KEY_fabovedot = 0x12b1, scim::SCIM_KEY_Mabovedot = 0x12b4,
scim::SCIM_KEY_mabovedot = 0x12b5, scim::SCIM_KEY_Pabovedot = 0x12b7, scim::SCIM_KEY_wgrave = 0x12b8, scim::SCIM_KEY_pabovedot = 0x12b9,
scim::SCIM_KEY_wacute = 0x12ba, scim::SCIM_KEY_Sabovedot = 0x12bb, scim::SCIM_KEY_ygrave = 0x12bc, scim::SCIM_KEY_Wdiaeresis = 0x12bd,
scim::SCIM_KEY_wdiaeresis = 0x12be, scim::SCIM_KEY_sabovedot = 0x12bf, scim::SCIM_KEY_Wcircumflex = 0x12d0, scim::SCIM_KEY_Tabovedot = 0x12d7,
scim::SCIM_KEY_Ycircumflex = 0x12de, scim::SCIM_KEY_wcircumflex = 0x12f0, scim::SCIM_KEY_tabovedot = 0x12f7, scim::SCIM_KEY_ycircumflex = 0x12fe,
scim::SCIM_KEY_OE = 0x13bc, scim::SCIM_KEY_oe = 0x13bd, scim::SCIM_KEY_Ydiaeresis = 0x13be, scim::SCIM_KEY_overline = 0x47e,
scim::SCIM_KEY_kana_fullstop = 0x4a1, scim::SCIM_KEY_kana_openingbracket = 0x4a2, scim::SCIM_KEY_kana_closingbracket = 0x4a3, scim::SCIM_KEY_kana_comma = 0x4a4,
scim::SCIM_KEY_kana_conjunctive = 0x4a5, scim::SCIM_KEY_kana_middledot = 0x4a5, scim::SCIM_KEY_kana_WO = 0x4a6, scim::SCIM_KEY_kana_a = 0x4a7,
scim::SCIM_KEY_kana_i = 0x4a8, scim::SCIM_KEY_kana_u = 0x4a9, scim::SCIM_KEY_kana_e = 0x4aa, scim::SCIM_KEY_kana_o = 0x4ab,
scim::SCIM_KEY_kana_ya = 0x4ac, scim::SCIM_KEY_kana_yu = 0x4ad, scim::SCIM_KEY_kana_yo = 0x4ae, scim::SCIM_KEY_kana_tsu = 0x4af,
scim::SCIM_KEY_kana_tu = 0x4af, scim::SCIM_KEY_prolongedsound = 0x4b0, scim::SCIM_KEY_kana_A = 0x4b1, scim::SCIM_KEY_kana_I = 0x4b2,
scim::SCIM_KEY_kana_U = 0x4b3, scim::SCIM_KEY_kana_E = 0x4b4, scim::SCIM_KEY_kana_O = 0x4b5, scim::SCIM_KEY_kana_KA = 0x4b6,
scim::SCIM_KEY_kana_KI = 0x4b7, scim::SCIM_KEY_kana_KU = 0x4b8, scim::SCIM_KEY_kana_KE = 0x4b9, scim::SCIM_KEY_kana_KO = 0x4ba,
scim::SCIM_KEY_kana_SA = 0x4bb, scim::SCIM_KEY_kana_SHI = 0x4bc, scim::SCIM_KEY_kana_SU = 0x4bd, scim::SCIM_KEY_kana_SE = 0x4be,
scim::SCIM_KEY_kana_SO = 0x4bf, scim::SCIM_KEY_kana_TA = 0x4c0, scim::SCIM_KEY_kana_CHI = 0x4c1, scim::SCIM_KEY_kana_TI = 0x4c1,
scim::SCIM_KEY_kana_TSU = 0x4c2, scim::SCIM_KEY_kana_TU = 0x4c2, scim::SCIM_KEY_kana_TE = 0x4c3, scim::SCIM_KEY_kana_TO = 0x4c4,
scim::SCIM_KEY_kana_NA = 0x4c5, scim::SCIM_KEY_kana_NI = 0x4c6, scim::SCIM_KEY_kana_NU = 0x4c7, scim::SCIM_KEY_kana_NE = 0x4c8,
scim::SCIM_KEY_kana_NO = 0x4c9, scim::SCIM_KEY_kana_HA = 0x4ca, scim::SCIM_KEY_kana_HI = 0x4cb, scim::SCIM_KEY_kana_FU = 0x4cc,
scim::SCIM_KEY_kana_HU = 0x4cc, scim::SCIM_KEY_kana_HE = 0x4cd, scim::SCIM_KEY_kana_HO = 0x4ce, scim::SCIM_KEY_kana_MA = 0x4cf,
scim::SCIM_KEY_kana_MI = 0x4d0, scim::SCIM_KEY_kana_MU = 0x4d1, scim::SCIM_KEY_kana_ME = 0x4d2, scim::SCIM_KEY_kana_MO = 0x4d3,
scim::SCIM_KEY_kana_YA = 0x4d4, scim::SCIM_KEY_kana_YU = 0x4d5, scim::SCIM_KEY_kana_YO = 0x4d6, scim::SCIM_KEY_kana_RA = 0x4d7,
scim::SCIM_KEY_kana_RI = 0x4d8, scim::SCIM_KEY_kana_RU = 0x4d9, scim::SCIM_KEY_kana_RE = 0x4da, scim::SCIM_KEY_kana_RO = 0x4db,
scim::SCIM_KEY_kana_WA = 0x4dc, scim::SCIM_KEY_kana_N = 0x4dd, scim::SCIM_KEY_voicedsound = 0x4de, scim::SCIM_KEY_semivoicedsound = 0x4df,
scim::SCIM_KEY_kana_switch = 0xFF7E, scim::SCIM_KEY_Farsi_0 = 0x590, scim::SCIM_KEY_Farsi_1 = 0x591, scim::SCIM_KEY_Farsi_2 = 0x592,
scim::SCIM_KEY_Farsi_3 = 0x593, scim::SCIM_KEY_Farsi_4 = 0x594, scim::SCIM_KEY_Farsi_5 = 0x595, scim::SCIM_KEY_Farsi_6 = 0x596,
scim::SCIM_KEY_Farsi_7 = 0x597, scim::SCIM_KEY_Farsi_8 = 0x598, scim::SCIM_KEY_Farsi_9 = 0x599, scim::SCIM_KEY_Arabic_percent = 0x5a5,
scim::SCIM_KEY_Arabic_superscript_alef = 0x5a6, scim::SCIM_KEY_Arabic_tteh = 0x5a7, scim::SCIM_KEY_Arabic_peh = 0x5a8, scim::SCIM_KEY_Arabic_tcheh = 0x5a9,
scim::SCIM_KEY_Arabic_ddal = 0x5aa, scim::SCIM_KEY_Arabic_rreh = 0x5ab, scim::SCIM_KEY_Arabic_comma = 0x5ac, scim::SCIM_KEY_Arabic_fullstop = 0x5ae,
scim::SCIM_KEY_Arabic_0 = 0x5b0, scim::SCIM_KEY_Arabic_1 = 0x5b1, scim::SCIM_KEY_Arabic_2 = 0x5b2, scim::SCIM_KEY_Arabic_3 = 0x5b3,
scim::SCIM_KEY_Arabic_4 = 0x5b4, scim::SCIM_KEY_Arabic_5 = 0x5b5, scim::SCIM_KEY_Arabic_6 = 0x5b6, scim::SCIM_KEY_Arabic_7 = 0x5b7,
scim::SCIM_KEY_Arabic_8 = 0x5b8, scim::SCIM_KEY_Arabic_9 = 0x5b9, scim::SCIM_KEY_Arabic_semicolon = 0x5bb, scim::SCIM_KEY_Arabic_question_mark = 0x5bf,
scim::SCIM_KEY_Arabic_hamza = 0x5c1, scim::SCIM_KEY_Arabic_maddaonalef = 0x5c2, scim::SCIM_KEY_Arabic_hamzaonalef = 0x5c3, scim::SCIM_KEY_Arabic_hamzaonwaw = 0x5c4,
scim::SCIM_KEY_Arabic_hamzaunderalef = 0x5c5, scim::SCIM_KEY_Arabic_hamzaonyeh = 0x5c6, scim::SCIM_KEY_Arabic_alef = 0x5c7, scim::SCIM_KEY_Arabic_beh = 0x5c8,
scim::SCIM_KEY_Arabic_tehmarbuta = 0x5c9, scim::SCIM_KEY_Arabic_teh = 0x5ca, scim::SCIM_KEY_Arabic_theh = 0x5cb, scim::SCIM_KEY_Arabic_jeem = 0x5cc,
scim::SCIM_KEY_Arabic_hah = 0x5cd, scim::SCIM_KEY_Arabic_khah = 0x5ce, scim::SCIM_KEY_Arabic_dal = 0x5cf, scim::SCIM_KEY_Arabic_thal = 0x5d0,
scim::SCIM_KEY_Arabic_ra = 0x5d1, scim::SCIM_KEY_Arabic_zain = 0x5d2, scim::SCIM_KEY_Arabic_seen = 0x5d3, scim::SCIM_KEY_Arabic_sheen = 0x5d4,
scim::SCIM_KEY_Arabic_sad = 0x5d5, scim::SCIM_KEY_Arabic_dad = 0x5d6, scim::SCIM_KEY_Arabic_tah = 0x5d7, scim::SCIM_KEY_Arabic_zah = 0x5d8,
scim::SCIM_KEY_Arabic_ain = 0x5d9, scim::SCIM_KEY_Arabic_ghain = 0x5da, scim::SCIM_KEY_Arabic_tatweel = 0x5e0, scim::SCIM_KEY_Arabic_feh = 0x5e1,
scim::SCIM_KEY_Arabic_qaf = 0x5e2, scim::SCIM_KEY_Arabic_kaf = 0x5e3, scim::SCIM_KEY_Arabic_lam = 0x5e4, scim::SCIM_KEY_Arabic_meem = 0x5e5,
scim::SCIM_KEY_Arabic_noon = 0x5e6, scim::SCIM_KEY_Arabic_ha = 0x5e7, scim::SCIM_KEY_Arabic_heh = 0x5e7, scim::SCIM_KEY_Arabic_waw = 0x5e8,
scim::SCIM_KEY_Arabic_alefmaksura = 0x5e9, scim::SCIM_KEY_Arabic_yeh = 0x5ea, scim::SCIM_KEY_Arabic_fathatan = 0x5eb, scim::SCIM_KEY_Arabic_dammatan = 0x5ec,
scim::SCIM_KEY_Arabic_kasratan = 0x5ed, scim::SCIM_KEY_Arabic_fatha = 0x5ee, scim::SCIM_KEY_Arabic_damma = 0x5ef, scim::SCIM_KEY_Arabic_kasra = 0x5f0,
scim::SCIM_KEY_Arabic_shadda = 0x5f1, scim::SCIM_KEY_Arabic_sukun = 0x5f2, scim::SCIM_KEY_Arabic_madda_above = 0x5f3, scim::SCIM_KEY_Arabic_hamza_above = 0x5f4,
scim::SCIM_KEY_Arabic_hamza_below = 0x5f5, scim::SCIM_KEY_Arabic_jeh = 0x5f6, scim::SCIM_KEY_Arabic_veh = 0x5f7, scim::SCIM_KEY_Arabic_keheh = 0x5f8,
scim::SCIM_KEY_Arabic_gaf = 0x5f9, scim::SCIM_KEY_Arabic_noon_ghunna = 0x5fa, scim::SCIM_KEY_Arabic_heh_doachashmee = 0x5fb, scim::SCIM_KEY_Farsi_yeh = 0x5fc,
scim::SCIM_KEY_Arabic_farsi_yeh = SCIM_KEY_Farsi_yeh, scim::SCIM_KEY_Arabic_yeh_baree = 0x5fd, scim::SCIM_KEY_Arabic_heh_goal = 0x5fe, scim::SCIM_KEY_Arabic_switch = 0xFF7E,
scim::SCIM_KEY_Cyrillic_GHE_bar = 0x680, scim::SCIM_KEY_Cyrillic_ghe_bar = 0x690, scim::SCIM_KEY_Cyrillic_ZHE_descender = 0x681, scim::SCIM_KEY_Cyrillic_zhe_descender = 0x691,
scim::SCIM_KEY_Cyrillic_KA_descender = 0x682, scim::SCIM_KEY_Cyrillic_ka_descender = 0x692, scim::SCIM_KEY_Cyrillic_KA_vertstroke = 0x683, scim::SCIM_KEY_Cyrillic_ka_vertstroke = 0x693,
scim::SCIM_KEY_Cyrillic_EN_descender = 0x684, scim::SCIM_KEY_Cyrillic_en_descender = 0x694, scim::SCIM_KEY_Cyrillic_U_straight = 0x685, scim::SCIM_KEY_Cyrillic_u_straight = 0x695,
scim::SCIM_KEY_Cyrillic_U_straight_bar = 0x686, scim::SCIM_KEY_Cyrillic_u_straight_bar = 0x696, scim::SCIM_KEY_Cyrillic_HA_descender = 0x687, scim::SCIM_KEY_Cyrillic_ha_descender = 0x697,
scim::SCIM_KEY_Cyrillic_CHE_descender = 0x688, scim::SCIM_KEY_Cyrillic_che_descender = 0x698, scim::SCIM_KEY_Cyrillic_CHE_vertstroke = 0x689, scim::SCIM_KEY_Cyrillic_che_vertstroke = 0x699,
scim::SCIM_KEY_Cyrillic_SHHA = 0x68a, scim::SCIM_KEY_Cyrillic_shha = 0x69a, scim::SCIM_KEY_Cyrillic_SCHWA = 0x68c, scim::SCIM_KEY_Cyrillic_schwa = 0x69c,
scim::SCIM_KEY_Cyrillic_I_macron = 0x68d, scim::SCIM_KEY_Cyrillic_i_macron = 0x69d, scim::SCIM_KEY_Cyrillic_O_bar = 0x68e, scim::SCIM_KEY_Cyrillic_o_bar = 0x69e,
scim::SCIM_KEY_Cyrillic_U_macron = 0x68f, scim::SCIM_KEY_Cyrillic_u_macron = 0x69f, scim::SCIM_KEY_Serbian_dje = 0x6a1, scim::SCIM_KEY_Macedonia_gje = 0x6a2,
scim::SCIM_KEY_Cyrillic_io = 0x6a3, scim::SCIM_KEY_Ukrainian_ie = 0x6a4, scim::SCIM_KEY_Ukranian_je = 0x6a4, scim::SCIM_KEY_Macedonia_dse = 0x6a5,
scim::SCIM_KEY_Ukrainian_i = 0x6a6, scim::SCIM_KEY_Ukranian_i = 0x6a6, scim::SCIM_KEY_Ukrainian_yi = 0x6a7, scim::SCIM_KEY_Ukranian_yi = 0x6a7,
scim::SCIM_KEY_Cyrillic_je = 0x6a8, scim::SCIM_KEY_Serbian_je = 0x6a8, scim::SCIM_KEY_Cyrillic_lje = 0x6a9, scim::SCIM_KEY_Serbian_lje = 0x6a9,
scim::SCIM_KEY_Cyrillic_nje = 0x6aa, scim::SCIM_KEY_Serbian_nje = 0x6aa, scim::SCIM_KEY_Serbian_tshe = 0x6ab, scim::SCIM_KEY_Macedonia_kje = 0x6ac,
scim::SCIM_KEY_Ukrainian_ghe_with_upturn = 0x6ad, scim::SCIM_KEY_Byelorussian_shortu = 0x6ae, scim::SCIM_KEY_Cyrillic_dzhe = 0x6af, scim::SCIM_KEY_Serbian_dze = 0x6af,
scim::SCIM_KEY_numerosign = 0x6b0, scim::SCIM_KEY_Serbian_DJE = 0x6b1, scim::SCIM_KEY_Macedonia_GJE = 0x6b2, scim::SCIM_KEY_Cyrillic_IO = 0x6b3,
scim::SCIM_KEY_Ukrainian_IE = 0x6b4, scim::SCIM_KEY_Ukranian_JE = 0x6b4, scim::SCIM_KEY_Macedonia_DSE = 0x6b5, scim::SCIM_KEY_Ukrainian_I = 0x6b6,
scim::SCIM_KEY_Ukranian_I = 0x6b6, scim::SCIM_KEY_Ukrainian_YI = 0x6b7, scim::SCIM_KEY_Ukranian_YI = 0x6b7, scim::SCIM_KEY_Cyrillic_JE = 0x6b8,
scim::SCIM_KEY_Serbian_JE = 0x6b8, scim::SCIM_KEY_Cyrillic_LJE = 0x6b9, scim::SCIM_KEY_Serbian_LJE = 0x6b9, scim::SCIM_KEY_Cyrillic_NJE = 0x6ba,
scim::SCIM_KEY_Serbian_NJE = 0x6ba, scim::SCIM_KEY_Serbian_TSHE = 0x6bb, scim::SCIM_KEY_Macedonia_KJE = 0x6bc, scim::SCIM_KEY_Ukrainian_GHE_WITH_UPTURN = 0x6bd,
scim::SCIM_KEY_Byelorussian_SHORTU = 0x6be, scim::SCIM_KEY_Cyrillic_DZHE = 0x6bf, scim::SCIM_KEY_Serbian_DZE = 0x6bf, scim::SCIM_KEY_Cyrillic_yu = 0x6c0,
scim::SCIM_KEY_Cyrillic_a = 0x6c1, scim::SCIM_KEY_Cyrillic_be = 0x6c2, scim::SCIM_KEY_Cyrillic_tse = 0x6c3, scim::SCIM_KEY_Cyrillic_de = 0x6c4,
scim::SCIM_KEY_Cyrillic_ie = 0x6c5, scim::SCIM_KEY_Cyrillic_ef = 0x6c6, scim::SCIM_KEY_Cyrillic_ghe = 0x6c7, scim::SCIM_KEY_Cyrillic_ha = 0x6c8,
scim::SCIM_KEY_Cyrillic_i = 0x6c9, scim::SCIM_KEY_Cyrillic_shorti = 0x6ca, scim::SCIM_KEY_Cyrillic_ka = 0x6cb, scim::SCIM_KEY_Cyrillic_el = 0x6cc,
scim::SCIM_KEY_Cyrillic_em = 0x6cd, scim::SCIM_KEY_Cyrillic_en = 0x6ce, scim::SCIM_KEY_Cyrillic_o = 0x6cf, scim::SCIM_KEY_Cyrillic_pe = 0x6d0,
scim::SCIM_KEY_Cyrillic_ya = 0x6d1, scim::SCIM_KEY_Cyrillic_er = 0x6d2, scim::SCIM_KEY_Cyrillic_es = 0x6d3, scim::SCIM_KEY_Cyrillic_te = 0x6d4,
scim::SCIM_KEY_Cyrillic_u = 0x6d5, scim::SCIM_KEY_Cyrillic_zhe = 0x6d6, scim::SCIM_KEY_Cyrillic_ve = 0x6d7, scim::SCIM_KEY_Cyrillic_softsign = 0x6d8,
scim::SCIM_KEY_Cyrillic_yeru = 0x6d9, scim::SCIM_KEY_Cyrillic_ze = 0x6da, scim::SCIM_KEY_Cyrillic_sha = 0x6db, scim::SCIM_KEY_Cyrillic_e = 0x6dc,
scim::SCIM_KEY_Cyrillic_shcha = 0x6dd, scim::SCIM_KEY_Cyrillic_che = 0x6de, scim::SCIM_KEY_Cyrillic_hardsign = 0x6df, scim::SCIM_KEY_Cyrillic_YU = 0x6e0,
scim::SCIM_KEY_Cyrillic_A = 0x6e1, scim::SCIM_KEY_Cyrillic_BE = 0x6e2, scim::SCIM_KEY_Cyrillic_TSE = 0x6e3, scim::SCIM_KEY_Cyrillic_DE = 0x6e4,
scim::SCIM_KEY_Cyrillic_IE = 0x6e5, scim::SCIM_KEY_Cyrillic_EF = 0x6e6, scim::SCIM_KEY_Cyrillic_GHE = 0x6e7, scim::SCIM_KEY_Cyrillic_HA = 0x6e8,
scim::SCIM_KEY_Cyrillic_I = 0x6e9, scim::SCIM_KEY_Cyrillic_SHORTI = 0x6ea, scim::SCIM_KEY_Cyrillic_KA = 0x6eb, scim::SCIM_KEY_Cyrillic_EL = 0x6ec,
scim::SCIM_KEY_Cyrillic_EM = 0x6ed, scim::SCIM_KEY_Cyrillic_EN = 0x6ee, scim::SCIM_KEY_Cyrillic_O = 0x6ef, scim::SCIM_KEY_Cyrillic_PE = 0x6f0,
scim::SCIM_KEY_Cyrillic_YA = 0x6f1, scim::SCIM_KEY_Cyrillic_ER = 0x6f2, scim::SCIM_KEY_Cyrillic_ES = 0x6f3, scim::SCIM_KEY_Cyrillic_TE = 0x6f4,
scim::SCIM_KEY_Cyrillic_U = 0x6f5, scim::SCIM_KEY_Cyrillic_ZHE = 0x6f6, scim::SCIM_KEY_Cyrillic_VE = 0x6f7, scim::SCIM_KEY_Cyrillic_SOFTSIGN = 0x6f8,
scim::SCIM_KEY_Cyrillic_YERU = 0x6f9, scim::SCIM_KEY_Cyrillic_ZE = 0x6fa, scim::SCIM_KEY_Cyrillic_SHA = 0x6fb, scim::SCIM_KEY_Cyrillic_E = 0x6fc,
scim::SCIM_KEY_Cyrillic_SHCHA = 0x6fd, scim::SCIM_KEY_Cyrillic_CHE = 0x6fe, scim::SCIM_KEY_Cyrillic_HARDSIGN = 0x6ff, scim::SCIM_KEY_Greek_ALPHAaccent = 0x7a1,
scim::SCIM_KEY_Greek_EPSILONaccent = 0x7a2, scim::SCIM_KEY_Greek_ETAaccent = 0x7a3, scim::SCIM_KEY_Greek_IOTAaccent = 0x7a4, scim::SCIM_KEY_Greek_IOTAdieresis = 0x7a5,
scim::SCIM_KEY_Greek_IOTAdiaeresis = SCIM_KEY_Greek_IOTAdieresis, scim::SCIM_KEY_Greek_OMICRONaccent = 0x7a7, scim::SCIM_KEY_Greek_UPSILONaccent = 0x7a8, scim::SCIM_KEY_Greek_UPSILONdieresis = 0x7a9,
scim::SCIM_KEY_Greek_OMEGAaccent = 0x7ab, scim::SCIM_KEY_Greek_accentdieresis = 0x7ae, scim::SCIM_KEY_Greek_horizbar = 0x7af, scim::SCIM_KEY_Greek_alphaaccent = 0x7b1,
scim::SCIM_KEY_Greek_epsilonaccent = 0x7b2, scim::SCIM_KEY_Greek_etaaccent = 0x7b3, scim::SCIM_KEY_Greek_iotaaccent = 0x7b4, scim::SCIM_KEY_Greek_iotadieresis = 0x7b5,
scim::SCIM_KEY_Greek_iotaaccentdieresis = 0x7b6, scim::SCIM_KEY_Greek_omicronaccent = 0x7b7, scim::SCIM_KEY_Greek_upsilonaccent = 0x7b8, scim::SCIM_KEY_Greek_upsilondieresis = 0x7b9,
scim::SCIM_KEY_Greek_upsilonaccentdieresis = 0x7ba, scim::SCIM_KEY_Greek_omegaaccent = 0x7bb, scim::SCIM_KEY_Greek_ALPHA = 0x7c1, scim::SCIM_KEY_Greek_BETA = 0x7c2,
scim::SCIM_KEY_Greek_GAMMA = 0x7c3, scim::SCIM_KEY_Greek_DELTA = 0x7c4, scim::SCIM_KEY_Greek_EPSILON = 0x7c5, scim::SCIM_KEY_Greek_ZETA = 0x7c6,
scim::SCIM_KEY_Greek_ETA = 0x7c7, scim::SCIM_KEY_Greek_THETA = 0x7c8, scim::SCIM_KEY_Greek_IOTA = 0x7c9, scim::SCIM_KEY_Greek_KAPPA = 0x7ca,
scim::SCIM_KEY_Greek_LAMDA = 0x7cb, scim::SCIM_KEY_Greek_LAMBDA = 0x7cb, scim::SCIM_KEY_Greek_MU = 0x7cc, scim::SCIM_KEY_Greek_NU = 0x7cd,
scim::SCIM_KEY_Greek_XI = 0x7ce, scim::SCIM_KEY_Greek_OMICRON = 0x7cf, scim::SCIM_KEY_Greek_PI = 0x7d0, scim::SCIM_KEY_Greek_RHO = 0x7d1,
scim::SCIM_KEY_Greek_SIGMA = 0x7d2, scim::SCIM_KEY_Greek_TAU = 0x7d4, scim::SCIM_KEY_Greek_UPSILON = 0x7d5, scim::SCIM_KEY_Greek_PHI = 0x7d6,
scim::SCIM_KEY_Greek_CHI = 0x7d7, scim::SCIM_KEY_Greek_PSI = 0x7d8, scim::SCIM_KEY_Greek_OMEGA = 0x7d9, scim::SCIM_KEY_Greek_alpha = 0x7e1,
scim::SCIM_KEY_Greek_beta = 0x7e2, scim::SCIM_KEY_Greek_gamma = 0x7e3, scim::SCIM_KEY_Greek_delta = 0x7e4, scim::SCIM_KEY_Greek_epsilon = 0x7e5,
scim::SCIM_KEY_Greek_zeta = 0x7e6, scim::SCIM_KEY_Greek_eta = 0x7e7, scim::SCIM_KEY_Greek_theta = 0x7e8, scim::SCIM_KEY_Greek_iota = 0x7e9,
scim::SCIM_KEY_Greek_kappa = 0x7ea, scim::SCIM_KEY_Greek_lamda = 0x7eb, scim::SCIM_KEY_Greek_lambda = 0x7eb, scim::SCIM_KEY_Greek_mu = 0x7ec,
scim::SCIM_KEY_Greek_nu = 0x7ed, scim::SCIM_KEY_Greek_xi = 0x7ee, scim::SCIM_KEY_Greek_omicron = 0x7ef, scim::SCIM_KEY_Greek_pi = 0x7f0,
scim::SCIM_KEY_Greek_rho = 0x7f1, scim::SCIM_KEY_Greek_sigma = 0x7f2, scim::SCIM_KEY_Greek_finalsmallsigma = 0x7f3, scim::SCIM_KEY_Greek_tau = 0x7f4,
scim::SCIM_KEY_Greek_upsilon = 0x7f5, scim::SCIM_KEY_Greek_phi = 0x7f6, scim::SCIM_KEY_Greek_chi = 0x7f7, scim::SCIM_KEY_Greek_psi = 0x7f8,
scim::SCIM_KEY_Greek_omega = 0x7f9, scim::SCIM_KEY_Greek_switch = 0xFF7E, scim::SCIM_KEY_leftradical = 0x8a1, scim::SCIM_KEY_topleftradical = 0x8a2,
scim::SCIM_KEY_horizconnector = 0x8a3, scim::SCIM_KEY_topintegral = 0x8a4, scim::SCIM_KEY_botintegral = 0x8a5, scim::SCIM_KEY_vertconnector = 0x8a6,
scim::SCIM_KEY_topleftsqbracket = 0x8a7, scim::SCIM_KEY_botleftsqbracket = 0x8a8, scim::SCIM_KEY_toprightsqbracket = 0x8a9, scim::SCIM_KEY_botrightsqbracket = 0x8aa,
scim::SCIM_KEY_topleftparens = 0x8ab, scim::SCIM_KEY_botleftparens = 0x8ac, scim::SCIM_KEY_toprightparens = 0x8ad, scim::SCIM_KEY_botrightparens = 0x8ae,
scim::SCIM_KEY_leftmiddlecurlybrace = 0x8af, scim::SCIM_KEY_rightmiddlecurlybrace = 0x8b0, scim::SCIM_KEY_topleftsummation = 0x8b1, scim::SCIM_KEY_botleftsummation = 0x8b2,
scim::SCIM_KEY_topvertsummationconnector = 0x8b3, scim::SCIM_KEY_botvertsummationconnector = 0x8b4, scim::SCIM_KEY_toprightsummation = 0x8b5, scim::SCIM_KEY_botrightsummation = 0x8b6,
scim::SCIM_KEY_rightmiddlesummation = 0x8b7, scim::SCIM_KEY_lessthanequal = 0x8bc, scim::SCIM_KEY_notequal = 0x8bd, scim::SCIM_KEY_greaterthanequal = 0x8be,
scim::SCIM_KEY_integral = 0x8bf, scim::SCIM_KEY_therefore = 0x8c0, scim::SCIM_KEY_variation = 0x8c1, scim::SCIM_KEY_infinity = 0x8c2,
scim::SCIM_KEY_nabla = 0x8c5, scim::SCIM_KEY_approximate = 0x8c8, scim::SCIM_KEY_similarequal = 0x8c9, scim::SCIM_KEY_ifonlyif = 0x8cd,
scim::SCIM_KEY_implies = 0x8ce, scim::SCIM_KEY_identical = 0x8cf, scim::SCIM_KEY_radical = 0x8d6, scim::SCIM_KEY_includedin = 0x8da,
scim::SCIM_KEY_includes = 0x8db, scim::SCIM_KEY_intersection = 0x8dc, scim::SCIM_KEY_union = 0x8dd, scim::SCIM_KEY_logicaland = 0x8de,
scim::SCIM_KEY_logicalor = 0x8df, scim::SCIM_KEY_partialderivative = 0x8ef, scim::SCIM_KEY_function = 0x8f6, scim::SCIM_KEY_leftarrow = 0x8fb,
scim::SCIM_KEY_uparrow = 0x8fc, scim::SCIM_KEY_rightarrow = 0x8fd, scim::SCIM_KEY_downarrow = 0x8fe, scim::SCIM_KEY_blank = 0x9df,
scim::SCIM_KEY_soliddiamond = 0x9e0, scim::SCIM_KEY_checkerboard = 0x9e1, scim::SCIM_KEY_ht = 0x9e2, scim::SCIM_KEY_ff = 0x9e3,
scim::SCIM_KEY_cr = 0x9e4, scim::SCIM_KEY_lf = 0x9e5, scim::SCIM_KEY_nl = 0x9e8, scim::SCIM_KEY_vt = 0x9e9,
scim::SCIM_KEY_lowrightcorner = 0x9ea, scim::SCIM_KEY_uprightcorner = 0x9eb, scim::SCIM_KEY_upleftcorner = 0x9ec, scim::SCIM_KEY_lowleftcorner = 0x9ed,
scim::SCIM_KEY_crossinglines = 0x9ee, scim::SCIM_KEY_horizlinescan1 = 0x9ef, scim::SCIM_KEY_horizlinescan3 = 0x9f0, scim::SCIM_KEY_horizlinescan5 = 0x9f1,
scim::SCIM_KEY_horizlinescan7 = 0x9f2, scim::SCIM_KEY_horizlinescan9 = 0x9f3, scim::SCIM_KEY_leftt = 0x9f4, scim::SCIM_KEY_rightt = 0x9f5,
scim::SCIM_KEY_bott = 0x9f6, scim::SCIM_KEY_topt = 0x9f7, scim::SCIM_KEY_vertbar = 0x9f8, scim::SCIM_KEY_emspace = 0xaa1,
scim::SCIM_KEY_enspace = 0xaa2, scim::SCIM_KEY_em3space = 0xaa3, scim::SCIM_KEY_em4space = 0xaa4, scim::SCIM_KEY_digitspace = 0xaa5,
scim::SCIM_KEY_punctspace = 0xaa6, scim::SCIM_KEY_thinspace = 0xaa7, scim::SCIM_KEY_hairspace = 0xaa8, scim::SCIM_KEY_emdash = 0xaa9,
scim::SCIM_KEY_endash = 0xaaa, scim::SCIM_KEY_signifblank = 0xaac, scim::SCIM_KEY_ellipsis = 0xaae, scim::SCIM_KEY_doubbaselinedot = 0xaaf,
scim::SCIM_KEY_onethird = 0xab0, scim::SCIM_KEY_twothirds = 0xab1, scim::SCIM_KEY_onefifth = 0xab2, scim::SCIM_KEY_twofifths = 0xab3,
scim::SCIM_KEY_threefifths = 0xab4, scim::SCIM_KEY_fourfifths = 0xab5, scim::SCIM_KEY_onesixth = 0xab6, scim::SCIM_KEY_fivesixths = 0xab7,
scim::SCIM_KEY_careof = 0xab8, scim::SCIM_KEY_figdash = 0xabb, scim::SCIM_KEY_leftanglebracket = 0xabc, scim::SCIM_KEY_decimalpoint = 0xabd,
scim::SCIM_KEY_rightanglebracket = 0xabe, scim::SCIM_KEY_marker = 0xabf, scim::SCIM_KEY_oneeighth = 0xac3, scim::SCIM_KEY_threeeighths = 0xac4,
scim::SCIM_KEY_fiveeighths = 0xac5, scim::SCIM_KEY_seveneighths = 0xac6, scim::SCIM_KEY_trademark = 0xac9, scim::SCIM_KEY_signaturemark = 0xaca,
scim::SCIM_KEY_trademarkincircle = 0xacb, scim::SCIM_KEY_leftopentriangle = 0xacc, scim::SCIM_KEY_rightopentriangle = 0xacd, scim::SCIM_KEY_emopencircle = 0xace,
scim::SCIM_KEY_emopenrectangle = 0xacf, scim::SCIM_KEY_leftsinglequotemark = 0xad0, scim::SCIM_KEY_rightsinglequotemark = 0xad1, scim::SCIM_KEY_leftdoublequotemark = 0xad2,
scim::SCIM_KEY_rightdoublequotemark = 0xad3, scim::SCIM_KEY_prescription = 0xad4, scim::SCIM_KEY_minutes = 0xad6, scim::SCIM_KEY_seconds = 0xad7,
scim::SCIM_KEY_latincross = 0xad9, scim::SCIM_KEY_hexagram = 0xada, scim::SCIM_KEY_filledrectbullet = 0xadb, scim::SCIM_KEY_filledlefttribullet = 0xadc,
scim::SCIM_KEY_filledrighttribullet = 0xadd, scim::SCIM_KEY_emfilledcircle = 0xade, scim::SCIM_KEY_emfilledrect = 0xadf, scim::SCIM_KEY_enopencircbullet = 0xae0,
scim::SCIM_KEY_enopensquarebullet = 0xae1, scim::SCIM_KEY_openrectbullet = 0xae2, scim::SCIM_KEY_opentribulletup = 0xae3, scim::SCIM_KEY_opentribulletdown = 0xae4,
scim::SCIM_KEY_openstar = 0xae5, scim::SCIM_KEY_enfilledcircbullet = 0xae6, scim::SCIM_KEY_enfilledsqbullet = 0xae7, scim::SCIM_KEY_filledtribulletup = 0xae8,
scim::SCIM_KEY_filledtribulletdown = 0xae9, scim::SCIM_KEY_leftpointer = 0xaea, scim::SCIM_KEY_rightpointer = 0xaeb, scim::SCIM_KEY_club = 0xaec,
scim::SCIM_KEY_diamond = 0xaed, scim::SCIM_KEY_heart = 0xaee, scim::SCIM_KEY_maltesecross = 0xaf0, scim::SCIM_KEY_dagger = 0xaf1,
scim::SCIM_KEY_doubledagger = 0xaf2, scim::SCIM_KEY_checkmark = 0xaf3, scim::SCIM_KEY_ballotcross = 0xaf4, scim::SCIM_KEY_musicalsharp = 0xaf5,
scim::SCIM_KEY_musicalflat = 0xaf6, scim::SCIM_KEY_malesymbol = 0xaf7, scim::SCIM_KEY_femalesymbol = 0xaf8, scim::SCIM_KEY_telephone = 0xaf9,
scim::SCIM_KEY_telephonerecorder = 0xafa, scim::SCIM_KEY_phonographcopyright = 0xafb, scim::SCIM_KEY_caret = 0xafc, scim::SCIM_KEY_singlelowquotemark = 0xafd,
scim::SCIM_KEY_doublelowquotemark = 0xafe, scim::SCIM_KEY_cursor = 0xaff, scim::SCIM_KEY_leftcaret = 0xba3, scim::SCIM_KEY_rightcaret = 0xba6,
scim::SCIM_KEY_downcaret = 0xba8, scim::SCIM_KEY_upcaret = 0xba9, scim::SCIM_KEY_overbar = 0xbc0, scim::SCIM_KEY_downtack = 0xbc2,
scim::SCIM_KEY_upshoe = 0xbc3, scim::SCIM_KEY_downstile = 0xbc4, scim::SCIM_KEY_underbar = 0xbc6, scim::SCIM_KEY_jot = 0xbca,
scim::SCIM_KEY_quad = 0xbcc, scim::SCIM_KEY_uptack = 0xbce, scim::SCIM_KEY_circle = 0xbcf, scim::SCIM_KEY_upstile = 0xbd3,
scim::SCIM_KEY_downshoe = 0xbd6, scim::SCIM_KEY_rightshoe = 0xbd8, scim::SCIM_KEY_leftshoe = 0xbda, scim::SCIM_KEY_lefttack = 0xbdc,
scim::SCIM_KEY_righttack = 0xbfc, scim::SCIM_KEY_hebrew_doublelowline = 0xcdf, scim::SCIM_KEY_hebrew_aleph = 0xce0, scim::SCIM_KEY_hebrew_bet = 0xce1,
scim::SCIM_KEY_hebrew_beth = 0xce1, scim::SCIM_KEY_hebrew_gimel = 0xce2, scim::SCIM_KEY_hebrew_gimmel = 0xce2, scim::SCIM_KEY_hebrew_dalet = 0xce3,
scim::SCIM_KEY_hebrew_daleth = 0xce3, scim::SCIM_KEY_hebrew_he = 0xce4, scim::SCIM_KEY_hebrew_waw = 0xce5, scim::SCIM_KEY_hebrew_zain = 0xce6,
scim::SCIM_KEY_hebrew_zayin = 0xce6, scim::SCIM_KEY_hebrew_chet = 0xce7, scim::SCIM_KEY_hebrew_het = 0xce7, scim::SCIM_KEY_hebrew_tet = 0xce8,
scim::SCIM_KEY_hebrew_teth = 0xce8, scim::SCIM_KEY_hebrew_yod = 0xce9, scim::SCIM_KEY_hebrew_finalkaph = 0xcea, scim::SCIM_KEY_hebrew_kaph = 0xceb,
scim::SCIM_KEY_hebrew_lamed = 0xcec, scim::SCIM_KEY_hebrew_finalmem = 0xced, scim::SCIM_KEY_hebrew_mem = 0xcee, scim::SCIM_KEY_hebrew_finalnun = 0xcef,
scim::SCIM_KEY_hebrew_nun = 0xcf0, scim::SCIM_KEY_hebrew_samech = 0xcf1, scim::SCIM_KEY_hebrew_samekh = 0xcf1, scim::SCIM_KEY_hebrew_ayin = 0xcf2,
scim::SCIM_KEY_hebrew_finalpe = 0xcf3, scim::SCIM_KEY_hebrew_pe = 0xcf4, scim::SCIM_KEY_hebrew_finalzade = 0xcf5, scim::SCIM_KEY_hebrew_finalzadi = 0xcf5,
scim::SCIM_KEY_hebrew_zade = 0xcf6, scim::SCIM_KEY_hebrew_zadi = 0xcf6, scim::SCIM_KEY_hebrew_qoph = 0xcf7, scim::SCIM_KEY_hebrew_kuf = 0xcf7,
scim::SCIM_KEY_hebrew_resh = 0xcf8, scim::SCIM_KEY_hebrew_shin = 0xcf9, scim::SCIM_KEY_hebrew_taw = 0xcfa, scim::SCIM_KEY_hebrew_taf = 0xcfa,
scim::SCIM_KEY_Hebrew_switch = 0xFF7E, scim::SCIM_KEY_Thai_kokai = 0xda1, scim::SCIM_KEY_Thai_khokhai = 0xda2, scim::SCIM_KEY_Thai_khokhuat = 0xda3,
scim::SCIM_KEY_Thai_khokhwai = 0xda4, scim::SCIM_KEY_Thai_khokhon = 0xda5, scim::SCIM_KEY_Thai_khorakhang = 0xda6, scim::SCIM_KEY_Thai_ngongu = 0xda7,
scim::SCIM_KEY_Thai_chochan = 0xda8, scim::SCIM_KEY_Thai_choching = 0xda9, scim::SCIM_KEY_Thai_chochang = 0xdaa, scim::SCIM_KEY_Thai_soso = 0xdab,
scim::SCIM_KEY_Thai_chochoe = 0xdac, scim::SCIM_KEY_Thai_yoying = 0xdad, scim::SCIM_KEY_Thai_dochada = 0xdae, scim::SCIM_KEY_Thai_topatak = 0xdaf,
scim::SCIM_KEY_Thai_thothan = 0xdb0, scim::SCIM_KEY_Thai_thonangmontho = 0xdb1, scim::SCIM_KEY_Thai_thophuthao = 0xdb2, scim::SCIM_KEY_Thai_nonen = 0xdb3,
scim::SCIM_KEY_Thai_dodek = 0xdb4, scim::SCIM_KEY_Thai_totao = 0xdb5, scim::SCIM_KEY_Thai_thothung = 0xdb6, scim::SCIM_KEY_Thai_thothahan = 0xdb7,
scim::SCIM_KEY_Thai_thothong = 0xdb8, scim::SCIM_KEY_Thai_nonu = 0xdb9, scim::SCIM_KEY_Thai_bobaimai = 0xdba, scim::SCIM_KEY_Thai_popla = 0xdbb,
scim::SCIM_KEY_Thai_phophung = 0xdbc, scim::SCIM_KEY_Thai_fofa = 0xdbd, scim::SCIM_KEY_Thai_phophan = 0xdbe, scim::SCIM_KEY_Thai_fofan = 0xdbf,
scim::SCIM_KEY_Thai_phosamphao = 0xdc0, scim::SCIM_KEY_Thai_moma = 0xdc1, scim::SCIM_KEY_Thai_yoyak = 0xdc2, scim::SCIM_KEY_Thai_rorua = 0xdc3,
scim::SCIM_KEY_Thai_ru = 0xdc4, scim::SCIM_KEY_Thai_loling = 0xdc5, scim::SCIM_KEY_Thai_lu = 0xdc6, scim::SCIM_KEY_Thai_wowaen = 0xdc7,
scim::SCIM_KEY_Thai_sosala = 0xdc8, scim::SCIM_KEY_Thai_sorusi = 0xdc9, scim::SCIM_KEY_Thai_sosua = 0xdca, scim::SCIM_KEY_Thai_hohip = 0xdcb,
scim::SCIM_KEY_Thai_lochula = 0xdcc, scim::SCIM_KEY_Thai_oang = 0xdcd, scim::SCIM_KEY_Thai_honokhuk = 0xdce, scim::SCIM_KEY_Thai_paiyannoi = 0xdcf,
scim::SCIM_KEY_Thai_saraa = 0xdd0, scim::SCIM_KEY_Thai_maihanakat = 0xdd1, scim::SCIM_KEY_Thai_saraaa = 0xdd2, scim::SCIM_KEY_Thai_saraam = 0xdd3,
scim::SCIM_KEY_Thai_sarai = 0xdd4, scim::SCIM_KEY_Thai_saraii = 0xdd5, scim::SCIM_KEY_Thai_saraue = 0xdd6, scim::SCIM_KEY_Thai_sarauee = 0xdd7,
scim::SCIM_KEY_Thai_sarau = 0xdd8, scim::SCIM_KEY_Thai_sarauu = 0xdd9, scim::SCIM_KEY_Thai_phinthu = 0xdda, scim::SCIM_KEY_Thai_maihanakat_maitho = 0xdde,
scim::SCIM_KEY_Thai_baht = 0xddf, scim::SCIM_KEY_Thai_sarae = 0xde0, scim::SCIM_KEY_Thai_saraae = 0xde1, scim::SCIM_KEY_Thai_sarao = 0xde2,
scim::SCIM_KEY_Thai_saraaimaimuan = 0xde3, scim::SCIM_KEY_Thai_saraaimaimalai = 0xde4, scim::SCIM_KEY_Thai_lakkhangyao = 0xde5, scim::SCIM_KEY_Thai_maiyamok = 0xde6,
scim::SCIM_KEY_Thai_maitaikhu = 0xde7, scim::SCIM_KEY_Thai_maiek = 0xde8, scim::SCIM_KEY_Thai_maitho = 0xde9, scim::SCIM_KEY_Thai_maitri = 0xdea,
scim::SCIM_KEY_Thai_maichattawa = 0xdeb, scim::SCIM_KEY_Thai_thanthakhat = 0xdec, scim::SCIM_KEY_Thai_nikhahit = 0xded, scim::SCIM_KEY_Thai_leksun = 0xdf0,
scim::SCIM_KEY_Thai_leknung = 0xdf1, scim::SCIM_KEY_Thai_leksong = 0xdf2, scim::SCIM_KEY_Thai_leksam = 0xdf3, scim::SCIM_KEY_Thai_leksi = 0xdf4,
scim::SCIM_KEY_Thai_lekha = 0xdf5, scim::SCIM_KEY_Thai_lekhok = 0xdf6, scim::SCIM_KEY_Thai_lekchet = 0xdf7, scim::SCIM_KEY_Thai_lekpaet = 0xdf8,
scim::SCIM_KEY_Thai_lekkao = 0xdf9, scim::SCIM_KEY_Hangul = 0xff31, scim::SCIM_KEY_Hangul_Start = 0xff32, scim::SCIM_KEY_Hangul_End = 0xff33,
scim::SCIM_KEY_Hangul_Hanja = 0xff34, scim::SCIM_KEY_Hangul_Jamo = 0xff35, scim::SCIM_KEY_Hangul_Romaja = 0xff36, scim::SCIM_KEY_Hangul_Codeinput = 0xff37,
scim::SCIM_KEY_Hangul_Jeonja = 0xff38, scim::SCIM_KEY_Hangul_Banja = 0xff39, scim::SCIM_KEY_Hangul_PreHanja = 0xff3a, scim::SCIM_KEY_Hangul_PostHanja = 0xff3b,
scim::SCIM_KEY_Hangul_SingleCandidate = 0xff3c, scim::SCIM_KEY_Hangul_MultipleCandidate = 0xff3d, scim::SCIM_KEY_Hangul_PreviousCandidate = 0xff3e, scim::SCIM_KEY_Hangul_Special = 0xff3f,
scim::SCIM_KEY_Hangul_switch = 0xFF7E, scim::SCIM_KEY_Hangul_Kiyeog = 0xea1, scim::SCIM_KEY_Hangul_SsangKiyeog = 0xea2, scim::SCIM_KEY_Hangul_KiyeogSios = 0xea3,
scim::SCIM_KEY_Hangul_Nieun = 0xea4, scim::SCIM_KEY_Hangul_NieunJieuj = 0xea5, scim::SCIM_KEY_Hangul_NieunHieuh = 0xea6, scim::SCIM_KEY_Hangul_Dikeud = 0xea7,
scim::SCIM_KEY_Hangul_SsangDikeud = 0xea8, scim::SCIM_KEY_Hangul_Rieul = 0xea9, scim::SCIM_KEY_Hangul_RieulKiyeog = 0xeaa, scim::SCIM_KEY_Hangul_RieulMieum = 0xeab,
scim::SCIM_KEY_Hangul_RieulPieub = 0xeac, scim::SCIM_KEY_Hangul_RieulSios = 0xead, scim::SCIM_KEY_Hangul_RieulTieut = 0xeae, scim::SCIM_KEY_Hangul_RieulPhieuf = 0xeaf,
scim::SCIM_KEY_Hangul_RieulHieuh = 0xeb0, scim::SCIM_KEY_Hangul_Mieum = 0xeb1, scim::SCIM_KEY_Hangul_Pieub = 0xeb2, scim::SCIM_KEY_Hangul_SsangPieub = 0xeb3,
scim::SCIM_KEY_Hangul_PieubSios = 0xeb4, scim::SCIM_KEY_Hangul_Sios = 0xeb5, scim::SCIM_KEY_Hangul_SsangSios = 0xeb6, scim::SCIM_KEY_Hangul_Ieung = 0xeb7,
scim::SCIM_KEY_Hangul_Jieuj = 0xeb8, scim::SCIM_KEY_Hangul_SsangJieuj = 0xeb9, scim::SCIM_KEY_Hangul_Cieuc = 0xeba, scim::SCIM_KEY_Hangul_Khieuq = 0xebb,
scim::SCIM_KEY_Hangul_Tieut = 0xebc, scim::SCIM_KEY_Hangul_Phieuf = 0xebd, scim::SCIM_KEY_Hangul_Hieuh = 0xebe, scim::SCIM_KEY_Hangul_A = 0xebf,
scim::SCIM_KEY_Hangul_AE = 0xec0, scim::SCIM_KEY_Hangul_YA = 0xec1, scim::SCIM_KEY_Hangul_YAE = 0xec2, scim::SCIM_KEY_Hangul_EO = 0xec3,
scim::SCIM_KEY_Hangul_E = 0xec4, scim::SCIM_KEY_Hangul_YEO = 0xec5, scim::SCIM_KEY_Hangul_YE = 0xec6, scim::SCIM_KEY_Hangul_O = 0xec7,
scim::SCIM_KEY_Hangul_WA = 0xec8, scim::SCIM_KEY_Hangul_WAE = 0xec9, scim::SCIM_KEY_Hangul_OE = 0xeca, scim::SCIM_KEY_Hangul_YO = 0xecb,
scim::SCIM_KEY_Hangul_U = 0xecc, scim::SCIM_KEY_Hangul_WEO = 0xecd, scim::SCIM_KEY_Hangul_WE = 0xece, scim::SCIM_KEY_Hangul_WI = 0xecf,
scim::SCIM_KEY_Hangul_YU = 0xed0, scim::SCIM_KEY_Hangul_EU = 0xed1, scim::SCIM_KEY_Hangul_YI = 0xed2, scim::SCIM_KEY_Hangul_I = 0xed3,
scim::SCIM_KEY_Hangul_J_Kiyeog = 0xed4, scim::SCIM_KEY_Hangul_J_SsangKiyeog = 0xed5, scim::SCIM_KEY_Hangul_J_KiyeogSios = 0xed6, scim::SCIM_KEY_Hangul_J_Nieun = 0xed7,
scim::SCIM_KEY_Hangul_J_NieunJieuj = 0xed8, scim::SCIM_KEY_Hangul_J_NieunHieuh = 0xed9, scim::SCIM_KEY_Hangul_J_Dikeud = 0xeda, scim::SCIM_KEY_Hangul_J_Rieul = 0xedb,
scim::SCIM_KEY_Hangul_J_RieulKiyeog = 0xedc, scim::SCIM_KEY_Hangul_J_RieulMieum = 0xedd, scim::SCIM_KEY_Hangul_J_RieulPieub = 0xede, scim::SCIM_KEY_Hangul_J_RieulSios = 0xedf,
scim::SCIM_KEY_Hangul_J_RieulTieut = 0xee0, scim::SCIM_KEY_Hangul_J_RieulPhieuf = 0xee1, scim::SCIM_KEY_Hangul_J_RieulHieuh = 0xee2, scim::SCIM_KEY_Hangul_J_Mieum = 0xee3,
scim::SCIM_KEY_Hangul_J_Pieub = 0xee4, scim::SCIM_KEY_Hangul_J_PieubSios = 0xee5, scim::SCIM_KEY_Hangul_J_Sios = 0xee6, scim::SCIM_KEY_Hangul_J_SsangSios = 0xee7,
scim::SCIM_KEY_Hangul_J_Ieung = 0xee8, scim::SCIM_KEY_Hangul_J_Jieuj = 0xee9, scim::SCIM_KEY_Hangul_J_Cieuc = 0xeea, scim::SCIM_KEY_Hangul_J_Khieuq = 0xeeb,
scim::SCIM_KEY_Hangul_J_Tieut = 0xeec, scim::SCIM_KEY_Hangul_J_Phieuf = 0xeed, scim::SCIM_KEY_Hangul_J_Hieuh = 0xeee, scim::SCIM_KEY_Hangul_RieulYeorinHieuh = 0xeef,
scim::SCIM_KEY_Hangul_SunkyeongeumMieum = 0xef0, scim::SCIM_KEY_Hangul_SunkyeongeumPieub = 0xef1, scim::SCIM_KEY_Hangul_PanSios = 0xef2, scim::SCIM_KEY_Hangul_KkogjiDalrinIeung = 0xef3,
scim::SCIM_KEY_Hangul_SunkyeongeumPhieuf = 0xef4, scim::SCIM_KEY_Hangul_YeorinHieuh = 0xef5, scim::SCIM_KEY_Hangul_AraeA = 0xef6, scim::SCIM_KEY_Hangul_AraeAE = 0xef7,
scim::SCIM_KEY_Hangul_J_PanSios = 0xef8, scim::SCIM_KEY_Hangul_J_KkogjiDalrinIeung = 0xef9, scim::SCIM_KEY_Hangul_J_YeorinHieuh = 0xefa, scim::SCIM_KEY_Korean_Won = 0xeff,
scim::SCIM_KEY_Armenian_eternity = 0x14a1, scim::SCIM_KEY_Armenian_ligature_ew = 0x14a2, scim::SCIM_KEY_Armenian_full_stop = 0x14a3, scim::SCIM_KEY_Armenian_verjaket = 0x14a3,
scim::SCIM_KEY_Armenian_parenright = 0x14a4, scim::SCIM_KEY_Armenian_parenleft = 0x14a5, scim::SCIM_KEY_Armenian_guillemotright = 0x14a6, scim::SCIM_KEY_Armenian_guillemotleft = 0x14a7,
scim::SCIM_KEY_Armenian_em_dash = 0x14a8, scim::SCIM_KEY_Armenian_dot = 0x14a9, scim::SCIM_KEY_Armenian_mijaket = 0x14a9, scim::SCIM_KEY_Armenian_separation_mark = 0x14aa,
scim::SCIM_KEY_Armenian_but = 0x14aa, scim::SCIM_KEY_Armenian_comma = 0x14ab, scim::SCIM_KEY_Armenian_en_dash = 0x14ac, scim::SCIM_KEY_Armenian_hyphen = 0x14ad,
scim::SCIM_KEY_Armenian_yentamna = 0x14ad, scim::SCIM_KEY_Armenian_ellipsis = 0x14ae, scim::SCIM_KEY_Armenian_exclam = 0x14af, scim::SCIM_KEY_Armenian_amanak = 0x14af,
scim::SCIM_KEY_Armenian_accent = 0x14b0, scim::SCIM_KEY_Armenian_shesht = 0x14b0, scim::SCIM_KEY_Armenian_question = 0x14b1, scim::SCIM_KEY_Armenian_paruyk = 0x14b1,
scim::SCIM_KEY_Armenian_AYB = 0x14b2, scim::SCIM_KEY_Armenian_ayb = 0x14b3, scim::SCIM_KEY_Armenian_BEN = 0x14b4, scim::SCIM_KEY_Armenian_ben = 0x14b5,
scim::SCIM_KEY_Armenian_GIM = 0x14b6, scim::SCIM_KEY_Armenian_gim = 0x14b7, scim::SCIM_KEY_Armenian_DA = 0x14b8, scim::SCIM_KEY_Armenian_da = 0x14b9,
scim::SCIM_KEY_Armenian_YECH = 0x14ba, scim::SCIM_KEY_Armenian_yech = 0x14bb, scim::SCIM_KEY_Armenian_ZA = 0x14bc, scim::SCIM_KEY_Armenian_za = 0x14bd,
scim::SCIM_KEY_Armenian_E = 0x14be, scim::SCIM_KEY_Armenian_e = 0x14bf, scim::SCIM_KEY_Armenian_AT = 0x14c0, scim::SCIM_KEY_Armenian_at = 0x14c1,
scim::SCIM_KEY_Armenian_TO = 0x14c2, scim::SCIM_KEY_Armenian_to = 0x14c3, scim::SCIM_KEY_Armenian_ZHE = 0x14c4, scim::SCIM_KEY_Armenian_zhe = 0x14c5,
scim::SCIM_KEY_Armenian_INI = 0x14c6, scim::SCIM_KEY_Armenian_ini = 0x14c7, scim::SCIM_KEY_Armenian_LYUN = 0x14c8, scim::SCIM_KEY_Armenian_lyun = 0x14c9,
scim::SCIM_KEY_Armenian_KHE = 0x14ca, scim::SCIM_KEY_Armenian_khe = 0x14cb, scim::SCIM_KEY_Armenian_TSA = 0x14cc, scim::SCIM_KEY_Armenian_tsa = 0x14cd,
scim::SCIM_KEY_Armenian_KEN = 0x14ce, scim::SCIM_KEY_Armenian_ken = 0x14cf, scim::SCIM_KEY_Armenian_HO = 0x14d0, scim::SCIM_KEY_Armenian_ho = 0x14d1,
scim::SCIM_KEY_Armenian_DZA = 0x14d2, scim::SCIM_KEY_Armenian_dza = 0x14d3, scim::SCIM_KEY_Armenian_GHAT = 0x14d4, scim::SCIM_KEY_Armenian_ghat = 0x14d5,
scim::SCIM_KEY_Armenian_TCHE = 0x14d6, scim::SCIM_KEY_Armenian_tche = 0x14d7, scim::SCIM_KEY_Armenian_MEN = 0x14d8, scim::SCIM_KEY_Armenian_men = 0x14d9,
scim::SCIM_KEY_Armenian_HI = 0x14da, scim::SCIM_KEY_Armenian_hi = 0x14db, scim::SCIM_KEY_Armenian_NU = 0x14dc, scim::SCIM_KEY_Armenian_nu = 0x14dd,
scim::SCIM_KEY_Armenian_SHA = 0x14de, scim::SCIM_KEY_Armenian_sha = 0x14df, scim::SCIM_KEY_Armenian_VO = 0x14e0, scim::SCIM_KEY_Armenian_vo = 0x14e1,
scim::SCIM_KEY_Armenian_CHA = 0x14e2, scim::SCIM_KEY_Armenian_cha = 0x14e3, scim::SCIM_KEY_Armenian_PE = 0x14e4, scim::SCIM_KEY_Armenian_pe = 0x14e5,
scim::SCIM_KEY_Armenian_JE = 0x14e6, scim::SCIM_KEY_Armenian_je = 0x14e7, scim::SCIM_KEY_Armenian_RA = 0x14e8, scim::SCIM_KEY_Armenian_ra = 0x14e9,
scim::SCIM_KEY_Armenian_SE = 0x14ea, scim::SCIM_KEY_Armenian_se = 0x14eb, scim::SCIM_KEY_Armenian_VEV = 0x14ec, scim::SCIM_KEY_Armenian_vev = 0x14ed,
scim::SCIM_KEY_Armenian_TYUN = 0x14ee, scim::SCIM_KEY_Armenian_tyun = 0x14ef, scim::SCIM_KEY_Armenian_RE = 0x14f0, scim::SCIM_KEY_Armenian_re = 0x14f1,
scim::SCIM_KEY_Armenian_TSO = 0x14f2, scim::SCIM_KEY_Armenian_tso = 0x14f3, scim::SCIM_KEY_Armenian_VYUN = 0x14f4, scim::SCIM_KEY_Armenian_vyun = 0x14f5,
scim::SCIM_KEY_Armenian_PYUR = 0x14f6, scim::SCIM_KEY_Armenian_pyur = 0x14f7, scim::SCIM_KEY_Armenian_KE = 0x14f8, scim::SCIM_KEY_Armenian_ke = 0x14f9,
scim::SCIM_KEY_Armenian_O = 0x14fa, scim::SCIM_KEY_Armenian_o = 0x14fb, scim::SCIM_KEY_Armenian_FE = 0x14fc, scim::SCIM_KEY_Armenian_fe = 0x14fd,
scim::SCIM_KEY_Armenian_apostrophe = 0x14fe, scim::SCIM_KEY_Armenian_section_sign = 0x14ff, scim::SCIM_KEY_Georgian_an = 0x15d0, scim::SCIM_KEY_Georgian_ban = 0x15d1,
scim::SCIM_KEY_Georgian_gan = 0x15d2, scim::SCIM_KEY_Georgian_don = 0x15d3, scim::SCIM_KEY_Georgian_en = 0x15d4, scim::SCIM_KEY_Georgian_vin = 0x15d5,
scim::SCIM_KEY_Georgian_zen = 0x15d6, scim::SCIM_KEY_Georgian_tan = 0x15d7, scim::SCIM_KEY_Georgian_in = 0x15d8, scim::SCIM_KEY_Georgian_kan = 0x15d9,
scim::SCIM_KEY_Georgian_las = 0x15da, scim::SCIM_KEY_Georgian_man = 0x15db, scim::SCIM_KEY_Georgian_nar = 0x15dc, scim::SCIM_KEY_Georgian_on = 0x15dd,
scim::SCIM_KEY_Georgian_par = 0x15de, scim::SCIM_KEY_Georgian_zhar = 0x15df, scim::SCIM_KEY_Georgian_rae = 0x15e0, scim::SCIM_KEY_Georgian_san = 0x15e1,
scim::SCIM_KEY_Georgian_tar = 0x15e2, scim::SCIM_KEY_Georgian_un = 0x15e3, scim::SCIM_KEY_Georgian_phar = 0x15e4, scim::SCIM_KEY_Georgian_khar = 0x15e5,
scim::SCIM_KEY_Georgian_ghan = 0x15e6, scim::SCIM_KEY_Georgian_qar = 0x15e7, scim::SCIM_KEY_Georgian_shin = 0x15e8, scim::SCIM_KEY_Georgian_chin = 0x15e9,
scim::SCIM_KEY_Georgian_can = 0x15ea, scim::SCIM_KEY_Georgian_jil = 0x15eb, scim::SCIM_KEY_Georgian_cil = 0x15ec, scim::SCIM_KEY_Georgian_char = 0x15ed,
scim::SCIM_KEY_Georgian_xan = 0x15ee, scim::SCIM_KEY_Georgian_jhan = 0x15ef, scim::SCIM_KEY_Georgian_hae = 0x15f0, scim::SCIM_KEY_Georgian_he = 0x15f1,
scim::SCIM_KEY_Georgian_hie = 0x15f2, scim::SCIM_KEY_Georgian_we = 0x15f3, scim::SCIM_KEY_Georgian_har = 0x15f4, scim::SCIM_KEY_Georgian_hoe = 0x15f5,
scim::SCIM_KEY_Georgian_fi = 0x15f6, scim::SCIM_KEY_Ccedillaabovedot = 0x16a2, scim::SCIM_KEY_Xabovedot = 0x16a3, scim::SCIM_KEY_Qabovedot = 0x16a5,
scim::SCIM_KEY_Ibreve = 0x16a6, scim::SCIM_KEY_IE = 0x16a7, scim::SCIM_KEY_UO = 0x16a8, scim::SCIM_KEY_Zstroke = 0x16a9,
scim::SCIM_KEY_Gcaron = 0x16aa, scim::SCIM_KEY_Obarred = 0x16af, scim::SCIM_KEY_ccedillaabovedot = 0x16b2, scim::SCIM_KEY_xabovedot = 0x16b3,
scim::SCIM_KEY_Ocaron = 0x16b4, scim::SCIM_KEY_qabovedot = 0x16b5, scim::SCIM_KEY_ibreve = 0x16b6, scim::SCIM_KEY_ie = 0x16b7,
scim::SCIM_KEY_uo = 0x16b8, scim::SCIM_KEY_zstroke = 0x16b9, scim::SCIM_KEY_gcaron = 0x16ba, scim::SCIM_KEY_ocaron = 0x16bd,
scim::SCIM_KEY_obarred = 0x16bf, scim::SCIM_KEY_SCHWA = 0x16c6, scim::SCIM_KEY_schwa = 0x16f6, scim::SCIM_KEY_Lbelowdot = 0x16d1,
scim::SCIM_KEY_Lstrokebelowdot = 0x16d2, scim::SCIM_KEY_lbelowdot = 0x16e1, scim::SCIM_KEY_lstrokebelowdot = 0x16e2, scim::SCIM_KEY_Gtilde = 0x16d3,
scim::SCIM_KEY_gtilde = 0x16e3, scim::SCIM_KEY_Abelowdot = 0x1ea0, scim::SCIM_KEY_abelowdot = 0x1ea1, scim::SCIM_KEY_Ahook = 0x1ea2,
scim::SCIM_KEY_ahook = 0x1ea3, scim::SCIM_KEY_Acircumflexacute = 0x1ea4, scim::SCIM_KEY_acircumflexacute = 0x1ea5, scim::SCIM_KEY_Acircumflexgrave = 0x1ea6,
scim::SCIM_KEY_acircumflexgrave = 0x1ea7, scim::SCIM_KEY_Acircumflexhook = 0x1ea8, scim::SCIM_KEY_acircumflexhook = 0x1ea9, scim::SCIM_KEY_Acircumflextilde = 0x1eaa,
scim::SCIM_KEY_acircumflextilde = 0x1eab, scim::SCIM_KEY_Acircumflexbelowdot = 0x1eac, scim::SCIM_KEY_acircumflexbelowdot = 0x1ead, scim::SCIM_KEY_Abreveacute = 0x1eae,
scim::SCIM_KEY_abreveacute = 0x1eaf, scim::SCIM_KEY_Abrevegrave = 0x1eb0, scim::SCIM_KEY_abrevegrave = 0x1eb1, scim::SCIM_KEY_Abrevehook = 0x1eb2,
scim::SCIM_KEY_abrevehook = 0x1eb3, scim::SCIM_KEY_Abrevetilde = 0x1eb4, scim::SCIM_KEY_abrevetilde = 0x1eb5, scim::SCIM_KEY_Abrevebelowdot = 0x1eb6,
scim::SCIM_KEY_abrevebelowdot = 0x1eb7, scim::SCIM_KEY_Ebelowdot = 0x1eb8, scim::SCIM_KEY_ebelowdot = 0x1eb9, scim::SCIM_KEY_Ehook = 0x1eba,
scim::SCIM_KEY_ehook = 0x1ebb, scim::SCIM_KEY_Etilde = 0x1ebc, scim::SCIM_KEY_etilde = 0x1ebd, scim::SCIM_KEY_Ecircumflexacute = 0x1ebe,
scim::SCIM_KEY_ecircumflexacute = 0x1ebf, scim::SCIM_KEY_Ecircumflexgrave = 0x1ec0, scim::SCIM_KEY_ecircumflexgrave = 0x1ec1, scim::SCIM_KEY_Ecircumflexhook = 0x1ec2,
scim::SCIM_KEY_ecircumflexhook = 0x1ec3, scim::SCIM_KEY_Ecircumflextilde = 0x1ec4, scim::SCIM_KEY_ecircumflextilde = 0x1ec5, scim::SCIM_KEY_Ecircumflexbelowdot = 0x1ec6,
scim::SCIM_KEY_ecircumflexbelowdot = 0x1ec7, scim::SCIM_KEY_Ihook = 0x1ec8, scim::SCIM_KEY_ihook = 0x1ec9, scim::SCIM_KEY_Ibelowdot = 0x1eca,
scim::SCIM_KEY_ibelowdot = 0x1ecb, scim::SCIM_KEY_Obelowdot = 0x1ecc, scim::SCIM_KEY_obelowdot = 0x1ecd, scim::SCIM_KEY_Ohook = 0x1ece,
scim::SCIM_KEY_ohook = 0x1ecf, scim::SCIM_KEY_Ocircumflexacute = 0x1ed0, scim::SCIM_KEY_ocircumflexacute = 0x1ed1, scim::SCIM_KEY_Ocircumflexgrave = 0x1ed2,
scim::SCIM_KEY_ocircumflexgrave = 0x1ed3, scim::SCIM_KEY_Ocircumflexhook = 0x1ed4, scim::SCIM_KEY_ocircumflexhook = 0x1ed5, scim::SCIM_KEY_Ocircumflextilde = 0x1ed6,
scim::SCIM_KEY_ocircumflextilde = 0x1ed7, scim::SCIM_KEY_Ocircumflexbelowdot = 0x1ed8, scim::SCIM_KEY_ocircumflexbelowdot = 0x1ed9, scim::SCIM_KEY_Ohornacute = 0x1eda,
scim::SCIM_KEY_ohornacute = 0x1edb, scim::SCIM_KEY_Ohorngrave = 0x1edc, scim::SCIM_KEY_ohorngrave = 0x1edd, scim::SCIM_KEY_Ohornhook = 0x1ede,
scim::SCIM_KEY_ohornhook = 0x1edf, scim::SCIM_KEY_Ohorntilde = 0x1ee0, scim::SCIM_KEY_ohorntilde = 0x1ee1, scim::SCIM_KEY_Ohornbelowdot = 0x1ee2,
scim::SCIM_KEY_ohornbelowdot = 0x1ee3, scim::SCIM_KEY_Ubelowdot = 0x1ee4, scim::SCIM_KEY_ubelowdot = 0x1ee5, scim::SCIM_KEY_Uhook = 0x1ee6,
scim::SCIM_KEY_uhook = 0x1ee7, scim::SCIM_KEY_Uhornacute = 0x1ee8, scim::SCIM_KEY_uhornacute = 0x1ee9, scim::SCIM_KEY_Uhorngrave = 0x1eea,
scim::SCIM_KEY_uhorngrave = 0x1eeb, scim::SCIM_KEY_Uhornhook = 0x1eec, scim::SCIM_KEY_uhornhook = 0x1eed, scim::SCIM_KEY_Uhorntilde = 0x1eee,
scim::SCIM_KEY_uhorntilde = 0x1eef, scim::SCIM_KEY_Uhornbelowdot = 0x1ef0, scim::SCIM_KEY_uhornbelowdot = 0x1ef1, scim::SCIM_KEY_Ybelowdot = 0x1ef4,
scim::SCIM_KEY_ybelowdot = 0x1ef5, scim::SCIM_KEY_Yhook = 0x1ef6, scim::SCIM_KEY_yhook = 0x1ef7, scim::SCIM_KEY_Ytilde = 0x1ef8,
scim::SCIM_KEY_ytilde = 0x1ef9, scim::SCIM_KEY_Ohorn = 0x1efa, scim::SCIM_KEY_ohorn = 0x1efb, scim::SCIM_KEY_Uhorn = 0x1efc,
scim::SCIM_KEY_uhorn = 0x1efd, scim::SCIM_KEY_combining_tilde = 0x1e9f, scim::SCIM_KEY_combining_grave = 0x1ef2, scim::SCIM_KEY_combining_acute = 0x1ef3,
scim::SCIM_KEY_combining_hook = 0x1efe, scim::SCIM_KEY_combining_belowdot = 0x1eff, scim::SCIM_KEY_EcuSign = 0x20a0, scim::SCIM_KEY_ColonSign = 0x20a1,
scim::SCIM_KEY_CruzeiroSign = 0x20a2, scim::SCIM_KEY_FFrancSign = 0x20a3, scim::SCIM_KEY_LiraSign = 0x20a4, scim::SCIM_KEY_MillSign = 0x20a5,
scim::SCIM_KEY_NairaSign = 0x20a6, scim::SCIM_KEY_PesetaSign = 0x20a7, scim::SCIM_KEY_RupeeSign = 0x20a8, scim::SCIM_KEY_WonSign = 0x20a9,
scim::SCIM_KEY_NewSheqelSign = 0x20aa, scim::SCIM_KEY_DongSign = 0x20ab, scim::SCIM_KEY_EuroSign = 0x20ac
}
Enum values of all valid key codes.
enum scim::KeyboardLayout {
scim::SCIM_KEYBOARD_Unknown = 0, scim::SCIM_KEYBOARD_Default = 1, scim::SCIM_KEYBOARD_US = 1, scim::SCIM_KEYBOARD_Belgian = 2,
scim::SCIM_KEYBOARD_Croatian = 3, scim::SCIM_KEYBOARD_Czech = 4, scim::SCIM_KEYBOARD_Czech_Qwerty = 5, scim::SCIM_KEYBOARD_Danish = 6,
scim::SCIM_KEYBOARD_Dutch = 7, scim::SCIM_KEYBOARD_Dvorak = 8, scim::SCIM_KEYBOARD_Estonian = 9, scim::SCIM_KEYBOARD_Finnish = 10,
scim::SCIM_KEYBOARD_French = 11, scim::SCIM_KEYBOARD_French_Canadian = 12, scim::SCIM_KEYBOARD_French_Switzerland = 13, scim::SCIM_KEYBOARD_German = 14,
scim::SCIM_KEYBOARD_German_Deadkeys = 15, scim::SCIM_KEYBOARD_German_Swiss = 16, scim::SCIM_KEYBOARD_Greek = 17, scim::SCIM_KEYBOARD_Hungarian = 18,
scim::SCIM_KEYBOARD_Italian = 19, scim::SCIM_KEYBOARD_Japanese = 20, scim::SCIM_KEYBOARD_Norwegian = 21, scim::SCIM_KEYBOARD_Polish = 22,
scim::SCIM_KEYBOARD_Portuguese = 23, scim::SCIM_KEYBOARD_Portuguese_Brazil = 24, scim::SCIM_KEYBOARD_Portuguese_Brazil_US_Accents = 25, scim::SCIM_KEYBOARD_Russian = 26,
scim::SCIM_KEYBOARD_Slovak = 27, scim::SCIM_KEYBOARD_Slovak_Qwerty = 28, scim::SCIM_KEYBOARD_Slovene = 29, scim::SCIM_KEYBOARD_Spanish = 30,
scim::SCIM_KEYBOARD_Spanish_CP850 = 31, scim::SCIM_KEYBOARD_Spanish_Latin_America = 32, scim::SCIM_KEYBOARD_Swedish = 33, scim::SCIM_KEYBOARD_Turkish = 34,
scim::SCIM_KEYBOARD_UK = 35, scim::SCIM_KEYBOARD_Icelandic = 36, scim::SCIM_KEYBOARD_Lithuanian = 37, scim::SCIM_KEYBOARD_Ukrainian = 38,
scim::SCIM_KEYBOARD_NUM_LAYOUTS = 39
}
Enum values of all valid Keyboard Layout type.
enum scim::FrontEndHotkeyAction {
scim::SCIM_FRONTEND_HOTKEY_NOOP = 0, scim::SCIM_FRONTEND_HOTKEY_TRIGGER = 1, scim::SCIM_FRONTEND_HOTKEY_ON = 2, scim::SCIM_FRONTEND_HOTKEY_OFF = 3,
scim::SCIM_FRONTEND_HOTKEY_NEXT_FACTORY = 4, scim::SCIM_FRONTEND_HOTKEY_PREVIOUS_FACTORY = 5, scim::SCIM_FRONTEND_HOTKEY_SHOW_FACTORY_MENU = 6
}
FrontEnd actions which could be binded with Hotkeys.
Functions
bool scim::operator< (const Attribute &lhs, const Attribute &rhs)
bool scim::scim_key_to_string (String &str, const KeyEvent &key)
Convert a key event to a string.
bool scim::scim_string_to_key (KeyEvent &key, const String &str)
Convert a string to a KeyEvent.
bool scim::scim_key_list_to_string (String &str, const KeyEventList &keylist)
Convert a set of KeyEvents to a string.
bool scim::scim_string_to_key_list (KeyEventList &keylist, const String &str)
Covnert a string to a set of KeyEvents.
String scim::scim_keyboard_layout_to_string (KeyboardLayout layout)
Convert a Keyboard Layout enum value to its String name.
KeyboardLayout scim::scim_string_to_keyboard_layout (const String &str)
Convert a String name to the corresponding Keyboard Layout value.
String scim::scim_keyboard_layout_get_display_name (KeyboardLayout layout)
Get the display name of a Keyboard Layout enum value.
KeyboardLayout scim::scim_get_default_keyboard_layout ()
Get default Keyboard Layout setting.
void scim::scim_set_default_keyboard_layout (KeyboardLayout layout)
Change the default Keyboard Layout setting.
String scim::scim_global_config_read (const String &key, const String &defVal=String())
Read a string value from the global configuration file.
int scim::scim_global_config_read (const String &key, int defVal)
Read an int value from the global configuration file.
bool scim::scim_global_config_read (const String &key, bool defVal)
Read a bool value from the global configuration file.
double scim::scim_global_config_read (const String &key, double defVal)
Read a double value from the global configuration file.
std::vector< String > scim::scim_global_config_read (const String &key, const std::vector< String > &defVal)
Read a string list from the global configuration file.
std::vector< int > scim::scim_global_config_read (const String &key, const std::vector< int > &defVal)
Read an int list from the global configuration file.
void scim::scim_global_config_write (const String &key, const String &val)
Write a string value into the user global config.
void scim::scim_global_config_write (const String &key, int val)
Write an int value into the user global config.
void scim::scim_global_config_write (const String &key, bool val)
Write a bool value into the user global config.
void scim::scim_global_config_write (const String &key, double val)
Write a double value into the user global config.
void scim::scim_global_config_write (const String &key, const std::vector< String > &val)
Write a string list into the user global config.
void scim::scim_global_config_write (const String &key, const std::vector< int > &val)
Write an int list into the user global config.
void scim::scim_global_config_reset (const String &key)
Reset the value associated to the specified key to its default value.
bool scim::scim_global_config_flush ()
Flush the updated global config into user global config file.
int scim::scim_get_module_list (std::vector< String > &mod_list, const String &type="")
bool scim::operator< (const Property &lhs, const Property &rhs)
bool scim::operator< (const Property &lhs, const String &rhs)
bool scim::operator< (const String &lhs, const Property &rhs)
bool scim::operator== (const Property &lhs, const Property &rhs)
bool scim::operator== (const Property &lhs, const String &rhs)
bool scim::operator== (const String &lhs, const Property &rhs)
bool scim::operator!= (const Property &lhs, const Property &rhs)
bool scim::operator!= (const Property &lhs, const String &rhs)
bool scim::operator!= (const String &lhs, const Property &rhs)
int scim::utf8_mbtowc (ucs4_t *pwc, const unsigned char *src, int src_len)
Convert an utf8 char sequence to ucs4.
int scim::utf8_wctomb (unsigned char *dest, ucs4_t wc, int dest_size)
Convert an ucs4 code to utf8 char sequence.
WideString scim::utf8_mbstowcs (const String &str)
Convert an utf8 string to an ucs4 string.
WideString scim::utf8_mbstowcs (const char *str, int len=-1)
Convert an utf8 string to an ucs4 string.
String scim::utf8_wcstombs (const WideString &wstr)
Convert an ucs4 string to an utf8 string.
String scim::utf8_wcstombs (const ucs4_t *wstr, int len=-1)
Convert an ucs4 string to an utf8 string.
ucs4_t scim::utf8_read_wchar (std::istream &is)
Read a wide char from istream.
std::ostream & scim::utf8_write_wchar (std::ostream &os, ucs4_t wc)
Write a wide char to ostream.
WideString scim::utf8_read_wstring (std::istream &is, ucs4_t delim=(ucs4_t) '\n', bool rm_delim=true)
Read a wide string from istream.
std::ostream & scim::utf8_write_wstring (std::ostream &os, const WideString &wstr)
Write a wide string to ostream.
void scim::scim_uint32tobytes (unsigned char *bytes, uint32 n)
Convert an uint32 variable into a sequence of bytes.
uint32 scim::scim_bytestouint32 (const unsigned char *bytes)
Convert a sequence of bytes into an uint32 value.
void scim::scim_uint16tobytes (unsigned char *bytes, uint16 n)
Convert an uint16 variable into a sequence of bytes.
uint16 scim::scim_bytestouint16 (const unsigned char *bytes)
Convert a sequence of bytes into an uint16 value.
String scim::scim_validate_locale (const String &locale)
Test if the locale is valid, and return the good locale name.
String scim::scim_get_locale_encoding (const String &locale)
Get the encoding for a locale.
String scim::scim_get_current_locale ()
Get current system locale.
String scim::scim_get_current_language ()
Get current system language.
int scim::scim_get_locale_maxlen (const String &locale)
Get the max length of the multibyte char of a locale.
int scim::scim_split_string_list (std::vector< String > &vec, const String &str, char delim= ',')
Split string list into a string vector according to the delim char.
String scim::scim_combine_string_list (const std::vector< String > &vec, char delim= ',')
Combine a string vector into one string list, separated by char delim.
bool scim::scim_is_little_endian ()
Get machine endian type.
bool scim::scim_if_wchar_ucs4_equal ()
Test if wchar_t is using UCS4 encoding.
ucs4_t scim::scim_wchar_to_full_width (ucs4_t code)
Convert a half width unicode char to its full width counterpart.
ucs4_t scim::scim_wchar_to_half_width (ucs4_t code)
Convert a full width unicode char to its half width counterpart.
String scim::scim_get_home_dir ()
Get the home dir of current user.
String scim::scim_get_user_name ()
Get the name of current user.
String scim::scim_get_user_data_dir ()
Get SCIM data dir of current user.
size_t scim::scim_load_file (const String &filename, char **bufptr)
Load a file into memory.
bool scim::scim_make_dir (const String &dir)
Make a directory.
String scim::scim_get_language_name (const String &lang)
Get the localized name of a language id.
String scim::scim_get_language_name_english (const String &lang)
Get the English name of a language id.
String scim::scim_get_language_name_untranslated (const String &lang)
Get the untranslated name of a language id.
String scim::scim_get_language_locales (const String &lang)
Get the supported locales for a language.
String scim::scim_get_locale_language (const String &locale)
Get the language id for a locale.
String scim::scim_validate_language (const String &lang)
Test if the language is valid, and return the good language code.
String scim::scim_get_normalized_language (const String &lang)
Get the normalized language id of a language.
int scim::scim_launch (bool daemon, const String &config, const String &imengines, const String &frontend, char *const argv[]=0)
Launch a SCIM process with specific options.
int scim::scim_launch_panel (bool daemon, const String &config, const String &display, char *const argv[]=0)
Launch a SCIM Panel process with specific options.
void scim::scim_usleep (unsigned int usec)
Sleep some microseconds.
void scim::scim_daemon ()
Switch process into daemon mode.
Variables
const unsigned int scim::SCIM_ATTR_DECORATE_NONE = 0
No decorate.
const unsigned int scim::SCIM_ATTR_DECORATE_UNDERLINE = 1
Draw a line under the text.
const unsigned int scim::SCIM_ATTR_DECORATE_HIGHLIGHT = 2
Draw the text in highlighted color.
const unsigned int scim::SCIM_ATTR_DECORATE_REVERSE = 4
Draw the text in reverse color mode.
Equality operators
template<typename T1 , typename T2 >
bool scim::operator== (const Pointer< T1 > &t1, const Pointer< T2 > &t2)
template<typename T1 , typename T2 >
bool scim::operator!= (const Pointer< T1 > &t1, const Pointer< T2 > &t2)
C++-style casting functions
template<typename To , typename From >
Pointer< To > scim::cast_const (const Pointer< From > &from)
template<typename To , typename From >
Pointer< To > scim::cast_dynamic (const Pointer< From > &from)
template<typename To , typename From >
Pointer< To > scim::cast_static (const Pointer< From > &from)
Detailed Description
The accessorial classes and functions, including Attribute, IConvert, LookupTable etc.
Macro Definition Documentation
#define SCIM_RGB_COLOR (RED, GREEN, BLUE) ((unsigned int)(((RED)<<16) + ((GREEN)<<8) + (BLUE)))
#define SCIM_RGB_COLOR_RED (COLOR) ((unsigned int)((COLOR>>16) & 0x00ff))
#define SCIM_RGB_COLOR_GREEN (COLOR) ((unsigned int)((COLOR>>8) & 0x00ff))
#define SCIM_RGB_COLOR_BLUE (COLOR) ((unsigned int)((COLOR) & 0x00ff))
#define SCIM_MAX_BUFSIZE 4096
#define SCIM_LOOKUP_TABLE_MAX_PAGESIZE 16
#define SCIM_PATH_DELIM_STRING "/"
#define SCIM_PATH_DELIM '/'
#define RET_ILSEQ 0
#define RET_TOOFEW (n) (-1-(n))
#define RET_TOOSMALL -1
#define BAD_WCHAR ((ucs4_t) 0xfffd)
#define BAD_CHAR '?'
Typedef Documentation
typedef std::vector< Attribute > scim::AttributeList
The container to store a set of Attribute objects.
You should use the STL container methods to manipulate its objects.
typedef std::vector< KeyEvent > scim::KeyEventList
The container to store a set of KeyEvent objects.
You should use the STL container methods to manipulate its objects.
std::vector< Property > scim::PropertyList
The container to store a set of Properties.
You should use the STL container methods to manipulate its objects.
Enumeration Type Documentation
enum scim::AttributeType
Enum values of the valid attribute type.
Enumerator
SCIM_ATTR_NONE
No attribute.
SCIM_ATTR_DECORATE
A decorate attribute, eg. underline etc.
SCIM_ATTR_FOREGROUND
A foreground color attribute, in RGB format.
SCIM_ATTR_BACKGROUND
A background color attribute, in RGB format.
enum scim::KeyMask
Enum values of all valid key masks.
The key masks indicate which modifier keys is pressed down during the keyboard hit.
The special SCIM_KEY_ReleaseMask indicates the key release event.
Enumerator
SCIM_KEY_NullMask
Key press event without modifier key.
SCIM_KEY_ShiftMask
The Shift key is pressed down
SCIM_KEY_CapsLockMask
The CapsLock key is pressed down
SCIM_KEY_ControlMask
The Control key is pressed down
SCIM_KEY_AltMask
The Alt key is pressed down
SCIM_KEY_MetaMask
The Meta key is pressed down
SCIM_KEY_SuperMask
The Super key is pressed down
SCIM_KEY_HyperMask
The Hyper key is pressed down
SCIM_KEY_NumLockMask
The NumLock key is pressed down
SCIM_KEY_LockMask
For backward API compatibility, do not use it in new code
SCIM_KEY_Mod1Mask
For backward API compatibility, do not use it in new code
SCIM_KEY_Mod2Mask
For backward API compatibility, do not use it in new code
SCIM_KEY_Mod3Mask
For backward API compatibility, do not use it in new code
SCIM_KEY_Mod4Mask
For backward API compatibility, do not use it in new code
SCIM_KEY_Mod5Mask
For backward API compatibility, do not use it in new code
SCIM_KEY_ScrollLockMask
For backward API compatibility, do not use it in new code
SCIM_KEY_QuirkKanaRoMask
Special mask to distinguish two backslash keys on jp106 keyboard
SCIM_KEY_ReleaseMask
It's a key release event
SCIM_KEY_AllMasks
All valid Masks
enum scim::KeyCode
Enum values of all valid key codes.
If keycode & 0xff000000 == 0x01000000 then this key code is directly encoded 24-bit UCS character. The UCS value is keycode & 0x00ffffff.
Enumerator
SCIM_KEY_NullKey
SCIM_KEY_VoidSymbol
SCIM_KEY_BackSpace
SCIM_KEY_Tab
SCIM_KEY_Linefeed
SCIM_KEY_Clear
SCIM_KEY_Return
SCIM_KEY_Pause
SCIM_KEY_Scroll_Lock
SCIM_KEY_Sys_Req
SCIM_KEY_Escape
SCIM_KEY_Delete
SCIM_KEY_Multi_key
SCIM_KEY_Codeinput
SCIM_KEY_SingleCandidate
SCIM_KEY_MultipleCandidate
SCIM_KEY_PreviousCandidate
SCIM_KEY_Kanji
SCIM_KEY_Muhenkan
SCIM_KEY_Henkan_Mode
SCIM_KEY_Henkan
SCIM_KEY_Romaji
SCIM_KEY_Hiragana
SCIM_KEY_Katakana
SCIM_KEY_Hiragana_Katakana
SCIM_KEY_Zenkaku
SCIM_KEY_Hankaku
SCIM_KEY_Zenkaku_Hankaku
SCIM_KEY_Touroku
SCIM_KEY_Massyo
SCIM_KEY_Kana_Lock
SCIM_KEY_Kana_Shift
SCIM_KEY_Eisu_Shift
SCIM_KEY_Eisu_toggle
SCIM_KEY_Kanji_Bangou
SCIM_KEY_Zen_Koho
SCIM_KEY_Mae_Koho
SCIM_KEY_Home
SCIM_KEY_Left
SCIM_KEY_Up
SCIM_KEY_Right
SCIM_KEY_Down
SCIM_KEY_Prior
SCIM_KEY_Page_Up
SCIM_KEY_Next
SCIM_KEY_Page_Down
SCIM_KEY_End
SCIM_KEY_Begin
SCIM_KEY_Select
SCIM_KEY_Print
SCIM_KEY_Execute
SCIM_KEY_Insert
SCIM_KEY_Undo
SCIM_KEY_Redo
SCIM_KEY_Menu
SCIM_KEY_Find
SCIM_KEY_Cancel
SCIM_KEY_Help
SCIM_KEY_Break
SCIM_KEY_Mode_switch
SCIM_KEY_Num_Lock
SCIM_KEY_KP_Space
SCIM_KEY_KP_Tab
SCIM_KEY_KP_Enter
SCIM_KEY_KP_F1
SCIM_KEY_KP_F2
SCIM_KEY_KP_F3
SCIM_KEY_KP_F4
SCIM_KEY_KP_Home
SCIM_KEY_KP_Left
SCIM_KEY_KP_Up
SCIM_KEY_KP_Right
SCIM_KEY_KP_Down
SCIM_KEY_KP_Prior
SCIM_KEY_KP_Page_Up
SCIM_KEY_KP_Next
SCIM_KEY_KP_Page_Down
SCIM_KEY_KP_End
SCIM_KEY_KP_Begin
SCIM_KEY_KP_Insert
SCIM_KEY_KP_Delete
SCIM_KEY_KP_Equal
SCIM_KEY_KP_Multiply
SCIM_KEY_KP_Add
SCIM_KEY_KP_Separator
SCIM_KEY_KP_Subtract
SCIM_KEY_KP_Decimal
SCIM_KEY_KP_Divide
SCIM_KEY_KP_0
SCIM_KEY_KP_1
SCIM_KEY_KP_2
SCIM_KEY_KP_3
SCIM_KEY_KP_4
SCIM_KEY_KP_5
SCIM_KEY_KP_6
SCIM_KEY_KP_7
SCIM_KEY_KP_8
SCIM_KEY_KP_9
SCIM_KEY_F1
SCIM_KEY_F2
SCIM_KEY_F3
SCIM_KEY_F4
SCIM_KEY_F5
SCIM_KEY_F6
SCIM_KEY_F7
SCIM_KEY_F8
SCIM_KEY_F9
SCIM_KEY_F10
SCIM_KEY_F11
SCIM_KEY_F12
SCIM_KEY_F13
SCIM_KEY_F14
SCIM_KEY_F15
SCIM_KEY_F16
SCIM_KEY_F17
SCIM_KEY_F18
SCIM_KEY_F19
SCIM_KEY_F20
SCIM_KEY_F21
SCIM_KEY_F22
SCIM_KEY_F23
SCIM_KEY_F24
SCIM_KEY_F25
SCIM_KEY_F26
SCIM_KEY_F27
SCIM_KEY_F28
SCIM_KEY_F29
SCIM_KEY_F30
SCIM_KEY_F31
SCIM_KEY_F32
SCIM_KEY_F33
SCIM_KEY_F34
SCIM_KEY_F35
SCIM_KEY_Shift_L
SCIM_KEY_Shift_R
SCIM_KEY_Control_L
SCIM_KEY_Control_R
SCIM_KEY_Caps_Lock
SCIM_KEY_Shift_Lock
SCIM_KEY_Meta_L
SCIM_KEY_Meta_R
SCIM_KEY_Alt_L
SCIM_KEY_Alt_R
SCIM_KEY_Super_L
SCIM_KEY_Super_R
SCIM_KEY_Hyper_L
SCIM_KEY_Hyper_R
SCIM_KEY_ISO_Lock
SCIM_KEY_ISO_Level2_Latch
SCIM_KEY_ISO_Level3_Shift
SCIM_KEY_ISO_Level3_Latch
SCIM_KEY_ISO_Level3_Lock
SCIM_KEY_ISO_Group_Shift
SCIM_KEY_ISO_Group_Latch
SCIM_KEY_ISO_Group_Lock
SCIM_KEY_ISO_Next_Group
SCIM_KEY_ISO_Next_Group_Lock
SCIM_KEY_ISO_Prev_Group
SCIM_KEY_ISO_Prev_Group_Lock
SCIM_KEY_ISO_First_Group
SCIM_KEY_ISO_First_Group_Lock
SCIM_KEY_ISO_Last_Group
SCIM_KEY_ISO_Last_Group_Lock
SCIM_KEY_ISO_Left_Tab
SCIM_KEY_ISO_Move_Line_Up
SCIM_KEY_ISO_Move_Line_Down
SCIM_KEY_ISO_Partial_Line_Up
SCIM_KEY_ISO_Partial_Line_Down
SCIM_KEY_ISO_Partial_Space_Left
SCIM_KEY_ISO_Partial_Space_Right
SCIM_KEY_ISO_Set_Margin_Left
SCIM_KEY_ISO_Set_Margin_Right
SCIM_KEY_ISO_Release_Margin_Left
SCIM_KEY_ISO_Release_Margin_Right
SCIM_KEY_ISO_Release_Both_Margins
SCIM_KEY_ISO_Fast_Cursor_Left
SCIM_KEY_ISO_Fast_Cursor_Right
SCIM_KEY_ISO_Fast_Cursor_Up
SCIM_KEY_ISO_Fast_Cursor_Down
SCIM_KEY_ISO_Continuous_Underline
SCIM_KEY_ISO_Discontinuous_Underline
SCIM_KEY_ISO_Emphasize
SCIM_KEY_ISO_Center_Object
SCIM_KEY_ISO_Enter
SCIM_KEY_dead_grave
SCIM_KEY_dead_acute
SCIM_KEY_dead_circumflex
SCIM_KEY_dead_tilde
SCIM_KEY_dead_macron
SCIM_KEY_dead_breve
SCIM_KEY_dead_abovedot
SCIM_KEY_dead_diaeresis
SCIM_KEY_dead_abovering
SCIM_KEY_dead_doubleacute
SCIM_KEY_dead_caron
SCIM_KEY_dead_cedilla
SCIM_KEY_dead_ogonek
SCIM_KEY_dead_iota
SCIM_KEY_dead_voiced_sound
SCIM_KEY_dead_semivoiced_sound
SCIM_KEY_dead_belowdot
SCIM_KEY_dead_hook
SCIM_KEY_dead_horn
SCIM_KEY_First_Virtual_Screen
SCIM_KEY_Prev_Virtual_Screen
SCIM_KEY_Next_Virtual_Screen
SCIM_KEY_Last_Virtual_Screen
SCIM_KEY_Terminate_Server
SCIM_KEY_AccessX_Enable
SCIM_KEY_AccessX_Feedback_Enable
SCIM_KEY_RepeatKeys_Enable
SCIM_KEY_SlowKeys_Enable
SCIM_KEY_BounceKeys_Enable
SCIM_KEY_StickyKeys_Enable
SCIM_KEY_MouseKeys_Enable
SCIM_KEY_MouseKeys_Accel_Enable
SCIM_KEY_Overlay1_Enable
SCIM_KEY_Overlay2_Enable
SCIM_KEY_AudibleBell_Enable
SCIM_KEY_Pointer_Left
SCIM_KEY_Pointer_Right
SCIM_KEY_Pointer_Up
SCIM_KEY_Pointer_Down
SCIM_KEY_Pointer_UpLeft
SCIM_KEY_Pointer_UpRight
SCIM_KEY_Pointer_DownLeft
SCIM_KEY_Pointer_DownRight
SCIM_KEY_Pointer_Button_Dflt
SCIM_KEY_Pointer_Button1
SCIM_KEY_Pointer_Button2
SCIM_KEY_Pointer_Button3
SCIM_KEY_Pointer_Button4
SCIM_KEY_Pointer_Button5
SCIM_KEY_Pointer_DblClick_Dflt
SCIM_KEY_Pointer_DblClick1
SCIM_KEY_Pointer_DblClick2
SCIM_KEY_Pointer_DblClick3
SCIM_KEY_Pointer_DblClick4
SCIM_KEY_Pointer_DblClick5
SCIM_KEY_Pointer_Drag_Dflt
SCIM_KEY_Pointer_Drag1
SCIM_KEY_Pointer_Drag2
SCIM_KEY_Pointer_Drag3
SCIM_KEY_Pointer_Drag4
SCIM_KEY_Pointer_Drag5
SCIM_KEY_Pointer_EnableKeys
SCIM_KEY_Pointer_Accelerate
SCIM_KEY_Pointer_DfltBtnNext
SCIM_KEY_Pointer_DfltBtnPrev
SCIM_KEY_3270_Duplicate
SCIM_KEY_3270_FieldMark
SCIM_KEY_3270_Right2
SCIM_KEY_3270_Left2
SCIM_KEY_3270_BackTab
SCIM_KEY_3270_EraseEOF
SCIM_KEY_3270_EraseInput
SCIM_KEY_3270_Reset
SCIM_KEY_3270_Quit
SCIM_KEY_3270_PA1
SCIM_KEY_3270_PA2
SCIM_KEY_3270_PA3
SCIM_KEY_3270_Test
SCIM_KEY_3270_Attn
SCIM_KEY_3270_CursorBlink
SCIM_KEY_3270_AltCursor
SCIM_KEY_3270_KeyClick
SCIM_KEY_3270_Jump
SCIM_KEY_3270_Ident
SCIM_KEY_3270_Rule
SCIM_KEY_3270_Copy
SCIM_KEY_3270_Play
SCIM_KEY_3270_Setup
SCIM_KEY_3270_Record
SCIM_KEY_3270_ChangeScreen
SCIM_KEY_3270_DeleteWord
SCIM_KEY_3270_ExSelect
SCIM_KEY_3270_CursorSelect
SCIM_KEY_3270_PrintScreen
SCIM_KEY_3270_Enter
SCIM_KEY_space
SCIM_KEY_exclam
SCIM_KEY_quotedbl
SCIM_KEY_numbersign
SCIM_KEY_dollar
SCIM_KEY_percent
SCIM_KEY_ampersand
SCIM_KEY_apostrophe
SCIM_KEY_quoteright
SCIM_KEY_parenleft
SCIM_KEY_parenright
SCIM_KEY_asterisk
SCIM_KEY_plus
SCIM_KEY_comma
SCIM_KEY_minus
SCIM_KEY_period
SCIM_KEY_slash
SCIM_KEY_0
SCIM_KEY_1
SCIM_KEY_2
SCIM_KEY_3
SCIM_KEY_4
SCIM_KEY_5
SCIM_KEY_6
SCIM_KEY_7
SCIM_KEY_8
SCIM_KEY_9
SCIM_KEY_colon
SCIM_KEY_semicolon
SCIM_KEY_less
SCIM_KEY_equal
SCIM_KEY_greater
SCIM_KEY_question
SCIM_KEY_at
SCIM_KEY_A
SCIM_KEY_B
SCIM_KEY_C
SCIM_KEY_D
SCIM_KEY_E
SCIM_KEY_F
SCIM_KEY_G
SCIM_KEY_H
SCIM_KEY_I
SCIM_KEY_J
SCIM_KEY_K
SCIM_KEY_L
SCIM_KEY_M
SCIM_KEY_N
SCIM_KEY_O
SCIM_KEY_P
SCIM_KEY_Q
SCIM_KEY_R
SCIM_KEY_S
SCIM_KEY_T
SCIM_KEY_U
SCIM_KEY_V
SCIM_KEY_W
SCIM_KEY_X
SCIM_KEY_Y
SCIM_KEY_Z
SCIM_KEY_bracketleft
SCIM_KEY_backslash
SCIM_KEY_bracketright
SCIM_KEY_asciicircum
SCIM_KEY_underscore
SCIM_KEY_grave
SCIM_KEY_a
SCIM_KEY_b
SCIM_KEY_c
SCIM_KEY_d
SCIM_KEY_e
SCIM_KEY_f
SCIM_KEY_g
SCIM_KEY_h
SCIM_KEY_i
SCIM_KEY_j
SCIM_KEY_k
SCIM_KEY_l
SCIM_KEY_m
SCIM_KEY_n
SCIM_KEY_o
SCIM_KEY_p
SCIM_KEY_q
SCIM_KEY_r
SCIM_KEY_s
SCIM_KEY_t
SCIM_KEY_u
SCIM_KEY_v
SCIM_KEY_w
SCIM_KEY_x
SCIM_KEY_y
SCIM_KEY_z
SCIM_KEY_braceleft
SCIM_KEY_bar
SCIM_KEY_braceright
SCIM_KEY_asciitilde
SCIM_KEY_nobreakspace
SCIM_KEY_exclamdown
SCIM_KEY_cent
SCIM_KEY_sterling
SCIM_KEY_currency
SCIM_KEY_yen
SCIM_KEY_brokenbar
SCIM_KEY_section
SCIM_KEY_diaeresis
SCIM_KEY_copyright
SCIM_KEY_ordfeminine
SCIM_KEY_guillemotleft
SCIM_KEY_notsign
SCIM_KEY_hyphen
SCIM_KEY_registered
SCIM_KEY_macron
SCIM_KEY_degree
SCIM_KEY_plusminus
SCIM_KEY_twosuperior
SCIM_KEY_threesuperior
SCIM_KEY_acute
SCIM_KEY_mu
SCIM_KEY_paragraph
SCIM_KEY_periodcentered
SCIM_KEY_cedilla
SCIM_KEY_onesuperior
SCIM_KEY_masculine
SCIM_KEY_guillemotright
SCIM_KEY_onequarter
SCIM_KEY_onehalf
SCIM_KEY_threequarters
SCIM_KEY_questiondown
SCIM_KEY_Agrave
SCIM_KEY_Aacute
SCIM_KEY_Acircumflex
SCIM_KEY_Atilde
SCIM_KEY_Adiaeresis
SCIM_KEY_Aring
SCIM_KEY_AE
SCIM_KEY_Ccedilla
SCIM_KEY_Egrave
SCIM_KEY_Eacute
SCIM_KEY_Ecircumflex
SCIM_KEY_Ediaeresis
SCIM_KEY_Igrave
SCIM_KEY_Iacute
SCIM_KEY_Icircumflex
SCIM_KEY_Idiaeresis
SCIM_KEY_ETH
SCIM_KEY_Eth
SCIM_KEY_Ntilde
SCIM_KEY_Ograve
SCIM_KEY_Oacute
SCIM_KEY_Ocircumflex
SCIM_KEY_Otilde
SCIM_KEY_Odiaeresis
SCIM_KEY_multiply
SCIM_KEY_Ooblique
SCIM_KEY_Oslash
SCIM_KEY_Ugrave
SCIM_KEY_Uacute
SCIM_KEY_Ucircumflex
SCIM_KEY_Udiaeresis
SCIM_KEY_Yacute
SCIM_KEY_THORN
SCIM_KEY_Thorn
SCIM_KEY_ssharp
SCIM_KEY_agrave
SCIM_KEY_aacute
SCIM_KEY_acircumflex
SCIM_KEY_atilde
SCIM_KEY_adiaeresis
SCIM_KEY_aring
SCIM_KEY_ae
SCIM_KEY_ccedilla
SCIM_KEY_egrave
SCIM_KEY_eacute
SCIM_KEY_ecircumflex
SCIM_KEY_ediaeresis
SCIM_KEY_igrave
SCIM_KEY_iacute
SCIM_KEY_icircumflex
SCIM_KEY_idiaeresis
SCIM_KEY_eth
SCIM_KEY_ntilde
SCIM_KEY_ograve
SCIM_KEY_oacute
SCIM_KEY_ocircumflex
SCIM_KEY_otilde
SCIM_KEY_odiaeresis
SCIM_KEY_division
SCIM_KEY_oslash
SCIM_KEY_ooblique
SCIM_KEY_ugrave
SCIM_KEY_uacute
SCIM_KEY_ucircumflex
SCIM_KEY_udiaeresis
SCIM_KEY_yacute
SCIM_KEY_thorn
SCIM_KEY_ydiaeresis
SCIM_KEY_Aogonek
SCIM_KEY_breve
SCIM_KEY_Lstroke
SCIM_KEY_Lcaron
SCIM_KEY_Sacute
SCIM_KEY_Scaron
SCIM_KEY_Scedilla
SCIM_KEY_Tcaron
SCIM_KEY_Zacute
SCIM_KEY_Zcaron
SCIM_KEY_Zabovedot
SCIM_KEY_aogonek
SCIM_KEY_ogonek
SCIM_KEY_lstroke
SCIM_KEY_lcaron
SCIM_KEY_sacute
SCIM_KEY_caron
SCIM_KEY_scaron
SCIM_KEY_scedilla
SCIM_KEY_tcaron
SCIM_KEY_zacute
SCIM_KEY_doubleacute
SCIM_KEY_zcaron
SCIM_KEY_zabovedot
SCIM_KEY_Racute
SCIM_KEY_Abreve
SCIM_KEY_Lacute
SCIM_KEY_Cacute
SCIM_KEY_Ccaron
SCIM_KEY_Eogonek
SCIM_KEY_Ecaron
SCIM_KEY_Dcaron
SCIM_KEY_Dstroke
SCIM_KEY_Nacute
SCIM_KEY_Ncaron
SCIM_KEY_Odoubleacute
SCIM_KEY_Rcaron
SCIM_KEY_Uring
SCIM_KEY_Udoubleacute
SCIM_KEY_Tcedilla
SCIM_KEY_racute
SCIM_KEY_abreve
SCIM_KEY_lacute
SCIM_KEY_cacute
SCIM_KEY_ccaron
SCIM_KEY_eogonek
SCIM_KEY_ecaron
SCIM_KEY_dcaron
SCIM_KEY_dstroke
SCIM_KEY_nacute
SCIM_KEY_ncaron
SCIM_KEY_odoubleacute
SCIM_KEY_udoubleacute
SCIM_KEY_rcaron
SCIM_KEY_uring
SCIM_KEY_tcedilla
SCIM_KEY_abovedot
SCIM_KEY_Hstroke
SCIM_KEY_Hcircumflex
SCIM_KEY_Iabovedot
SCIM_KEY_Gbreve
SCIM_KEY_Jcircumflex
SCIM_KEY_hstroke
SCIM_KEY_hcircumflex
SCIM_KEY_idotless
SCIM_KEY_gbreve
SCIM_KEY_jcircumflex
SCIM_KEY_Cabovedot
SCIM_KEY_Ccircumflex
SCIM_KEY_Gabovedot
SCIM_KEY_Gcircumflex
SCIM_KEY_Ubreve
SCIM_KEY_Scircumflex
SCIM_KEY_cabovedot
SCIM_KEY_ccircumflex
SCIM_KEY_gabovedot
SCIM_KEY_gcircumflex
SCIM_KEY_ubreve
SCIM_KEY_scircumflex
SCIM_KEY_kra
SCIM_KEY_kappa
SCIM_KEY_Rcedilla
SCIM_KEY_Itilde
SCIM_KEY_Lcedilla
SCIM_KEY_Emacron
SCIM_KEY_Gcedilla
SCIM_KEY_Tslash
SCIM_KEY_rcedilla
SCIM_KEY_itilde
SCIM_KEY_lcedilla
SCIM_KEY_emacron
SCIM_KEY_gcedilla
SCIM_KEY_tslash
SCIM_KEY_ENG
SCIM_KEY_eng
SCIM_KEY_Amacron
SCIM_KEY_Iogonek
SCIM_KEY_Eabovedot
SCIM_KEY_Imacron
SCIM_KEY_Ncedilla
SCIM_KEY_Omacron
SCIM_KEY_Kcedilla
SCIM_KEY_Uogonek
SCIM_KEY_Utilde
SCIM_KEY_Umacron
SCIM_KEY_amacron
SCIM_KEY_iogonek
SCIM_KEY_eabovedot
SCIM_KEY_imacron
SCIM_KEY_ncedilla
SCIM_KEY_omacron
SCIM_KEY_kcedilla
SCIM_KEY_uogonek
SCIM_KEY_utilde
SCIM_KEY_umacron
SCIM_KEY_Babovedot
SCIM_KEY_babovedot
SCIM_KEY_Dabovedot
SCIM_KEY_Wgrave
SCIM_KEY_Wacute
SCIM_KEY_dabovedot
SCIM_KEY_Ygrave
SCIM_KEY_Fabovedot
SCIM_KEY_fabovedot
SCIM_KEY_Mabovedot
SCIM_KEY_mabovedot
SCIM_KEY_Pabovedot
SCIM_KEY_wgrave
SCIM_KEY_pabovedot
SCIM_KEY_wacute
SCIM_KEY_Sabovedot
SCIM_KEY_ygrave
SCIM_KEY_Wdiaeresis
SCIM_KEY_wdiaeresis
SCIM_KEY_sabovedot
SCIM_KEY_Wcircumflex
SCIM_KEY_Tabovedot
SCIM_KEY_Ycircumflex
SCIM_KEY_wcircumflex
SCIM_KEY_tabovedot
SCIM_KEY_ycircumflex
SCIM_KEY_OE
SCIM_KEY_oe
SCIM_KEY_Ydiaeresis
SCIM_KEY_overline
SCIM_KEY_kana_fullstop
SCIM_KEY_kana_openingbracket
SCIM_KEY_kana_closingbracket
SCIM_KEY_kana_comma
SCIM_KEY_kana_conjunctive
SCIM_KEY_kana_middledot
SCIM_KEY_kana_WO
SCIM_KEY_kana_a
SCIM_KEY_kana_i
SCIM_KEY_kana_u
SCIM_KEY_kana_e
SCIM_KEY_kana_o
SCIM_KEY_kana_ya
SCIM_KEY_kana_yu
SCIM_KEY_kana_yo
SCIM_KEY_kana_tsu
SCIM_KEY_kana_tu
SCIM_KEY_prolongedsound
SCIM_KEY_kana_A
SCIM_KEY_kana_I
SCIM_KEY_kana_U
SCIM_KEY_kana_E
SCIM_KEY_kana_O
SCIM_KEY_kana_KA
SCIM_KEY_kana_KI
SCIM_KEY_kana_KU
SCIM_KEY_kana_KE
SCIM_KEY_kana_KO
SCIM_KEY_kana_SA
SCIM_KEY_kana_SHI
SCIM_KEY_kana_SU
SCIM_KEY_kana_SE
SCIM_KEY_kana_SO
SCIM_KEY_kana_TA
SCIM_KEY_kana_CHI
SCIM_KEY_kana_TI
SCIM_KEY_kana_TSU
SCIM_KEY_kana_TU
SCIM_KEY_kana_TE
SCIM_KEY_kana_TO
SCIM_KEY_kana_NA
SCIM_KEY_kana_NI
SCIM_KEY_kana_NU
SCIM_KEY_kana_NE
SCIM_KEY_kana_NO
SCIM_KEY_kana_HA
SCIM_KEY_kana_HI
SCIM_KEY_kana_FU
SCIM_KEY_kana_HU
SCIM_KEY_kana_HE
SCIM_KEY_kana_HO
SCIM_KEY_kana_MA
SCIM_KEY_kana_MI
SCIM_KEY_kana_MU
SCIM_KEY_kana_ME
SCIM_KEY_kana_MO
SCIM_KEY_kana_YA
SCIM_KEY_kana_YU
SCIM_KEY_kana_YO
SCIM_KEY_kana_RA
SCIM_KEY_kana_RI
SCIM_KEY_kana_RU
SCIM_KEY_kana_RE
SCIM_KEY_kana_RO
SCIM_KEY_kana_WA
SCIM_KEY_kana_N
SCIM_KEY_voicedsound
SCIM_KEY_semivoicedsound
SCIM_KEY_kana_switch
SCIM_KEY_Farsi_0
SCIM_KEY_Farsi_1
SCIM_KEY_Farsi_2
SCIM_KEY_Farsi_3
SCIM_KEY_Farsi_4
SCIM_KEY_Farsi_5
SCIM_KEY_Farsi_6
SCIM_KEY_Farsi_7
SCIM_KEY_Farsi_8
SCIM_KEY_Farsi_9
SCIM_KEY_Arabic_percent
SCIM_KEY_Arabic_superscript_alef
SCIM_KEY_Arabic_tteh
SCIM_KEY_Arabic_peh
SCIM_KEY_Arabic_tcheh
SCIM_KEY_Arabic_ddal
SCIM_KEY_Arabic_rreh
SCIM_KEY_Arabic_comma
SCIM_KEY_Arabic_fullstop
SCIM_KEY_Arabic_0
SCIM_KEY_Arabic_1
SCIM_KEY_Arabic_2
SCIM_KEY_Arabic_3
SCIM_KEY_Arabic_4
SCIM_KEY_Arabic_5
SCIM_KEY_Arabic_6
SCIM_KEY_Arabic_7
SCIM_KEY_Arabic_8
SCIM_KEY_Arabic_9
SCIM_KEY_Arabic_semicolon
SCIM_KEY_Arabic_question_mark
SCIM_KEY_Arabic_hamza
SCIM_KEY_Arabic_maddaonalef
SCIM_KEY_Arabic_hamzaonalef
SCIM_KEY_Arabic_hamzaonwaw
SCIM_KEY_Arabic_hamzaunderalef
SCIM_KEY_Arabic_hamzaonyeh
SCIM_KEY_Arabic_alef
SCIM_KEY_Arabic_beh
SCIM_KEY_Arabic_tehmarbuta
SCIM_KEY_Arabic_teh
SCIM_KEY_Arabic_theh
SCIM_KEY_Arabic_jeem
SCIM_KEY_Arabic_hah
SCIM_KEY_Arabic_khah
SCIM_KEY_Arabic_dal
SCIM_KEY_Arabic_thal
SCIM_KEY_Arabic_ra
SCIM_KEY_Arabic_zain
SCIM_KEY_Arabic_seen
SCIM_KEY_Arabic_sheen
SCIM_KEY_Arabic_sad
SCIM_KEY_Arabic_dad
SCIM_KEY_Arabic_tah
SCIM_KEY_Arabic_zah
SCIM_KEY_Arabic_ain
SCIM_KEY_Arabic_ghain
SCIM_KEY_Arabic_tatweel
SCIM_KEY_Arabic_feh
SCIM_KEY_Arabic_qaf
SCIM_KEY_Arabic_kaf
SCIM_KEY_Arabic_lam
SCIM_KEY_Arabic_meem
SCIM_KEY_Arabic_noon
SCIM_KEY_Arabic_ha
SCIM_KEY_Arabic_heh
SCIM_KEY_Arabic_waw
SCIM_KEY_Arabic_alefmaksura
SCIM_KEY_Arabic_yeh
SCIM_KEY_Arabic_fathatan
SCIM_KEY_Arabic_dammatan
SCIM_KEY_Arabic_kasratan
SCIM_KEY_Arabic_fatha
SCIM_KEY_Arabic_damma
SCIM_KEY_Arabic_kasra
SCIM_KEY_Arabic_shadda
SCIM_KEY_Arabic_sukun
SCIM_KEY_Arabic_madda_above
SCIM_KEY_Arabic_hamza_above
SCIM_KEY_Arabic_hamza_below
SCIM_KEY_Arabic_jeh
SCIM_KEY_Arabic_veh
SCIM_KEY_Arabic_keheh
SCIM_KEY_Arabic_gaf
SCIM_KEY_Arabic_noon_ghunna
SCIM_KEY_Arabic_heh_doachashmee
SCIM_KEY_Farsi_yeh
SCIM_KEY_Arabic_farsi_yeh
SCIM_KEY_Arabic_yeh_baree
SCIM_KEY_Arabic_heh_goal
SCIM_KEY_Arabic_switch
SCIM_KEY_Cyrillic_GHE_bar
SCIM_KEY_Cyrillic_ghe_bar
SCIM_KEY_Cyrillic_ZHE_descender
SCIM_KEY_Cyrillic_zhe_descender
SCIM_KEY_Cyrillic_KA_descender
SCIM_KEY_Cyrillic_ka_descender
SCIM_KEY_Cyrillic_KA_vertstroke
SCIM_KEY_Cyrillic_ka_vertstroke
SCIM_KEY_Cyrillic_EN_descender
SCIM_KEY_Cyrillic_en_descender
SCIM_KEY_Cyrillic_U_straight
SCIM_KEY_Cyrillic_u_straight
SCIM_KEY_Cyrillic_U_straight_bar
SCIM_KEY_Cyrillic_u_straight_bar
SCIM_KEY_Cyrillic_HA_descender
SCIM_KEY_Cyrillic_ha_descender
SCIM_KEY_Cyrillic_CHE_descender
SCIM_KEY_Cyrillic_che_descender
SCIM_KEY_Cyrillic_CHE_vertstroke
SCIM_KEY_Cyrillic_che_vertstroke
SCIM_KEY_Cyrillic_SHHA
SCIM_KEY_Cyrillic_shha
SCIM_KEY_Cyrillic_SCHWA
SCIM_KEY_Cyrillic_schwa
SCIM_KEY_Cyrillic_I_macron
SCIM_KEY_Cyrillic_i_macron
SCIM_KEY_Cyrillic_O_bar
SCIM_KEY_Cyrillic_o_bar
SCIM_KEY_Cyrillic_U_macron
SCIM_KEY_Cyrillic_u_macron
SCIM_KEY_Serbian_dje
SCIM_KEY_Macedonia_gje
SCIM_KEY_Cyrillic_io
SCIM_KEY_Ukrainian_ie
SCIM_KEY_Ukranian_je
SCIM_KEY_Macedonia_dse
SCIM_KEY_Ukrainian_i
SCIM_KEY_Ukranian_i
SCIM_KEY_Ukrainian_yi
SCIM_KEY_Ukranian_yi
SCIM_KEY_Cyrillic_je
SCIM_KEY_Serbian_je
SCIM_KEY_Cyrillic_lje
SCIM_KEY_Serbian_lje
SCIM_KEY_Cyrillic_nje
SCIM_KEY_Serbian_nje
SCIM_KEY_Serbian_tshe
SCIM_KEY_Macedonia_kje
SCIM_KEY_Ukrainian_ghe_with_upturn
SCIM_KEY_Byelorussian_shortu
SCIM_KEY_Cyrillic_dzhe
SCIM_KEY_Serbian_dze
SCIM_KEY_numerosign
SCIM_KEY_Serbian_DJE
SCIM_KEY_Macedonia_GJE
SCIM_KEY_Cyrillic_IO
SCIM_KEY_Ukrainian_IE
SCIM_KEY_Ukranian_JE
SCIM_KEY_Macedonia_DSE
SCIM_KEY_Ukrainian_I
SCIM_KEY_Ukranian_I
SCIM_KEY_Ukrainian_YI
SCIM_KEY_Ukranian_YI
SCIM_KEY_Cyrillic_JE
SCIM_KEY_Serbian_JE
SCIM_KEY_Cyrillic_LJE
SCIM_KEY_Serbian_LJE
SCIM_KEY_Cyrillic_NJE
SCIM_KEY_Serbian_NJE
SCIM_KEY_Serbian_TSHE
SCIM_KEY_Macedonia_KJE
SCIM_KEY_Ukrainian_GHE_WITH_UPTURN
SCIM_KEY_Byelorussian_SHORTU
SCIM_KEY_Cyrillic_DZHE
SCIM_KEY_Serbian_DZE
SCIM_KEY_Cyrillic_yu
SCIM_KEY_Cyrillic_a
SCIM_KEY_Cyrillic_be
SCIM_KEY_Cyrillic_tse
SCIM_KEY_Cyrillic_de
SCIM_KEY_Cyrillic_ie
SCIM_KEY_Cyrillic_ef
SCIM_KEY_Cyrillic_ghe
SCIM_KEY_Cyrillic_ha
SCIM_KEY_Cyrillic_i
SCIM_KEY_Cyrillic_shorti
SCIM_KEY_Cyrillic_ka
SCIM_KEY_Cyrillic_el
SCIM_KEY_Cyrillic_em
SCIM_KEY_Cyrillic_en
SCIM_KEY_Cyrillic_o
SCIM_KEY_Cyrillic_pe
SCIM_KEY_Cyrillic_ya
SCIM_KEY_Cyrillic_er
SCIM_KEY_Cyrillic_es
SCIM_KEY_Cyrillic_te
SCIM_KEY_Cyrillic_u
SCIM_KEY_Cyrillic_zhe
SCIM_KEY_Cyrillic_ve
SCIM_KEY_Cyrillic_softsign
SCIM_KEY_Cyrillic_yeru
SCIM_KEY_Cyrillic_ze
SCIM_KEY_Cyrillic_sha
SCIM_KEY_Cyrillic_e
SCIM_KEY_Cyrillic_shcha
SCIM_KEY_Cyrillic_che
SCIM_KEY_Cyrillic_hardsign
SCIM_KEY_Cyrillic_YU
SCIM_KEY_Cyrillic_A
SCIM_KEY_Cyrillic_BE
SCIM_KEY_Cyrillic_TSE
SCIM_KEY_Cyrillic_DE
SCIM_KEY_Cyrillic_IE
SCIM_KEY_Cyrillic_EF
SCIM_KEY_Cyrillic_GHE
SCIM_KEY_Cyrillic_HA
SCIM_KEY_Cyrillic_I
SCIM_KEY_Cyrillic_SHORTI
SCIM_KEY_Cyrillic_KA
SCIM_KEY_Cyrillic_EL
SCIM_KEY_Cyrillic_EM
SCIM_KEY_Cyrillic_EN
SCIM_KEY_Cyrillic_O
SCIM_KEY_Cyrillic_PE
SCIM_KEY_Cyrillic_YA
SCIM_KEY_Cyrillic_ER
SCIM_KEY_Cyrillic_ES
SCIM_KEY_Cyrillic_TE
SCIM_KEY_Cyrillic_U
SCIM_KEY_Cyrillic_ZHE
SCIM_KEY_Cyrillic_VE
SCIM_KEY_Cyrillic_SOFTSIGN
SCIM_KEY_Cyrillic_YERU
SCIM_KEY_Cyrillic_ZE
SCIM_KEY_Cyrillic_SHA
SCIM_KEY_Cyrillic_E
SCIM_KEY_Cyrillic_SHCHA
SCIM_KEY_Cyrillic_CHE
SCIM_KEY_Cyrillic_HARDSIGN
SCIM_KEY_Greek_ALPHAaccent
SCIM_KEY_Greek_EPSILONaccent
SCIM_KEY_Greek_ETAaccent
SCIM_KEY_Greek_IOTAaccent
SCIM_KEY_Greek_IOTAdieresis
SCIM_KEY_Greek_IOTAdiaeresis
SCIM_KEY_Greek_OMICRONaccent
SCIM_KEY_Greek_UPSILONaccent
SCIM_KEY_Greek_UPSILONdieresis
SCIM_KEY_Greek_OMEGAaccent
SCIM_KEY_Greek_accentdieresis
SCIM_KEY_Greek_horizbar
SCIM_KEY_Greek_alphaaccent
SCIM_KEY_Greek_epsilonaccent
SCIM_KEY_Greek_etaaccent
SCIM_KEY_Greek_iotaaccent
SCIM_KEY_Greek_iotadieresis
SCIM_KEY_Greek_iotaaccentdieresis
SCIM_KEY_Greek_omicronaccent
SCIM_KEY_Greek_upsilonaccent
SCIM_KEY_Greek_upsilondieresis
SCIM_KEY_Greek_upsilonaccentdieresis
SCIM_KEY_Greek_omegaaccent
SCIM_KEY_Greek_ALPHA
SCIM_KEY_Greek_BETA
SCIM_KEY_Greek_GAMMA
SCIM_KEY_Greek_DELTA
SCIM_KEY_Greek_EPSILON
SCIM_KEY_Greek_ZETA
SCIM_KEY_Greek_ETA
SCIM_KEY_Greek_THETA
SCIM_KEY_Greek_IOTA
SCIM_KEY_Greek_KAPPA
SCIM_KEY_Greek_LAMDA
SCIM_KEY_Greek_LAMBDA
SCIM_KEY_Greek_MU
SCIM_KEY_Greek_NU
SCIM_KEY_Greek_XI
SCIM_KEY_Greek_OMICRON
SCIM_KEY_Greek_PI
SCIM_KEY_Greek_RHO
SCIM_KEY_Greek_SIGMA
SCIM_KEY_Greek_TAU
SCIM_KEY_Greek_UPSILON
SCIM_KEY_Greek_PHI
SCIM_KEY_Greek_CHI
SCIM_KEY_Greek_PSI
SCIM_KEY_Greek_OMEGA
SCIM_KEY_Greek_alpha
SCIM_KEY_Greek_beta
SCIM_KEY_Greek_gamma
SCIM_KEY_Greek_delta
SCIM_KEY_Greek_epsilon
SCIM_KEY_Greek_zeta
SCIM_KEY_Greek_eta
SCIM_KEY_Greek_theta
SCIM_KEY_Greek_iota
SCIM_KEY_Greek_kappa
SCIM_KEY_Greek_lamda
SCIM_KEY_Greek_lambda
SCIM_KEY_Greek_mu
SCIM_KEY_Greek_nu
SCIM_KEY_Greek_xi
SCIM_KEY_Greek_omicron
SCIM_KEY_Greek_pi
SCIM_KEY_Greek_rho
SCIM_KEY_Greek_sigma
SCIM_KEY_Greek_finalsmallsigma
SCIM_KEY_Greek_tau
SCIM_KEY_Greek_upsilon
SCIM_KEY_Greek_phi
SCIM_KEY_Greek_chi
SCIM_KEY_Greek_psi
SCIM_KEY_Greek_omega
SCIM_KEY_Greek_switch
SCIM_KEY_leftradical
SCIM_KEY_topleftradical
SCIM_KEY_horizconnector
SCIM_KEY_topintegral
SCIM_KEY_botintegral
SCIM_KEY_vertconnector
SCIM_KEY_topleftsqbracket
SCIM_KEY_botleftsqbracket
SCIM_KEY_toprightsqbracket
SCIM_KEY_botrightsqbracket
SCIM_KEY_topleftparens
SCIM_KEY_botleftparens
SCIM_KEY_toprightparens
SCIM_KEY_botrightparens
SCIM_KEY_leftmiddlecurlybrace
SCIM_KEY_rightmiddlecurlybrace
SCIM_KEY_topleftsummation
SCIM_KEY_botleftsummation
SCIM_KEY_topvertsummationconnector
SCIM_KEY_botvertsummationconnector
SCIM_KEY_toprightsummation
SCIM_KEY_botrightsummation
SCIM_KEY_rightmiddlesummation
SCIM_KEY_lessthanequal
SCIM_KEY_notequal
SCIM_KEY_greaterthanequal
SCIM_KEY_integral
SCIM_KEY_therefore
SCIM_KEY_variation
SCIM_KEY_infinity
SCIM_KEY_nabla
SCIM_KEY_approximate
SCIM_KEY_similarequal
SCIM_KEY_ifonlyif
SCIM_KEY_implies
SCIM_KEY_identical
SCIM_KEY_radical
SCIM_KEY_includedin
SCIM_KEY_includes
SCIM_KEY_intersection
SCIM_KEY_union
SCIM_KEY_logicaland
SCIM_KEY_logicalor
SCIM_KEY_partialderivative
SCIM_KEY_function
SCIM_KEY_leftarrow
SCIM_KEY_uparrow
SCIM_KEY_rightarrow
SCIM_KEY_downarrow
SCIM_KEY_blank
SCIM_KEY_soliddiamond
SCIM_KEY_checkerboard
SCIM_KEY_ht
SCIM_KEY_ff
SCIM_KEY_cr
SCIM_KEY_lf
SCIM_KEY_nl
SCIM_KEY_vt
SCIM_KEY_lowrightcorner
SCIM_KEY_uprightcorner
SCIM_KEY_upleftcorner
SCIM_KEY_lowleftcorner
SCIM_KEY_crossinglines
SCIM_KEY_horizlinescan1
SCIM_KEY_horizlinescan3
SCIM_KEY_horizlinescan5
SCIM_KEY_horizlinescan7
SCIM_KEY_horizlinescan9
SCIM_KEY_leftt
SCIM_KEY_rightt
SCIM_KEY_bott
SCIM_KEY_topt
SCIM_KEY_vertbar
SCIM_KEY_emspace
SCIM_KEY_enspace
SCIM_KEY_em3space
SCIM_KEY_em4space
SCIM_KEY_digitspace
SCIM_KEY_punctspace
SCIM_KEY_thinspace
SCIM_KEY_hairspace
SCIM_KEY_emdash
SCIM_KEY_endash
SCIM_KEY_signifblank
SCIM_KEY_ellipsis
SCIM_KEY_doubbaselinedot
SCIM_KEY_onethird
SCIM_KEY_twothirds
SCIM_KEY_onefifth
SCIM_KEY_twofifths
SCIM_KEY_threefifths
SCIM_KEY_fourfifths
SCIM_KEY_onesixth
SCIM_KEY_fivesixths
SCIM_KEY_careof
SCIM_KEY_figdash
SCIM_KEY_leftanglebracket
SCIM_KEY_decimalpoint
SCIM_KEY_rightanglebracket
SCIM_KEY_marker
SCIM_KEY_oneeighth
SCIM_KEY_threeeighths
SCIM_KEY_fiveeighths
SCIM_KEY_seveneighths
SCIM_KEY_trademark
SCIM_KEY_signaturemark
SCIM_KEY_trademarkincircle
SCIM_KEY_leftopentriangle
SCIM_KEY_rightopentriangle
SCIM_KEY_emopencircle
SCIM_KEY_emopenrectangle
SCIM_KEY_leftsinglequotemark
SCIM_KEY_rightsinglequotemark
SCIM_KEY_leftdoublequotemark
SCIM_KEY_rightdoublequotemark
SCIM_KEY_prescription
SCIM_KEY_minutes
SCIM_KEY_seconds
SCIM_KEY_latincross
SCIM_KEY_hexagram
SCIM_KEY_filledrectbullet
SCIM_KEY_filledlefttribullet
SCIM_KEY_filledrighttribullet
SCIM_KEY_emfilledcircle
SCIM_KEY_emfilledrect
SCIM_KEY_enopencircbullet
SCIM_KEY_enopensquarebullet
SCIM_KEY_openrectbullet
SCIM_KEY_opentribulletup
SCIM_KEY_opentribulletdown
SCIM_KEY_openstar
SCIM_KEY_enfilledcircbullet
SCIM_KEY_enfilledsqbullet
SCIM_KEY_filledtribulletup
SCIM_KEY_filledtribulletdown
SCIM_KEY_leftpointer
SCIM_KEY_rightpointer
SCIM_KEY_club
SCIM_KEY_diamond
SCIM_KEY_heart
SCIM_KEY_maltesecross
SCIM_KEY_dagger
SCIM_KEY_doubledagger
SCIM_KEY_checkmark
SCIM_KEY_ballotcross
SCIM_KEY_musicalsharp
SCIM_KEY_musicalflat
SCIM_KEY_malesymbol
SCIM_KEY_femalesymbol
SCIM_KEY_telephone
SCIM_KEY_telephonerecorder
SCIM_KEY_phonographcopyright
SCIM_KEY_caret
SCIM_KEY_singlelowquotemark
SCIM_KEY_doublelowquotemark
SCIM_KEY_cursor
SCIM_KEY_leftcaret
SCIM_KEY_rightcaret
SCIM_KEY_downcaret
SCIM_KEY_upcaret
SCIM_KEY_overbar
SCIM_KEY_downtack
SCIM_KEY_upshoe
SCIM_KEY_downstile
SCIM_KEY_underbar
SCIM_KEY_jot
SCIM_KEY_quad
SCIM_KEY_uptack
SCIM_KEY_circle
SCIM_KEY_upstile
SCIM_KEY_downshoe
SCIM_KEY_rightshoe
SCIM_KEY_leftshoe
SCIM_KEY_lefttack
SCIM_KEY_righttack
SCIM_KEY_hebrew_doublelowline
SCIM_KEY_hebrew_aleph
SCIM_KEY_hebrew_bet
SCIM_KEY_hebrew_beth
SCIM_KEY_hebrew_gimel
SCIM_KEY_hebrew_gimmel
SCIM_KEY_hebrew_dalet
SCIM_KEY_hebrew_daleth
SCIM_KEY_hebrew_he
SCIM_KEY_hebrew_waw
SCIM_KEY_hebrew_zain
SCIM_KEY_hebrew_zayin
SCIM_KEY_hebrew_chet
SCIM_KEY_hebrew_het
SCIM_KEY_hebrew_tet
SCIM_KEY_hebrew_teth
SCIM_KEY_hebrew_yod
SCIM_KEY_hebrew_finalkaph
SCIM_KEY_hebrew_kaph
SCIM_KEY_hebrew_lamed
SCIM_KEY_hebrew_finalmem
SCIM_KEY_hebrew_mem
SCIM_KEY_hebrew_finalnun
SCIM_KEY_hebrew_nun
SCIM_KEY_hebrew_samech
SCIM_KEY_hebrew_samekh
SCIM_KEY_hebrew_ayin
SCIM_KEY_hebrew_finalpe
SCIM_KEY_hebrew_pe
SCIM_KEY_hebrew_finalzade
SCIM_KEY_hebrew_finalzadi
SCIM_KEY_hebrew_zade
SCIM_KEY_hebrew_zadi
SCIM_KEY_hebrew_qoph
SCIM_KEY_hebrew_kuf
SCIM_KEY_hebrew_resh
SCIM_KEY_hebrew_shin
SCIM_KEY_hebrew_taw
SCIM_KEY_hebrew_taf
SCIM_KEY_Hebrew_switch
SCIM_KEY_Thai_kokai
SCIM_KEY_Thai_khokhai
SCIM_KEY_Thai_khokhuat
SCIM_KEY_Thai_khokhwai
SCIM_KEY_Thai_khokhon
SCIM_KEY_Thai_khorakhang
SCIM_KEY_Thai_ngongu
SCIM_KEY_Thai_chochan
SCIM_KEY_Thai_choching
SCIM_KEY_Thai_chochang
SCIM_KEY_Thai_soso
SCIM_KEY_Thai_chochoe
SCIM_KEY_Thai_yoying
SCIM_KEY_Thai_dochada
SCIM_KEY_Thai_topatak
SCIM_KEY_Thai_thothan
SCIM_KEY_Thai_thonangmontho
SCIM_KEY_Thai_thophuthao
SCIM_KEY_Thai_nonen
SCIM_KEY_Thai_dodek
SCIM_KEY_Thai_totao
SCIM_KEY_Thai_thothung
SCIM_KEY_Thai_thothahan
SCIM_KEY_Thai_thothong
SCIM_KEY_Thai_nonu
SCIM_KEY_Thai_bobaimai
SCIM_KEY_Thai_popla
SCIM_KEY_Thai_phophung
SCIM_KEY_Thai_fofa
SCIM_KEY_Thai_phophan
SCIM_KEY_Thai_fofan
SCIM_KEY_Thai_phosamphao
SCIM_KEY_Thai_moma
SCIM_KEY_Thai_yoyak
SCIM_KEY_Thai_rorua
SCIM_KEY_Thai_ru
SCIM_KEY_Thai_loling
SCIM_KEY_Thai_lu
SCIM_KEY_Thai_wowaen
SCIM_KEY_Thai_sosala
SCIM_KEY_Thai_sorusi
SCIM_KEY_Thai_sosua
SCIM_KEY_Thai_hohip
SCIM_KEY_Thai_lochula
SCIM_KEY_Thai_oang
SCIM_KEY_Thai_honokhuk
SCIM_KEY_Thai_paiyannoi
SCIM_KEY_Thai_saraa
SCIM_KEY_Thai_maihanakat
SCIM_KEY_Thai_saraaa
SCIM_KEY_Thai_saraam
SCIM_KEY_Thai_sarai
SCIM_KEY_Thai_saraii
SCIM_KEY_Thai_saraue
SCIM_KEY_Thai_sarauee
SCIM_KEY_Thai_sarau
SCIM_KEY_Thai_sarauu
SCIM_KEY_Thai_phinthu
SCIM_KEY_Thai_maihanakat_maitho
SCIM_KEY_Thai_baht
SCIM_KEY_Thai_sarae
SCIM_KEY_Thai_saraae
SCIM_KEY_Thai_sarao
SCIM_KEY_Thai_saraaimaimuan
SCIM_KEY_Thai_saraaimaimalai
SCIM_KEY_Thai_lakkhangyao
SCIM_KEY_Thai_maiyamok
SCIM_KEY_Thai_maitaikhu
SCIM_KEY_Thai_maiek
SCIM_KEY_Thai_maitho
SCIM_KEY_Thai_maitri
SCIM_KEY_Thai_maichattawa
SCIM_KEY_Thai_thanthakhat
SCIM_KEY_Thai_nikhahit
SCIM_KEY_Thai_leksun
SCIM_KEY_Thai_leknung
SCIM_KEY_Thai_leksong
SCIM_KEY_Thai_leksam
SCIM_KEY_Thai_leksi
SCIM_KEY_Thai_lekha
SCIM_KEY_Thai_lekhok
SCIM_KEY_Thai_lekchet
SCIM_KEY_Thai_lekpaet
SCIM_KEY_Thai_lekkao
SCIM_KEY_Hangul
SCIM_KEY_Hangul_Start
SCIM_KEY_Hangul_End
SCIM_KEY_Hangul_Hanja
SCIM_KEY_Hangul_Jamo
SCIM_KEY_Hangul_Romaja
SCIM_KEY_Hangul_Codeinput
SCIM_KEY_Hangul_Jeonja
SCIM_KEY_Hangul_Banja
SCIM_KEY_Hangul_PreHanja
SCIM_KEY_Hangul_PostHanja
SCIM_KEY_Hangul_SingleCandidate
SCIM_KEY_Hangul_MultipleCandidate
SCIM_KEY_Hangul_PreviousCandidate
SCIM_KEY_Hangul_Special
SCIM_KEY_Hangul_switch
SCIM_KEY_Hangul_Kiyeog
SCIM_KEY_Hangul_SsangKiyeog
SCIM_KEY_Hangul_KiyeogSios
SCIM_KEY_Hangul_Nieun
SCIM_KEY_Hangul_NieunJieuj
SCIM_KEY_Hangul_NieunHieuh
SCIM_KEY_Hangul_Dikeud
SCIM_KEY_Hangul_SsangDikeud
SCIM_KEY_Hangul_Rieul
SCIM_KEY_Hangul_RieulKiyeog
SCIM_KEY_Hangul_RieulMieum
SCIM_KEY_Hangul_RieulPieub
SCIM_KEY_Hangul_RieulSios
SCIM_KEY_Hangul_RieulTieut
SCIM_KEY_Hangul_RieulPhieuf
SCIM_KEY_Hangul_RieulHieuh
SCIM_KEY_Hangul_Mieum
SCIM_KEY_Hangul_Pieub
SCIM_KEY_Hangul_SsangPieub
SCIM_KEY_Hangul_PieubSios
SCIM_KEY_Hangul_Sios
SCIM_KEY_Hangul_SsangSios
SCIM_KEY_Hangul_Ieung
SCIM_KEY_Hangul_Jieuj
SCIM_KEY_Hangul_SsangJieuj
SCIM_KEY_Hangul_Cieuc
SCIM_KEY_Hangul_Khieuq
SCIM_KEY_Hangul_Tieut
SCIM_KEY_Hangul_Phieuf
SCIM_KEY_Hangul_Hieuh
SCIM_KEY_Hangul_A
SCIM_KEY_Hangul_AE
SCIM_KEY_Hangul_YA
SCIM_KEY_Hangul_YAE
SCIM_KEY_Hangul_EO
SCIM_KEY_Hangul_E
SCIM_KEY_Hangul_YEO
SCIM_KEY_Hangul_YE
SCIM_KEY_Hangul_O
SCIM_KEY_Hangul_WA
SCIM_KEY_Hangul_WAE
SCIM_KEY_Hangul_OE
SCIM_KEY_Hangul_YO
SCIM_KEY_Hangul_U
SCIM_KEY_Hangul_WEO
SCIM_KEY_Hangul_WE
SCIM_KEY_Hangul_WI
SCIM_KEY_Hangul_YU
SCIM_KEY_Hangul_EU
SCIM_KEY_Hangul_YI
SCIM_KEY_Hangul_I
SCIM_KEY_Hangul_J_Kiyeog
SCIM_KEY_Hangul_J_SsangKiyeog
SCIM_KEY_Hangul_J_KiyeogSios
SCIM_KEY_Hangul_J_Nieun
SCIM_KEY_Hangul_J_NieunJieuj
SCIM_KEY_Hangul_J_NieunHieuh
SCIM_KEY_Hangul_J_Dikeud
SCIM_KEY_Hangul_J_Rieul
SCIM_KEY_Hangul_J_RieulKiyeog
SCIM_KEY_Hangul_J_RieulMieum
SCIM_KEY_Hangul_J_RieulPieub
SCIM_KEY_Hangul_J_RieulSios
SCIM_KEY_Hangul_J_RieulTieut
SCIM_KEY_Hangul_J_RieulPhieuf
SCIM_KEY_Hangul_J_RieulHieuh
SCIM_KEY_Hangul_J_Mieum
SCIM_KEY_Hangul_J_Pieub
SCIM_KEY_Hangul_J_PieubSios
SCIM_KEY_Hangul_J_Sios
SCIM_KEY_Hangul_J_SsangSios
SCIM_KEY_Hangul_J_Ieung
SCIM_KEY_Hangul_J_Jieuj
SCIM_KEY_Hangul_J_Cieuc
SCIM_KEY_Hangul_J_Khieuq
SCIM_KEY_Hangul_J_Tieut
SCIM_KEY_Hangul_J_Phieuf
SCIM_KEY_Hangul_J_Hieuh
SCIM_KEY_Hangul_RieulYeorinHieuh
SCIM_KEY_Hangul_SunkyeongeumMieum
SCIM_KEY_Hangul_SunkyeongeumPieub
SCIM_KEY_Hangul_PanSios
SCIM_KEY_Hangul_KkogjiDalrinIeung
SCIM_KEY_Hangul_SunkyeongeumPhieuf
SCIM_KEY_Hangul_YeorinHieuh
SCIM_KEY_Hangul_AraeA
SCIM_KEY_Hangul_AraeAE
SCIM_KEY_Hangul_J_PanSios
SCIM_KEY_Hangul_J_KkogjiDalrinIeung
SCIM_KEY_Hangul_J_YeorinHieuh
SCIM_KEY_Korean_Won
SCIM_KEY_Armenian_eternity
SCIM_KEY_Armenian_ligature_ew
SCIM_KEY_Armenian_full_stop
SCIM_KEY_Armenian_verjaket
SCIM_KEY_Armenian_parenright
SCIM_KEY_Armenian_parenleft
SCIM_KEY_Armenian_guillemotright
SCIM_KEY_Armenian_guillemotleft
SCIM_KEY_Armenian_em_dash
SCIM_KEY_Armenian_dot
SCIM_KEY_Armenian_mijaket
SCIM_KEY_Armenian_separation_mark
SCIM_KEY_Armenian_but
SCIM_KEY_Armenian_comma
SCIM_KEY_Armenian_en_dash
SCIM_KEY_Armenian_hyphen
SCIM_KEY_Armenian_yentamna
SCIM_KEY_Armenian_ellipsis
SCIM_KEY_Armenian_exclam
SCIM_KEY_Armenian_amanak
SCIM_KEY_Armenian_accent
SCIM_KEY_Armenian_shesht
SCIM_KEY_Armenian_question
SCIM_KEY_Armenian_paruyk
SCIM_KEY_Armenian_AYB
SCIM_KEY_Armenian_ayb
SCIM_KEY_Armenian_BEN
SCIM_KEY_Armenian_ben
SCIM_KEY_Armenian_GIM
SCIM_KEY_Armenian_gim
SCIM_KEY_Armenian_DA
SCIM_KEY_Armenian_da
SCIM_KEY_Armenian_YECH
SCIM_KEY_Armenian_yech
SCIM_KEY_Armenian_ZA
SCIM_KEY_Armenian_za
SCIM_KEY_Armenian_E
SCIM_KEY_Armenian_e
SCIM_KEY_Armenian_AT
SCIM_KEY_Armenian_at
SCIM_KEY_Armenian_TO
SCIM_KEY_Armenian_to
SCIM_KEY_Armenian_ZHE
SCIM_KEY_Armenian_zhe
SCIM_KEY_Armenian_INI
SCIM_KEY_Armenian_ini
SCIM_KEY_Armenian_LYUN
SCIM_KEY_Armenian_lyun
SCIM_KEY_Armenian_KHE
SCIM_KEY_Armenian_khe
SCIM_KEY_Armenian_TSA
SCIM_KEY_Armenian_tsa
SCIM_KEY_Armenian_KEN
SCIM_KEY_Armenian_ken
SCIM_KEY_Armenian_HO
SCIM_KEY_Armenian_ho
SCIM_KEY_Armenian_DZA
SCIM_KEY_Armenian_dza
SCIM_KEY_Armenian_GHAT
SCIM_KEY_Armenian_ghat
SCIM_KEY_Armenian_TCHE
SCIM_KEY_Armenian_tche
SCIM_KEY_Armenian_MEN
SCIM_KEY_Armenian_men
SCIM_KEY_Armenian_HI
SCIM_KEY_Armenian_hi
SCIM_KEY_Armenian_NU
SCIM_KEY_Armenian_nu
SCIM_KEY_Armenian_SHA
SCIM_KEY_Armenian_sha
SCIM_KEY_Armenian_VO
SCIM_KEY_Armenian_vo
SCIM_KEY_Armenian_CHA
SCIM_KEY_Armenian_cha
SCIM_KEY_Armenian_PE
SCIM_KEY_Armenian_pe
SCIM_KEY_Armenian_JE
SCIM_KEY_Armenian_je
SCIM_KEY_Armenian_RA
SCIM_KEY_Armenian_ra
SCIM_KEY_Armenian_SE
SCIM_KEY_Armenian_se
SCIM_KEY_Armenian_VEV
SCIM_KEY_Armenian_vev
SCIM_KEY_Armenian_TYUN
SCIM_KEY_Armenian_tyun
SCIM_KEY_Armenian_RE
SCIM_KEY_Armenian_re
SCIM_KEY_Armenian_TSO
SCIM_KEY_Armenian_tso
SCIM_KEY_Armenian_VYUN
SCIM_KEY_Armenian_vyun
SCIM_KEY_Armenian_PYUR
SCIM_KEY_Armenian_pyur
SCIM_KEY_Armenian_KE
SCIM_KEY_Armenian_ke
SCIM_KEY_Armenian_O
SCIM_KEY_Armenian_o
SCIM_KEY_Armenian_FE
SCIM_KEY_Armenian_fe
SCIM_KEY_Armenian_apostrophe
SCIM_KEY_Armenian_section_sign
SCIM_KEY_Georgian_an
SCIM_KEY_Georgian_ban
SCIM_KEY_Georgian_gan
SCIM_KEY_Georgian_don
SCIM_KEY_Georgian_en
SCIM_KEY_Georgian_vin
SCIM_KEY_Georgian_zen
SCIM_KEY_Georgian_tan
SCIM_KEY_Georgian_in
SCIM_KEY_Georgian_kan
SCIM_KEY_Georgian_las
SCIM_KEY_Georgian_man
SCIM_KEY_Georgian_nar
SCIM_KEY_Georgian_on
SCIM_KEY_Georgian_par
SCIM_KEY_Georgian_zhar
SCIM_KEY_Georgian_rae
SCIM_KEY_Georgian_san
SCIM_KEY_Georgian_tar
SCIM_KEY_Georgian_un
SCIM_KEY_Georgian_phar
SCIM_KEY_Georgian_khar
SCIM_KEY_Georgian_ghan
SCIM_KEY_Georgian_qar
SCIM_KEY_Georgian_shin
SCIM_KEY_Georgian_chin
SCIM_KEY_Georgian_can
SCIM_KEY_Georgian_jil
SCIM_KEY_Georgian_cil
SCIM_KEY_Georgian_char
SCIM_KEY_Georgian_xan
SCIM_KEY_Georgian_jhan
SCIM_KEY_Georgian_hae
SCIM_KEY_Georgian_he
SCIM_KEY_Georgian_hie
SCIM_KEY_Georgian_we
SCIM_KEY_Georgian_har
SCIM_KEY_Georgian_hoe
SCIM_KEY_Georgian_fi
SCIM_KEY_Ccedillaabovedot
SCIM_KEY_Xabovedot
SCIM_KEY_Qabovedot
SCIM_KEY_Ibreve
SCIM_KEY_IE
SCIM_KEY_UO
SCIM_KEY_Zstroke
SCIM_KEY_Gcaron
SCIM_KEY_Obarred
SCIM_KEY_ccedillaabovedot
SCIM_KEY_xabovedot
SCIM_KEY_Ocaron
SCIM_KEY_qabovedot
SCIM_KEY_ibreve
SCIM_KEY_ie
SCIM_KEY_uo
SCIM_KEY_zstroke
SCIM_KEY_gcaron
SCIM_KEY_ocaron
SCIM_KEY_obarred
SCIM_KEY_SCHWA
SCIM_KEY_schwa
SCIM_KEY_Lbelowdot
SCIM_KEY_Lstrokebelowdot
SCIM_KEY_lbelowdot
SCIM_KEY_lstrokebelowdot
SCIM_KEY_Gtilde
SCIM_KEY_gtilde
SCIM_KEY_Abelowdot
SCIM_KEY_abelowdot
SCIM_KEY_Ahook
SCIM_KEY_ahook
SCIM_KEY_Acircumflexacute
SCIM_KEY_acircumflexacute
SCIM_KEY_Acircumflexgrave
SCIM_KEY_acircumflexgrave
SCIM_KEY_Acircumflexhook
SCIM_KEY_acircumflexhook
SCIM_KEY_Acircumflextilde
SCIM_KEY_acircumflextilde
SCIM_KEY_Acircumflexbelowdot
SCIM_KEY_acircumflexbelowdot
SCIM_KEY_Abreveacute
SCIM_KEY_abreveacute
SCIM_KEY_Abrevegrave
SCIM_KEY_abrevegrave
SCIM_KEY_Abrevehook
SCIM_KEY_abrevehook
SCIM_KEY_Abrevetilde
SCIM_KEY_abrevetilde
SCIM_KEY_Abrevebelowdot
SCIM_KEY_abrevebelowdot
SCIM_KEY_Ebelowdot
SCIM_KEY_ebelowdot
SCIM_KEY_Ehook
SCIM_KEY_ehook
SCIM_KEY_Etilde
SCIM_KEY_etilde
SCIM_KEY_Ecircumflexacute
SCIM_KEY_ecircumflexacute
SCIM_KEY_Ecircumflexgrave
SCIM_KEY_ecircumflexgrave
SCIM_KEY_Ecircumflexhook
SCIM_KEY_ecircumflexhook
SCIM_KEY_Ecircumflextilde
SCIM_KEY_ecircumflextilde
SCIM_KEY_Ecircumflexbelowdot
SCIM_KEY_ecircumflexbelowdot
SCIM_KEY_Ihook
SCIM_KEY_ihook
SCIM_KEY_Ibelowdot
SCIM_KEY_ibelowdot
SCIM_KEY_Obelowdot
SCIM_KEY_obelowdot
SCIM_KEY_Ohook
SCIM_KEY_ohook
SCIM_KEY_Ocircumflexacute
SCIM_KEY_ocircumflexacute
SCIM_KEY_Ocircumflexgrave
SCIM_KEY_ocircumflexgrave
SCIM_KEY_Ocircumflexhook
SCIM_KEY_ocircumflexhook
SCIM_KEY_Ocircumflextilde
SCIM_KEY_ocircumflextilde
SCIM_KEY_Ocircumflexbelowdot
SCIM_KEY_ocircumflexbelowdot
SCIM_KEY_Ohornacute
SCIM_KEY_ohornacute
SCIM_KEY_Ohorngrave
SCIM_KEY_ohorngrave
SCIM_KEY_Ohornhook
SCIM_KEY_ohornhook
SCIM_KEY_Ohorntilde
SCIM_KEY_ohorntilde
SCIM_KEY_Ohornbelowdot
SCIM_KEY_ohornbelowdot
SCIM_KEY_Ubelowdot
SCIM_KEY_ubelowdot
SCIM_KEY_Uhook
SCIM_KEY_uhook
SCIM_KEY_Uhornacute
SCIM_KEY_uhornacute
SCIM_KEY_Uhorngrave
SCIM_KEY_uhorngrave
SCIM_KEY_Uhornhook
SCIM_KEY_uhornhook
SCIM_KEY_Uhorntilde
SCIM_KEY_uhorntilde
SCIM_KEY_Uhornbelowdot
SCIM_KEY_uhornbelowdot
SCIM_KEY_Ybelowdot
SCIM_KEY_ybelowdot
SCIM_KEY_Yhook
SCIM_KEY_yhook
SCIM_KEY_Ytilde
SCIM_KEY_ytilde
SCIM_KEY_Ohorn
SCIM_KEY_ohorn
SCIM_KEY_Uhorn
SCIM_KEY_uhorn
SCIM_KEY_combining_tilde
SCIM_KEY_combining_grave
SCIM_KEY_combining_acute
SCIM_KEY_combining_hook
SCIM_KEY_combining_belowdot
SCIM_KEY_EcuSign
SCIM_KEY_ColonSign
SCIM_KEY_CruzeiroSign
SCIM_KEY_FFrancSign
SCIM_KEY_LiraSign
SCIM_KEY_MillSign
SCIM_KEY_NairaSign
SCIM_KEY_PesetaSign
SCIM_KEY_RupeeSign
SCIM_KEY_WonSign
SCIM_KEY_NewSheqelSign
SCIM_KEY_DongSign
SCIM_KEY_EuroSign
enum scim::KeyboardLayout
Enum values of all valid Keyboard Layout type.
This types are used by the Keyboard Layout mapping function of KeyEvent class to map a KeyEvent of a certain Keyboard Layout to another.
But this function only covers the key range of default US PC keyboard. All additional keys in other layouts will never be mapped.
The default layout is standard US PC keyboard.
If the layout of a KeyEvent is Unknown, then it'll never be mapped.
Enumerator
SCIM_KEYBOARD_Unknown
SCIM_KEYBOARD_Default
SCIM_KEYBOARD_US
SCIM_KEYBOARD_Belgian
SCIM_KEYBOARD_Croatian
SCIM_KEYBOARD_Czech
SCIM_KEYBOARD_Czech_Qwerty
SCIM_KEYBOARD_Danish
SCIM_KEYBOARD_Dutch
SCIM_KEYBOARD_Dvorak
SCIM_KEYBOARD_Estonian
SCIM_KEYBOARD_Finnish
SCIM_KEYBOARD_French
SCIM_KEYBOARD_French_Canadian
SCIM_KEYBOARD_French_Switzerland
SCIM_KEYBOARD_German
SCIM_KEYBOARD_German_Deadkeys
SCIM_KEYBOARD_German_Swiss
SCIM_KEYBOARD_Greek
SCIM_KEYBOARD_Hungarian
SCIM_KEYBOARD_Italian
SCIM_KEYBOARD_Japanese
SCIM_KEYBOARD_Norwegian
SCIM_KEYBOARD_Polish
SCIM_KEYBOARD_Portuguese
SCIM_KEYBOARD_Portuguese_Brazil
SCIM_KEYBOARD_Portuguese_Brazil_US_Accents
SCIM_KEYBOARD_Russian
SCIM_KEYBOARD_Slovak
SCIM_KEYBOARD_Slovak_Qwerty
SCIM_KEYBOARD_Slovene
SCIM_KEYBOARD_Spanish
SCIM_KEYBOARD_Spanish_CP850
SCIM_KEYBOARD_Spanish_Latin_America
SCIM_KEYBOARD_Swedish
SCIM_KEYBOARD_Turkish
SCIM_KEYBOARD_UK
SCIM_KEYBOARD_Icelandic
SCIM_KEYBOARD_Lithuanian
SCIM_KEYBOARD_Ukrainian
SCIM_KEYBOARD_NUM_LAYOUTS
enum scim::FrontEndHotkeyAction
FrontEnd actions which could be binded with Hotkeys.
Enumerator
SCIM_FRONTEND_HOTKEY_NOOP
No action
SCIM_FRONTEND_HOTKEY_TRIGGER
Turn on/off the input method.
SCIM_FRONTEND_HOTKEY_ON
Turn on the input method.
SCIM_FRONTEND_HOTKEY_OFF
Turn off the input method.
SCIM_FRONTEND_HOTKEY_NEXT_FACTORY
Switch current Input Context to use the next available IMEngine Factory.
SCIM_FRONTEND_HOTKEY_PREVIOUS_FACTORY
Switch current Input Context to use the previous available IMEngine Factory.
SCIM_FRONTEND_HOTKEY_SHOW_FACTORY_MENU
Show a menu of all available IMEngine Factories.
Function Documentation
bool scim::operator< (const Attribute & lhs, const Attribute & rhs) inline
References scim::Attribute::get_length(), scim::Attribute::get_start(), scim::Attribute::get_type(), and scim::Attribute::get_value().
bool scim::scim_key_to_string (String & str, const KeyEvent & key)
Convert a key event to a string.
Parameters
str - the result string will be stored here.
key - the KeyEvent to be converted.
Returns
true if success.
bool scim::scim_string_to_key (KeyEvent & key, const String & str)
Convert a string to a KeyEvent.
Parameters
key - the result KeyEvent will be stored here.
str - the string to be converted.
Returns
true if success.
Referenced by scim::KeyEvent::KeyEvent().
bool scim::scim_key_list_to_string (String & str, const KeyEventList & keylist)
Convert a set of KeyEvents to a string.
Parameters
str - the result string will be stored here.
keylist - the keys to be converted.
Returns
true if success.
bool scim::scim_string_to_key_list (KeyEventList & keylist, const String & str)
Covnert a string to a set of KeyEvents.
Parameters
keylist - the result KeyEvents will be stored here.
str - the string to be converted.
Returns
true if success.
String scim::scim_keyboard_layout_to_string (KeyboardLayout layout)
Convert a Keyboard Layout enum value to its String name.
Parameters
layout The Keyboard Layout type.
Returns
The name of this layout.
KeyboardLayout scim::scim_string_to_keyboard_layout (const String & str)
Convert a String name to the corresponding Keyboard Layout value.
Parameters
str The Keyboard Layout name.
Returns
The Keyboard Layout type corresponding to this name, or SCIM_KEYBOARD_Unknown.
String scim::scim_keyboard_layout_get_display_name (KeyboardLayout layout)
Get the display name of a Keyboard Layout enum value.
Parameters
layout The Keyboard Layout type.
Returns
The localized display name of this layout.
KeyboardLayout scim::scim_get_default_keyboard_layout ()
Get default Keyboard Layout setting.
This function return the Keyboard Layout setting stored in global config repository as /DefaultKeyboardLayout key.
This function is mainly used by FrontEnds and Setup tools. IMEngines should not use it.
void scim::scim_set_default_keyboard_layout (KeyboardLayout layout)
Change the default Keyboard Layout setting.
The default layout setting will be stored in global config repository as /DefaultKeyboardLayout key.
This function is mainly used by FrontEnds and Setup tools. IMEngines should not use it.
String scim::scim_global_config_read (const String & key, const String & defVal = String())
Read a string value from the global configuration file.
Parameters
key The key to be read, like /PanelProgram etc.
defVal The default value to be returned if there is no such key in the configuration file.
Returns
the value string of the key.
int scim::scim_global_config_read (const String & key, int defVal)
Read an int value from the global configuration file.
Parameters
key The key to be read, like /SocketTimeout etc.
defVal The default value to be returned if there is no such key in the configuration file.
Returns
the value of the key.
bool scim::scim_global_config_read (const String & key, bool defVal)
Read a bool value from the global configuration file.
Parameters
key The key to be read.
defVal The default value to be returned if there is no such key in the configuration file.
Returns
the value of the key.
double scim::scim_global_config_read (const String & key, double defVal)
Read a double value from the global configuration file.
Parameters
key The key to be read.
defVal The default value to be returned if there is no such key in the configuration file.
Returns
the value of the key.
std::vector<String> scim::scim_global_config_read (const String & key, const std::vector< String > & defVal)
Read a string list from the global configuration file.
Parameters
key The key to be read.
defVal The default value to be returned if there is no such key in the configuration file.
Returns
the value of the key.
std::vector<int> scim::scim_global_config_read (const String & key, const std::vector< int > & defVal)
Read an int list from the global configuration file.
Parameters
key The key to be read.
defVal The default value to be returned if there is no such key in the configuration file.
Returns
the value of the key.
void scim::scim_global_config_write (const String & key, const String & val)
Write a string value into the user global config.
Parameters
key The key to be associated.
val The string value to be written.
void scim::scim_global_config_write (const String & key, int val)
Write an int value into the user global config.
Parameters
key The key to be associated.
val The int value to be written.
void scim::scim_global_config_write (const String & key, bool val)
Write a bool value into the user global config.
Parameters
key The key to be associated.
val The bool value to be written.
void scim::scim_global_config_write (const String & key, double val)
Write a double value into the user global config.
Parameters
key The key to be associated.
val The double value to be written.
void scim::scim_global_config_write (const String & key, const std::vector< String > & val)
Write a string list into the user global config.
Parameters
key The key to be associated.
val The string list to be written.
void scim::scim_global_config_write (const String & key, const std::vector< int > & val)
Write an int list into the user global config.
Parameters
key The key to be associated.
val The int list to be written.
void scim::scim_global_config_reset (const String & key)
Reset the value associated to the specified key to its default value.
Parameters
key The key to be reset.
bool scim::scim_global_config_flush ()
Flush the updated global config into user global config file.
Returns
true if success.
int scim::scim_get_module_list (std::vector< String > & mod_list, const String & type = "")
template<typename T1 , typename T2 > bool scim::operator== (const Pointer< T1 > & t1, const Pointer< T2 > & t2) inline
Compares two Pointers.
Returns
true if both Pointers manage to same dumb pointer.
template<typename T1 , typename T2 > bool scim::operator!= (const Pointer< T1 > & t1, const Pointer< T2 > & t2) inline
Compares two Pointers.
Returns
true if both Pointers manage a different dumb pointer.
template<typename To , typename From > Pointer<To> scim::cast_const (const Pointer< From > & from) inline
Removes the const qualifier from a managed const dumb pointer.
Parameters
from - a Pointer that manages a const dumb pointer.
Returns
a new Pointer that manages the non-const dumb pointer.
Calls const_cast on the dumb pointer and returns the non-const pointer as a new Pointer.
References scim::Pointer< T >::get().
template<typename To , typename From > Pointer<To> scim::cast_dynamic (const Pointer< From > & from) inline
Casts a managed polymophic dumb pointer down or across its inheritance heirarchy.
Parameters
from - a Pointer managing a polymophic dumb pointer of type From.
Returns
a new Pointer managing the dumb pointer as a base or sibling pointer of type To.
Calls dynmaic_cast to safely cast a managed polymophic dumb pointer of type From to a base, derived or sibling class pointer of type To.
References scim::Pointer< T >::get().
template<typename To , typename From > Pointer<To> scim::cast_static (const Pointer< From > & from) inline
Casts a managed dumb pointer to a pointer to a related type.
Parameters
from - a Pointer managing a dumb pointer of type From.
Returns
a new Pointer managing the dumb pointer as a pointer of type To.
Calls static_cast to cast a dumb pointer of type From to a pointer of type To.
References scim::Pointer< T >::get().
bool scim::operator< (const Property & lhs, const Property & rhs) inline
References scim::Property::get_key().
bool scim::operator< (const Property & lhs, const String & rhs) inline
References scim::Property::get_key().
bool scim::operator< (const String & lhs, const Property & rhs) inline
References scim::Property::get_key().
bool scim::operator== (const Property & lhs, const Property & rhs) inline
References scim::Property::get_key().
bool scim::operator== (const Property & lhs, const String & rhs) inline
References scim::Property::get_key().
bool scim::operator== (const String & lhs, const Property & rhs) inline
References scim::Property::get_key().
bool scim::operator!= (const Property & lhs, const Property & rhs) inline
References scim::Property::get_key().
bool scim::operator!= (const Property & lhs, const String & rhs) inline
References scim::Property::get_key().
bool scim::operator!= (const String & lhs, const Property & rhs) inline
References scim::Property::get_key().
int scim::utf8_mbtowc (ucs4_t * pwc, const unsigned char * src, int src_len)
Convert an utf8 char sequence to ucs4.
Parameters
pwc destination buffer to store the ucs4 code.
src source buffer contains the utf8 char sequence.
src_len the size of source buffer.
Returns
number of chars in s actually converted.
int scim::utf8_wctomb (unsigned char * dest, ucs4_t wc, int dest_size)
Convert an ucs4 code to utf8 char sequence.
Parameters
dest destination buffer to store utf8 char sequence.
wc the ucs4 code to be converted.
dest_size the size of destination buffer.
Returns
the number of bytes actually written into dest.
WideString scim::utf8_mbstowcs (const String & str)
Convert an utf8 string to an ucs4 string.
Parameters
str source utf8 string.
Returns
the destination widestring.
WideString scim::utf8_mbstowcs (const char * str, int len = -1)
Convert an utf8 string to an ucs4 string.
Parameters
str source utf8 string.
len length of the source string.
Returns
the destination widestring.
String scim::utf8_wcstombs (const WideString & wstr)
Convert an ucs4 string to an utf8 string.
Parameters
wstr source ucs4 string.
Returns
the destination utf8 string.
String scim::utf8_wcstombs (const ucs4_t * wstr, int len = -1)
Convert an ucs4 string to an utf8 string.
Parameters
wstr source ucs4 string.
len length of the source string.
Returns
the destination utf8 string.
ucs4_t scim::utf8_read_wchar (std::istream & is)
Read a wide char from istream.
The content in the istream are actually in utf-8 encoding.
Parameters
is the stream to be read.
Returns
if equal to 0 then got the end of the stream or error occurred.
std::ostream& scim::utf8_write_wchar (std::ostream & os, ucs4_t wc)
Write a wide char to ostream.
The content written into the ostream will be converted into utf-8 encoding.
Parameters
os the stream to be written.
wc the wide char to be written to the stream.
Returns
the same stream object reference.
WideString scim::utf8_read_wstring (std::istream & is, ucs4_t delim = (ucs4_t) '\n', bool rm_delim = true)
Read a wide string from istream.
The content in the istream are actually in utf-8 encoding.
Parameters
is the stream to be read.
delim the delimiter of the string.
rm_delim if the delim should be removed from the destination string.
Returns
the wide string read from the given stream.
std::ostream& scim::utf8_write_wstring (std::ostream & os, const WideString & wstr)
Write a wide string to ostream.
The content written into the ostream will be converted into utf-8 encoding.
Parameters
os the stream to be written.
wstr the wide string to be written into the stream.
Returns
the same stream object reference.
void scim::scim_uint32tobytes (unsigned char * bytes, uint32 n) inline
Convert an uint32 variable into a sequence of bytes.
Parameters
bytes the buffer to store the result.
n the variable to be converted.
uint32 scim::scim_bytestouint32 (const unsigned char * bytes) inline
Convert a sequence of bytes into an uint32 value.
Parameters
bytes the buffer contains the bytes to be converted.
Returns
the result uint32 value.
void scim::scim_uint16tobytes (unsigned char * bytes, uint16 n) inline
Convert an uint16 variable into a sequence of bytes.
Parameters
bytes the buffer to store the result.
n the variable to be converted.
uint16 scim::scim_bytestouint16 (const unsigned char * bytes) inline
Convert a sequence of bytes into an uint16 value.
Parameters
bytes the buffer contains the bytes to be converted.
Returns
the result uint16 value.
String scim::scim_validate_locale (const String & locale)
Test if the locale is valid, and return the good locale name.
Parameters
locale the locale to be tested.
Returns
If the locale is valid, it's the good locale name, otherwise empty.
String scim::scim_get_locale_encoding (const String & locale)
Get the encoding for a locale.
Parameters
locale the name of the locale.
Returns
The encoding used by the given locale.
String scim::scim_get_current_locale ()
Get current system locale.
Returns
The current system locale.
String scim::scim_get_current_language ()
Get current system language.
Returns
The current system language.
int scim::scim_get_locale_maxlen (const String & locale)
Get the max length of the multibyte char of a locale.
Parameters
locale the name of the locale.
Returns
the maxlen of this locale.
int scim::scim_split_string_list (std::vector< String > & vec, const String & str, char delim = ',')
Split string list into a string vector according to the delim char.
Parameters
vec the string vector to store the result.
str the string to be splitted.
delim the delimiter to split the strings.
Returns
the number of the strings in the result list.
String scim::scim_combine_string_list (const std::vector< String > & vec, char delim = ',')
Combine a string vector into one string list, separated by char delim.
Parameters
vec the string vector which contains the strings to be combined.
delim the delimiter which should be put between two strings.
Returns
the result string.
bool scim::scim_is_little_endian ()
Get machine endian type.
Returns
1 little endian, 0 big endian
bool scim::scim_if_wchar_ucs4_equal ()
Test if wchar_t is using UCS4 encoding.
ucs4_t scim::scim_wchar_to_full_width (ucs4_t code)
Convert a half width unicode char to its full width counterpart.
ucs4_t scim::scim_wchar_to_half_width (ucs4_t code)
Convert a full width unicode char to its half width counterpart.
String scim::scim_get_home_dir ()
Get the home dir of current user.
String scim::scim_get_user_name ()
Get the name of current user.
String scim::scim_get_user_data_dir ()
Get SCIM data dir of current user.
size_t scim::scim_load_file (const String & filename, char ** bufptr)
Load a file into memory.
Parameters
filename the name of the file to be loaded.
bufptr the place to store the newly allocated buffer pointer, if bufptr == NULL then the file is not actually loaded, just return the file size. The pointer *bufptr must be deleted afterwards.
Returns
the size of the data actually loaded (mostly, it's the file size), zero means load failed.
bool scim::scim_make_dir (const String & dir)
Make a directory.
Parameters
dir the dir path to be created.
Returns
true if sucess.
String scim::scim_get_language_name (const String & lang)
Get the localized name of a language id.
Parameters
lang the language id.
Returns
the localized name of this language, in utf8 encoding.
String scim::scim_get_language_name_english (const String & lang)
Get the English name of a language id.
Parameters
lang the language id.
Returns
the English name of this language, in utf8 encoding.
String scim::scim_get_language_name_untranslated (const String & lang)
Get the untranslated name of a language id.
Parameters
lang the language id.
Returns
the untranslated name of this language, in utf8 encoding.
String scim::scim_get_language_locales (const String & lang)
Get the supported locales for a language.
For example language zh_CN may support zh_CN.UTF-8, zh_CN.GB18030, zh_CN.GBK, zh_CN.GB2312 locales.
Parameters
lang the language id.
Returns
the supported locales separated by comma.
String scim::scim_get_locale_language (const String & locale)
Get the language id for a locale.
Parameters
locale the locale name
Returns
the language id for this locale.
String scim::scim_validate_language (const String & lang)
Test if the language is valid, and return the good language code.
Parameters
lang the language to be tested.
Returns
If the language is valid, return the good language id, otherwise return "~other".
String scim::scim_get_normalized_language (const String & lang)
Get the normalized language id of a language.
Some short language id will be normalized to it's full id, for example: "ja" -> "ja_JP" "ko" -> "ko_KR" "zh" -> "zh_CN"
furthermore, zh_HK will be normalized to zh_TW, zh_SG will be normalized to zh_CN.
Parameters
lang the original language
Returns
the normalized language code.
int scim::scim_launch (bool daemon, const String & config, const String & imengines, const String & frontend, char *const argv[] = 0)
Launch a SCIM process with specific options.
Parameters
daemon If true then launch scim in a daemon process, otherwise the current process will be stopped until the newly created process exit.
config The Config module to be used.
imengines The IMEngines to be loaded, separated by comma.
frontend The FrontEnd module to be used.
argv Additional arguments passed to the new process's FrontEnd. Must terminated by a NULL pointer.
Returns
Return 0 means the process started/exited without any problem, otherwise means an error occurred.
int scim::scim_launch_panel (bool daemon, const String & config, const String & display, char *const argv[] = 0)
Launch a SCIM Panel process with specific options.
Parameters
daemon If true then launch scim in a daemon process, otherwise the current process will be stopped until the newly created process exit.
config The Config module to be used.
display The display name on which the panel runs. eg. for X11 : localhost:0.0
argv Additional arguments passed to the new process's FrontEnd. Must terminated by a NULL pointer.
Returns
Return 0 means the process started/exited without any problem, otherwise means an error occurred.
void scim::scim_usleep (unsigned int usec)
Sleep some microseconds.
Parameters
usec The amount of microseconds to be sleeped.
void scim::scim_daemon ()
Switch process into daemon mode.
Variable Documentation
const unsigned int scim::SCIM_ATTR_DECORATE_NONE = 0
No decorate.
const unsigned int scim::SCIM_ATTR_DECORATE_UNDERLINE = 1
Draw a line under the text.
const unsigned int scim::SCIM_ATTR_DECORATE_HIGHLIGHT = 2
Draw the text in highlighted color.
const unsigned int scim::SCIM_ATTR_DECORATE_REVERSE = 4
Draw the text in reverse color mode.